### PR TITLE
 StoreConfig always initializes the account if it is missing

### LINKED ISSUE #3754: ACME key seems to not persist
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

I've started with *fresh config*. I don't have an `acme.json` and don't use the migration path. I start out with an empty Etcd.

I'm running into a problem where the ACME key specified in `storage = ...` is not persisted in Etcd. It seems Traefik gets certs every time it starts. I have:

```
storage = "traefik/acme/account"
```

but this key does not ever exist:

```
$ etcdctl get --prefix / --keys-only | grep acme | grep -v '^$'
/traefik/acme/
/traefik/acme/acmelogging
/traefik/acme/caserver
/traefik/acme/delaydontcheckdns
/traefik/acme/dnsprovider
/traefik/acme/domains/0/main
/traefik/acme/email
/traefik/acme/entrypoint
/traefik/acme/httpchallenge/
/traefik/acme/httpchallenge/entrypoint
/traefik/acme/keytype
/traefik/acme/ondemand
/traefik/acme/onhostrule
/traefik/acme/overridecertificates
/traefik/acme/storage
```

I use `storeconfig` to update the config in Etcd. This seems to work fine. (Though the storage key isn't created at that point, nor did I expect it to be.)

There's nothing interesting in the logs except things like `Datastore sync error: object lock value: expected 05254333-722a-4557-a320-0a12bda7645c, got 686712f1-fe57-4bb0-9438-0f06f3a54db9, retrying in 743.158272ms`.

I start Traefik without a config file, and specify the bootstrapping params (`--etcd.endpoint=...` and so on) on the command line. I don't use a config file once I've bootstrapped Etcd. I only use `storeconfig` to update it.

When Traefik starts up, it requests certs from Let's Encrypt. However, the key for the ACME state is never saved. The next time Traefik starts up, it has no state, and so requests everything from LE again.

### What did you expect to see?

I expected Traefik to persist the ACME account data.

### What did you see instead?

No ACME account data persisted to Etcd.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
$ /traefik version
Version:      v1.7.0-rc3
Codename:     maroilles
Go version:   go1.10.3
Built:        2018-08-01_01:37:51PM
OS/Arch:      linux/amd64
```

#### etcd (v3 only enabled, v2 disabled):

```
$ etcdctl version
etcdctl version: 3.3.9
API version: 3.3
```

#### Config file (used with `traefik storeconfig`)

<details>
 <summary>Config file</summary>

```toml
logLevel = "DEBUG"

defaultEntryPoints = ["http", "https"]

[etcd]
endpoint = "etcd-0.etcd-headless:2379"
watch = true
prefix = "/traefik"
useAPIV3 = true

[entryPoints]
  [entryPoints.http]
  address = ":8080"

  [entryPoints.https]
  address = ":8443"

    [entryPoints.https.tls]

  [entryPoints.admin]
  address = ":8000"

  [entryPoints.api]
  address = ":8001"

[acme]
email = *OMITTED*
entryPoint = "https"
acmeLogging = true
storage = "traefik/acme/account"
overrideCertificates = false

  [acme.httpChallenge]
  entryPoint = "http"

  [[acme.domains]]
  *OMITTED*

[file]

[frontends]
  [frontends.default]
  backend = "glb"
  passHostHeader = true

[backends]
  [backends.glb]
    [backends.glb.servers.glb]
    url = *OMITTED*

[ping]
entryPoint = "api"

[api]
entryPoint = "api"

[traefikLog]
format = "json"

[accessLog]
format = "json"
```
</details>

#### Traefik command line

```
traefik \
--etcd.endpoint=etcd-0.etcd-headless:2379 \
--etcd.watch=true \
--etcd.prefix=/traefik \
--etcd.useAPIV3=true
```
</details>

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

<details>
 <summary>Debug log</summary>

```js
{"level":"info","msg":"Traefik version v1.7.0-rc3 built on 2018-08-01_01:37:51PM","time":"2018-08-09T19:49:00Z"}
{"level":"info","msg":"\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/basics/#collected-data\n","time":"2018-08-09T19:49:00Z"}
{"level":"debug","msg":"Global configuration loaded ","time":"2018-08-09T19:49:00Z"}
{"level":"info","msg":"Preparing server admin \u0026{Address::8000 TLS:\u003cnil\u003e Redirect:\u003cnil\u003e Auth:\u003cnil\u003e WhitelistSourceRange:[] WhiteList:\u003cnil\u003e Compress:false ProxyProtocol:\u003cnil\u003e ForwardedHeaders:0xc4207974c0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s","time":"2018-08-09T19:49:01Z"}
{"level":"info","msg":"Preparing server https \u0026{Address::8443 TLS:0xc42074a120 Redirect:\u003cnil\u003e Auth:\u003cnil\u003e WhitelistSourceRange:[] WhiteList:\u003cnil\u003e Compress:false ProxyProtocol:\u003cnil\u003e ForwardedHeaders:0xc4207974e0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s","time":"2018-08-09T19:49:01Z"}
{"level":"info","msg":"Starting server on :8000","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Datastore reload","time":"2018-08-09T19:49:01Z"}
{"level":"info","msg":"Preparing server http \u0026{Address::8080 TLS:\u003cnil\u003e Redirect:\u003cnil\u003e Auth:\u003cnil\u003e WhitelistSourceRange:[] WhiteList:\u003cnil\u003e Compress:false ProxyProtocol:\u003cnil\u003e ForwardedHeaders:0xc420797440} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s","time":"2018-08-09T19:49:01Z"}
{"level":"info","msg":"Starting server on :8443","time":"2018-08-09T19:49:01Z"}
{"level":"info","msg":"Starting server on :8080","time":"2018-08-09T19:49:01Z"}
{"level":"info","msg":"Preparing server api \u0026{Address::8001 TLS:\u003cnil\u003e Redirect:\u003cnil\u003e Auth:\u003cnil\u003e WhitelistSourceRange:[] WhiteList:\u003cnil\u003e Compress:false ProxyProtocol:\u003cnil\u003e ForwardedHeaders:0xc420797460} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s","time":"2018-08-09T19:49:01Z"}
{"level":"info","msg":"Starting provider configuration.ProviderAggregator {}","time":"2018-08-09T19:49:01Z"}
{"level":"info","msg":"Starting provider *etcd.Provider {\"Watch\":true,\"Filename\":\"\",\"Constraints\":[],\"Trace\":false,\"TemplateVersion\":0,\"DebugLogGeneratedTemplate\":false,\"Endpoint\":\"etcd-0.etcd-headless:2379\",\"Prefix\":\"/traefik\",\"TLS\":null,\"Username\":\"\",\"Password\":\"\",\"UseAPIV3\":true}","time":"2018-08-09T19:49:01Z"}
{"level":"info","msg":"Starting server on :8001","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Node 7c780eb5-c33e-4cec-9927-712ffb1bc373 running for election","time":"2018-08-09T19:49:01Z"}
{"level":"info","msg":"Node 7c780eb5-c33e-4cec-9927-712ffb1bc373 elected worker ♝","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/alias Key not found in store, setting default /traefik","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/alias Key not found in store, setting default /traefik","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/circuitbreaker/expression Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/loadbalancer/method Key not found in store, setting default wrr","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/loadbalancer/sticky Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/circuitbreaker/expression Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/loadbalancer/method Key not found in store, setting default wrr","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/loadbalancer/stickiness Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/loadbalancer/sticky Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/maxconn/amount Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/loadbalancer/stickiness Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/maxconn/amount Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/maxconn/extractorfunc Key not found in store, setting default request.host","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/healthcheck/path Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/maxconn/extractorfunc Key not found in store, setting default request.host","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/backends/glb/buffering/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/healthcheck/path Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/backends/glb/buffering/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/entrypoints Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/entrypoints Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/entrypoints/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/entrypoints/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/basicauth Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/basicauth Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Building ACME client...","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/basicauth/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/basicauth/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/auth/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/auth/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/whitelist/sourcerange Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/whitelist/sourcerange Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/whitelist/sourcerange/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/whitelist/sourcerange/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/redirect/permanent Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/redirect/permanent Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/redirect/entrypoint Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/redirect/entrypoint Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/redirect/regex Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/redirect/regex Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/errors/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/errors/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/ratelimit/extractorfunc Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/ratelimit/extractorfunc Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/customrequestheaders/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/customrequestheaders/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/customresponseheaders/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/customresponseheaders/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/sslproxyheaders/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/sslproxyheaders/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/allowedhosts Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/allowedhosts Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/allowedhosts/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/allowedhosts/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/hostsproxyheaders Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/hostsproxyheaders Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/hostsproxyheaders/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/sslforcehost Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/hostsproxyheaders/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/sslredirect Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/sslforcehost Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/sslredirect Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/ssltemporaryredirect Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/ssltemporaryredirect Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/sslhost Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/stsseconds Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/sslhost Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/stsincludesubdomains Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/stsseconds Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/stspreload Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/stsincludesubdomains Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/stspreload Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/forcestsheader Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/framedeny Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/forcestsheader Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/customframeoptionsvalue Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/framedeny Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/contenttypenosniff Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/customframeoptionsvalue Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/browserxssfilter Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/contenttypenosniff Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/custombrowserxssvalue Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/browserxssfilter Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/contentsecuritypolicy Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/publickey Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/custombrowserxssvalue Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/contentsecuritypolicy Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/referrerpolicy Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/isdevelopment Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/publickey Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/routes/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/referrerpolicy Key not found in store, setting default ","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/tls/\": Key not found in store","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/isdevelopment Key not found in store, setting default false","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Configuration received from provider etcdv3: {\"backends\":{\"glb\":{\"servers\":{\"glb\":{\"url\":\"http://lb-enclosuresites.prod.gcp.t11e.com:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"default\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"glb\",\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot get key /traefik/alias Key not found in store, setting default /traefik","time":"2018-08-09T19:49:01Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/routes/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/tls/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Configuration received from provider etcdv3: {\"backends\":{\"glb\":{\"servers\":{\"glb\":{\"url\":\"http://lb-enclosuresites.prod.gcp.t11e.com:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"default\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"glb\",\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/circuitbreaker/expression Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/loadbalancer/method Key not found in store, setting default wrr","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/loadbalancer/sticky Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/loadbalancer/stickiness Key not found in store, setting default false","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/maxconn/amount Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/maxconn/extractorfunc Key not found in store, setting default request.host","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/backends/glb/healthcheck/path Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/backends/glb/buffering/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/entrypoints Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/entrypoints/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/basicauth Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/basicauth/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/auth/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/whitelist/sourcerange Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/whitelist/sourcerange/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/redirect/permanent Key not found in store, setting default false","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/redirect/entrypoint Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/redirect/regex Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/errors/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/ratelimit/extractorfunc Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/customrequestheaders/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/customresponseheaders/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/sslproxyheaders/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/allowedhosts Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/allowedhosts/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/hostsproxyheaders Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/headers/hostsproxyheaders/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Using HTTP Challenge provider.","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/sslforcehost Key not found in store, setting default false","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/sslredirect Key not found in store, setting default false","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/ssltemporaryredirect Key not found in store, setting default false","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/sslhost Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/stsseconds Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/stsincludesubdomains Key not found in store, setting default false","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/stspreload Key not found in store, setting default false","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/forcestsheader Key not found in store, setting default false","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/framedeny Key not found in store, setting default false","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/customframeoptionsvalue Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/contenttypenosniff Key not found in store, setting default false","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/browserxssfilter Key not found in store, setting default false","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/custombrowserxssvalue Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/contentsecuritypolicy Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/publickey Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/referrerpolicy Key not found in store, setting default ","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot get key /traefik/frontends/default/headers/isdevelopment Key not found in store, setting default false","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/frontends/default/routes/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Cannot list keys under \"/traefik/tls/\": Key not found in store","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Configuration received from provider etcdv3: {\"backends\":{\"glb\":{\"servers\":{\"glb\":{\"url\":\"http://lb-enclosuresites.prod.gcp.t11e.com:80\",\"weight\":0}},\"loadBalancer\":{\"method\":\"wrr\"}}},\"frontends\":{\"default\":{\"entryPoints\":[\"http\",\"https\"],\"backend\":\"glb\",\"passHostHeader\":true,\"priority\":0,\"basicAuth\":null}}}","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Wiring frontend default to entryPoint http","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Creating backend glb","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Creating load-balancer wrr","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Creating server glb at http://lb-enclosuresites.prod.gcp.t11e.com:80 with weight 0","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Wiring frontend default to entryPoint https","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Creating backend glb","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Creating load-balancer wrr","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Creating server glb at http://lb-enclosuresites.prod.gcp.t11e.com:80 with weight 0","time":"2018-08-09T19:49:02Z"}
{"level":"info","msg":"Server configuration reloaded on :8001","time":"2018-08-09T19:49:02Z"}
{"level":"info","msg":"Server configuration reloaded on :8000","time":"2018-08-09T19:49:02Z"}
{"level":"info","msg":"Server configuration reloaded on :8443","time":"2018-08-09T19:49:02Z"}
{"level":"info","msg":"Server configuration reloaded on :8080","time":"2018-08-09T19:49:02Z"}
{"level":"debug","msg":"Wiring frontend default to entryPoint http","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"Creating backend glb","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"Creating load-balancer wrr","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"Creating server glb at http://lb-enclosuresites.prod.gcp.t11e.com:80 with weight 0","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"Wiring frontend default to entryPoint https","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"Creating backend glb","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"Creating load-balancer wrr","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"Creating server glb at http://lb-enclosuresites.prod.gcp.t11e.com:80 with weight 0","time":"2018-08-09T19:49:04Z"}
{"level":"info","msg":"Server configuration reloaded on :8080","time":"2018-08-09T19:49:04Z"}
{"level":"info","msg":"Server configuration reloaded on :8001","time":"2018-08-09T19:49:04Z"}
{"level":"info","msg":"Server configuration reloaded on :8000","time":"2018-08-09T19:49:04Z"}
{"level":"info","msg":"Server configuration reloaded on :8443","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for stltoday.enclosuresites.com...","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"Looking for provided certificate to validate stltoday.enclosuresites.com...","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"No provided certificate found for domains stltoday.enclosuresites.com, get ACME certificate.","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"ACME got domain cert stltoday.enclosuresites.com","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:04Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 483170, duration: 154.375599ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:stltoday.enclosuresites.com","time":"2018-08-09T19:49:05Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for stltoday.enclosuresites.com...","time":"2018-08-09T19:49:06Z"}
{"level":"debug","msg":"Looking for provided certificate to validate stltoday.enclosuresites.com...","time":"2018-08-09T19:49:06Z"}
{"level":"debug","msg":"No provided certificate found for domains stltoday.enclosuresites.com, get ACME certificate.","time":"2018-08-09T19:49:06Z"}
{"level":"debug","msg":"ACME got domain cert stltoday.enclosuresites.com","time":"2018-08-09T19:49:06Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:06Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 79440, duration: 33.79309ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:stltoday.enclosuresites.com","time":"2018-08-09T19:49:06Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for stltoday.enclosuresites.com...","time":"2018-08-09T19:49:06Z"}
{"level":"debug","msg":"Looking for provided certificate to validate stltoday.enclosuresites.com...","time":"2018-08-09T19:49:06Z"}
{"level":"debug","msg":"No provided certificate found for domains stltoday.enclosuresites.com, get ACME certificate.","time":"2018-08-09T19:49:06Z"}
{"level":"debug","msg":"ACME got domain cert stltoday.enclosuresites.com","time":"2018-08-09T19:49:06Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:07Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 302, Length: 0, duration: 127.548444ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:stltoday.enclosuresites.com","time":"2018-08-09T19:49:07Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:14Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 302, Length: 0, duration: 134.830799ms","time":"2018-08-09T19:49:14Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:18Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 142, duration: 5.765189ms","time":"2018-08-09T19:49:18Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:19Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 4298, duration: 8.991574ms","time":"2018-08-09T19:49:19Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for stltoday.enclosuresites.com...","time":"2018-08-09T19:49:21Z"}
{"level":"debug","msg":"Looking for provided certificate to validate stltoday.enclosuresites.com...","time":"2018-08-09T19:49:21Z"}
{"level":"debug","msg":"No provided certificate found for domains stltoday.enclosuresites.com, get ACME certificate.","time":"2018-08-09T19:49:21Z"}
{"level":"debug","msg":"ACME got domain cert stltoday.enclosuresites.com","time":"2018-08-09T19:49:21Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:21Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 79440, duration: 33.755983ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:stltoday.enclosuresites.com","time":"2018-08-09T19:49:21Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for stltoday.enclosuresites.com...","time":"2018-08-09T19:49:21Z"}
{"level":"debug","msg":"Looking for provided certificate to validate stltoday.enclosuresites.com...","time":"2018-08-09T19:49:21Z"}
{"level":"debug","msg":"No provided certificate found for domains stltoday.enclosuresites.com, get ACME certificate.","time":"2018-08-09T19:49:21Z"}
{"level":"debug","msg":"ACME got domain cert stltoday.enclosuresites.com","time":"2018-08-09T19:49:21Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:21Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 302, Length: 0, duration: 120.641739ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:stltoday.enclosuresites.com","time":"2018-08-09T19:49:22Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:26Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 79440, duration: 33.204123ms","time":"2018-08-09T19:49:26Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for stltoday.enclosuresites.com...","time":"2018-08-09T19:49:27Z"}
{"level":"debug","msg":"Looking for provided certificate to validate stltoday.enclosuresites.com...","time":"2018-08-09T19:49:27Z"}
{"level":"debug","msg":"No provided certificate found for domains stltoday.enclosuresites.com, get ACME certificate.","time":"2018-08-09T19:49:27Z"}
{"level":"debug","msg":"ACME got domain cert stltoday.enclosuresites.com","time":"2018-08-09T19:49:27Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:27Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 4298, duration: 7.134438ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:stltoday.enclosuresites.com","time":"2018-08-09T19:49:27Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for stltoday.enclosuresites.com...","time":"2018-08-09T19:49:27Z"}
{"level":"debug","msg":"Looking for provided certificate to validate stltoday.enclosuresites.com...","time":"2018-08-09T19:49:27Z"}
{"level":"debug","msg":"No provided certificate found for domains stltoday.enclosuresites.com, get ACME certificate.","time":"2018-08-09T19:49:27Z"}
{"level":"debug","msg":"ACME got domain cert stltoday.enclosuresites.com","time":"2018-08-09T19:49:27Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:27Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 142, duration: 4.987745ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:stltoday.enclosuresites.com","time":"2018-08-09T19:49:27Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:33Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 142, duration: 4.439033ms","time":"2018-08-09T19:49:33Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for stltoday.enclosuresites.com...","time":"2018-08-09T19:49:33Z"}
{"level":"debug","msg":"Looking for provided certificate to validate stltoday.enclosuresites.com...","time":"2018-08-09T19:49:33Z"}
{"level":"debug","msg":"No provided certificate found for domains stltoday.enclosuresites.com, get ACME certificate.","time":"2018-08-09T19:49:33Z"}
{"level":"debug","msg":"ACME got domain cert stltoday.enclosuresites.com","time":"2018-08-09T19:49:33Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:34Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 4297, duration: 12.823533ms","time":"2018-08-09T19:49:34Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for stltoday.enclosuresites.com...","time":"2018-08-09T19:49:36Z"}
{"level":"debug","msg":"Looking for provided certificate to validate stltoday.enclosuresites.com...","time":"2018-08-09T19:49:36Z"}
{"level":"debug","msg":"No provided certificate found for domains stltoday.enclosuresites.com, get ACME certificate.","time":"2018-08-09T19:49:36Z"}
{"level":"debug","msg":"ACME got domain cert stltoday.enclosuresites.com","time":"2018-08-09T19:49:36Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:37Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 302, Length: 0, duration: 196.236599ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:stltoday.enclosuresites.com","time":"2018-08-09T19:49:37Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:39Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:39Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 483170, duration: 197.896838ms","time":"2018-08-09T19:49:40Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 371194, duration: 1.45103139s","time":"2018-08-09T19:49:40Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:41Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 79440, duration: 36.360839ms","time":"2018-08-09T19:49:41Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for stltoday.enclosuresites.com...","time":"2018-08-09T19:49:44Z"}
{"level":"debug","msg":"Looking for provided certificate to validate stltoday.enclosuresites.com...","time":"2018-08-09T19:49:44Z"}
{"level":"debug","msg":"No provided certificate found for domains stltoday.enclosuresites.com, get ACME certificate.","time":"2018-08-09T19:49:44Z"}
{"level":"debug","msg":"ACME got domain cert stltoday.enclosuresites.com","time":"2018-08-09T19:49:44Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for stltoday.enclosuresites.com...","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"Looking for provided certificate to validate stltoday.enclosuresites.com...","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"No provided certificate found for domains stltoday.enclosuresites.com, get ACME certificate.","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"ACME got domain cert stltoday.enclosuresites.com","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"http: TLS handshake error from 72.202.189.30:58906: EOF","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"Looking for an existing ACME challenge for stltoday.enclosuresites.com...","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"Looking for provided certificate to validate stltoday.enclosuresites.com...","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"No provided certificate found for domains stltoday.enclosuresites.com, get ACME certificate.","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"ACME got domain cert stltoday.enclosuresites.com","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 79440, duration: 121.630496ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:stltoday.enclosuresites.com","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"vulcand/oxy/forward/http: Round trip: http://lb-enclosuresites.prod.gcp.t11e.com:80, code: 200, Length: 483170, duration: 199.388079ms tls:version: 303, tls:resume:false, tls:csuite:c02f, tls:server:stltoday.enclosuresites.com","time":"2018-08-09T19:49:48Z"}
{"level":"debug","msg":"Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel.","time":"2018-08-09T19:49:48Z"}
```
</details>

### PR DESCRIPTION
**Pull request by geraldcroes**
### What does this PR do?

The StoreConfig command will now always initialize the account (which key path is defined by acme.storage) if it is not yet initialized.

### Motivation

Related #3787 #3776 
Fixes #3754

### CODE REVIEW

File: cmd/storeconfig/storeconfig.go [hunk 1]
```diff
@@ -114,6 +119,14 @@ func Run(kv *staert.KvSource, traefikConfiguration *cmd.TraefikConfiguration) fu
 	}
 }
 
+func keyExists(source *staert.KvSource, key string) (bool, error) {
+	list, err := source.List(key, nil)
+	if err != nil {
+		return false, err
+	}
+	return len(list) > 0, nil
```
Comment (mmatur) [inline cmd/storeconfig/storeconfig.go]: Could you please add a new line before?

**Comment by ace03uec** [comment]
```
---> Making bundle: validate-gofmt (in .)
These files are not properly gofmt'd:
 - cmd/storeconfig/storeconfig.go

Please reformat the above files using "gofmt -s -w" and commit the result.

make: *** [validate] Error 1
make validate failed, attempt 3/3
```
Error from semaphoreci.
