### PR TITLE
Fix rewrite target with full URL and no regex in ingress path

### LINKED ISSUE #12982: rewrite-target full URL still appends path suffix on Prefix ingress without regex (regression case after #12905)
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Running the ingress-nginx compatibility E2E tests on the `v3.7` branch (commit `2b9ffc4`, image `traefik/traefik:experimental-v3.7`). Two ingresses with the same annotation:

```
nginx.ingress.kubernetes.io/rewrite-target: https://bar.example.org/$1
```

1. **Case A** — `pathType: Prefix`, `path: /original` (no regex in path)
2. **Case B** — `pathType: ImplementationSpecific`, `path: /original/(.*)` (regex capture)

Sending requests to paths below the prefix (e.g. `/original/other`, `/original/a/b/c`).

### What did you see instead?

**Case A** (Prefix, no regex) — Traefik still appends the request path suffix with a leading extra slash, while NGINX strips it to `/` (no capture group so `$1` is empty):

| Request | NGINX `Location` | Traefik `Location` |
|---|---|---|
| `/original` | `https://bar.example.org/` | `https://bar.example.org/` ✓ |
| `/original/other` | `https://bar.example.org/` | `https://bar.example.org//other` ✗ |
| `/original/a/b/c` | `https://bar.example.org/` | `https://bar.example.org//a/b/c` ✗ |

**Case B** (regex path `/original/(.*)`) — request `/original` returns **404** on Traefik (expected `302` matching NGINX).

Same pattern as #12931 (closed as duplicate of #12911, fixed by #12905). #12905 solves the case where the request path **equals** the ingress path, but not the case where the request has additional path segments under a `Prefix` match without a regex capture.

### What version of Traefik are you using?

```console
$ docker run traefik/traefik:experimental-v3.7 version
Version:      2b9ffc426122b89bf38139cebfd7dfb8d5007634
Codename:     cheddar
Go version:   go1.25.9
Built:        2026-04-14_07:54:14AM
OS/Arch:      linux/arm64
```

### What is your environment & configuration?

Ingress (Case A):

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: full-path-test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: "https://bar.example.org/\$1"
spec:
  ingressClassName: traefik
  rules:
    - host: full-path-test.traefik.local
      http:
        paths:
          - path: /original
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
```

Traefik Helm values:

```yaml
providers:
  kubernetesIngressNginx: true
  kubernetesCRD: true
  kubernetesGateway: true
```

### If applicable, please paste the log output in DEBUG level

Reproduction available in https://github.com/traefik/ingress-nginx-migration — suite \`TestRewriteTargetSuite\`, tests \`TestFullPathRewriteNoRegexPath\` and \`TestFullPathRewriteWithRegexPath\`. Can attach full DEBUG logs on request.

### PR DESCRIPTION
**Pull request by LBF38**
### What does this PR do?

This PR fixes the `rewrite-target` annotation when there is a full URL, and the ingress path doesn't contain a regex (`pathType: Prefix`).

### Motivation

Partially fix https://github.com/traefik/traefik/issues/12982
Closes https://github.com/traefik/traefik/issues/12931

### More

~- [x] Added/updated tests~ (see the e2e tests in the ingress-nginx-migration tool)
- [ ] Added/updated documentation

### Additional Notes

It doesn't fix the other issue mentioned with the redirection status code. This requires more refactoring and discussions. (case B)

### CODE REVIEW

File: pkg/provider/kubernetes/ingress-nginx/kubernetes.go [hunk 1]
```diff
@@ -1698,24 +1698,44 @@ func (p *Provider) applyCustomHeaders(namespace, routerName string, ingressConfi
...
 		// Location modifier regex on ingress-nginx is case-insensitive.
 		regex = "(?i)" + regex
 	}
 
+	// When rewrite-target is a full URL and there's no capture group,
+	// append .* to match the entire path and avoid leaking unmatched suffix.
+	// See https://github.com/traefik/traefik/issues/12931
+	if isFullURLRewrite && !hasCaptureGroup {
+		pathType := ptr.Deref(rulePath.PathType, netv1.PathTypePrefix)
+		if pathType == netv1.PathTypePrefix {
```
Comment (gndz07) [inline pkg/provider/kubernetes/ingress-nginx/kubernetes.go]: Is pathType check absolutely necessary? What about ImplementationSpecific case?

File: pkg/provider/kubernetes/ingress-nginx/kubernetes.go [hunk 2]
```diff
@@ -1698,24 +1698,44 @@ func (p *Provider) applyCustomHeaders(namespace, routerName string, ingressConfi
...
 	// Skip rewrite if the path is equal to the target.
-	if rewrite == rulePath {
+	if rewrite == rulePath.Path {
 		return
 	}
 
 	rewriteTargetMiddlewareName := routerName + "-rewrite-target"
-	regex := rulePath
+	regex := rulePath.Path
+	isFullURLRewrite := isFullURL(rewrite)
```
Comment (gndz07) [inline pkg/provider/kubernetes/ingress-nginx/kubernetes.go]: Can use url.Parse() and check for the scheme.

**Review by gndz07 — APPROVED** [review]
LGTM

**Review by kevinpollet — APPROVED** [review]
