### PR TITLE
Don't panic if ResponseWriter does not implement CloseNotify

### LINKED ISSUE #2628: 500 Internal Server error with "missing method CloseNotify"
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Upgraded to 1.5.0-rc3 and then made a request.

### What did you expect to see?

The response from the backend or 502/503 when backend is unavailable (as in 1.4.5).

### What did you see instead?

500 Internal Server Error (and seee logs below)

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.5.0-rc3
Codename:     cancoillotte
Go version:   go1.9.2
Built:        2017-12-20_02:24:44PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

<details>
<summary>config json</summary>

```json
{
 "LifeCycle": null,
 "GraceTimeOut": 0,
 "Debug": true,
 "CheckNewVersion": true,
 "SendAnonymousUsage": false,
 "AccessLogsFile": "",
 "AccessLog": null,
 "TraefikLogsFile": "",
 "TraefikLog": null,
 "LogLevel": "DEBUG",
 "EntryPoints": {
  "http": {
   "Network": "",
   "Address": ":80",
   "TLS": null,
   "Redirect": {
    "entryPoint": "https"
   },
   "Auth": null,
   "WhitelistSourceRange": null,
   "Compress": false,
   "ProxyProtocol": null,
   "ForwardedHeaders": null
  },
  "https": {
   "Network": "",
   "Address": ":443",
   "TLS": {
    "MinVersion": "VersionTLS12",
    "CipherSuites": [
     "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
     "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
     "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
     "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
     "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
     "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
     "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
     "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
     "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
     "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
     "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
     "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
     "TLS_RSA_WITH_AES_128_GCM_SHA256",
     "TLS_RSA_WITH_AES_256_GCM_SHA384",
     "TLS_RSA_WITH_AES_128_CBC_SHA",
     "TLS_RSA_WITH_AES_256_CBC_SHA"
    ],
    "Certificates": null,
    "ClientCAFiles": null,
    "ClientCA": {
     "Files": null,
     "Optional": false
    }
   },
   "Redirect": null,
   "Auth": null,
   "WhitelistSourceRange": null,
   "Compress": true,
   "ProxyProtocol": null,
   "ForwardedHeaders": null
  }
 },
 "Cluster": null,
 "Constraints": [],
 "ACME": {
  "Email": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "Domains": null,
  "Storage": "/etc/traefik/acme/acme.json",
  "StorageFile": "",
  "OnDemand": false,
  "OnHostRule": true,
  "CAServer": "",
  "EntryPoint": "https",
  "DNSProvider": "",
  "DelayDontCheckDNS": 0,
  "ACMELogging": true,
  "TLSConfig": null
 },
 "DefaultEntryPoints": [
  "http",
  "https"
 ],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "IdleTimeout": 0,
 "InsecureSkipVerify": false,
 "RootCAs": null,
 "Retry": {
  "Attempts": 0
 },
 "HealthCheck": {
  "Interval": 30000000000
 },
 "RespondingTimeouts": null,
 "ForwardingTimeouts": null,
 "Web": {
  "Address": ":8080",
  "CertFile": "",
  "KeyFile": "",
  "ReadOnly": false,
  "Statistics": null,
  "Metrics": null,
  "Path": "",
  "Auth": null,
  "Debug": false
 },
 "Docker": null,
 "File": {
  "Watch": true,
  "Filename": "",
  "Constraints": null,
  "Trace": false,
  "DebugLogGeneratedTemplate": false,
  "Directory": "/config/"
 },
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": null,
 "DynamoDB": null,
 "ServiceFabric": null,
 "Rest": null,
 "API": null,
 "Metrics": null,
 "Ping": null,
 "ConfigFile": "//traefik.toml"
}
```

</details>

<details>
<summary>traefil.toml</summary>

```toml
debug = true

#InsecureSkipVerify = true

defaultEntryPoints = ["http", "https"]

logLevel = "DEBUG"

[retry]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entryPoints.https.tls]
    minVersion = "VersionTLS12"
    cipherSuites = [
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
      "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
      "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305",
      "TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA",
      "TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA",
      "TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA",
      "TLS_RSA_WITH_AES_128_GCM_SHA256",
      "TLS_RSA_WITH_AES_256_GCM_SHA384",
      "TLS_RSA_WITH_AES_128_CBC_SHA",
      "TLS_RSA_WITH_AES_256_CBC_SHA",
    ]

[acme]
storage = "/etc/traefik/acme/acme.json"
#caServer = "https://acme-staging.api.letsencrypt.org/directory"
email = "some-mail@example.com"
#onDemand = true
onHostRule = true
entryPoint = "https"
acmeLogging = true


[web]

[file]
directory = "/config/"
watch = true
```

/config/services.toml (only file in there)
```
[frontends]
  [frontends.concourse]
  backend = "concourse"
    [frontends.concourse.routes.test_1]
    rule = "Host:concourse.my.example.com"

[backends]
  [backends.concourse]
    [backends.concourse.servers.server1]
    url = "http://concourse-web:8080"
```
</details>

### If applicable, please paste the log output in debug mode (`--debug` switch)

<details>
<summary>logs</summary>

```shell
time="2017-12-28T15:26:25Z" level=info msg="Using TOML configuration file //traefik.toml"
time="2017-12-28T15:26:25Z" level=warning msg="web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics"
time="2017-12-28T15:26:25Z" level=info msg="Traefik version v1.5.0-rc3 built on 2017-12-20_02:24:44PM"
time="2017-12-28T15:26:25Z" level=info msg="
Stats collection is disabled.
Help us improve Traefik by turning this feature on :)
More details on: https://docs.traefik.io/basic/#collected-data
"
time="2017-12-28T15:26:25Z" level=debug msg="Global configuration loaded {"LifeCycle":{"RequestAcceptGraceTimeout":0,"GraceTimeOut":0},"GraceTimeOut":0,"Debug":true,"CheckNewVersion":true,"SendAnonymousUsage":false,"AccessLogsFile":"","AccessLog":null,"TraefikLogsFile":"","TraefikLog":null,"LogLevel":"DEBUG","EntryPoints":{"http":{"Network":"","Address":":80","TLS":null,"Redirect":{"entryPoint":"https"},"Auth":null,"WhitelistSourceRange":null,"Compress":false,"ProxyProtocol":null,"ForwardedHeaders":{"Insecure":true,"TrustedIPs":null}},"https":{"Network":"","Address":":443","TLS":{"MinVersion":"VersionTLS12","CipherSuites":["TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305","TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305","TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256","TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384","TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305","TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305","TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA","TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA","TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA","TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA","TLS_RSA_WITH_AES_128_GCM_SHA256","TLS_RSA_WITH_AES_256_GCM_SHA384","TLS_RSA_WITH_AES_128_CBC_SHA","TLS_RSA_WITH_AES_256_CBC_SHA"],"Certificates":null,"ClientCAFiles":null,"ClientCA":{"Files":null,"Optional":false}},"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":true,"ProxyProtocol":null,"ForwardedHeaders":{"Insecure":true,"TrustedIPs":null}},"traefik":{"Network":"","Address":":8080","TLS":null,"Redirect":null,"Auth":null,"WhitelistSourceRange":null,"Compress":false,"ProxyProtocol":null,"ForwardedHeaders":{"Insecure":true,"TrustedIPs":null}}},"Cluster":null,"Constraints":[],"ACME":{"Email":"some-mail@example.com","Domains":null,"Storage":"/etc/traefik/acme/acme.json","StorageFile":"","OnDemand":false,"OnHostRule":true,"CAServer":"","EntryPoint":"https","DNSProvider":"","DelayDontCheckDNS":0,"ACMELogging":true,"TLSConfig":null},"DefaultEntryPoints":["http","https"],"ProvidersThrottleDuration":2000000000,"MaxIdleConnsPerHost":200,"IdleTimeout":0,"InsecureSkipVerify":false,"RootCAs":null,"Retry":{"Attempts":0},"HealthCheck":{"Interval":30000000000},"RespondingTimeouts":null,"ForwardingTimeouts":null,"Web":{"Address":":8080","CertFile":"","KeyFile":"","ReadOnly":false,"Statistics":null,"Metrics":null,"Path":"/","Auth":null,"Debug":false},"Docker":null,"File":{"Watch":true,"Filename":"//traefik.toml","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Directory":"/config/"},"Marathon":null,"Consul":null,"ConsulCatalog":null,"Etcd":null,"Zookeeper":null,"Boltdb":null,"Kubernetes":null,"Mesos":null,"Eureka":null,"ECS":null,"Rancher":null,"DynamoDB":null,"ServiceFabric":null,"Rest":null,"API":{"EntryPoint":"traefik","Dashboard":true,"Debug":true,"CurrentConfigurations":null,"Statistics":null,"Stats":null,"StatsRecorder":null},"Metrics":null,"Ping":{"EntryPoint":"traefik"}}"
time="2017-12-28T15:26:25Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:0xc4204a92f0 Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4200bcb80} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2017-12-28T15:26:25Z" level=info msg="Preparing server https &{Network: Address::443 TLS:0xc4206bd180 Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:true ProxyProtocol:<nil> ForwardedHeaders:0xc4200bcba0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2017-12-28T15:26:25Z" level=info msg="Starting server on :80"
time="2017-12-28T15:26:26Z" level=info msg="Loading ACME Account..."
time="2017-12-28T15:26:26Z" level=info msg="Loaded ACME config from store /etc/traefik/acme/acme.json"
time="2017-12-28T15:26:26Z" level=debug msg="Building ACME client..."
time="2017-12-28T15:26:26Z" level=debug msg=AgreeToTOS...
time="2017-12-28T15:26:27Z" level=info msg="Preparing server traefik &{Network: Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4200bcbc0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
time="2017-12-28T15:26:27Z" level=info msg="Starting provider *file.Provider {"Watch":true,"Filename":"//traefik.toml","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Directory":"/config/"}"
time="2017-12-28T15:26:27Z" level=info msg="Retrieving ACME certificates..."
time="2017-12-28T15:26:27Z" level=info msg="Retrieved ACME certificates"
time="2017-12-28T15:26:27Z" level=info msg="Testing certificate renew..."
time="2017-12-28T15:26:27Z" level=info msg="Starting server on :443"
time="2017-12-28T15:26:27Z" level=info msg="Starting server on :8080"
time="2017-12-28T15:26:27Z" level=debug msg="Validation of load balancer method for backend concourse failed: invalid load-balancing method ''. Using default method wrr."
time="2017-12-28T15:26:27Z" level=debug msg="Configuration received from provider file: {"backends":{"concourse":{"servers":{"server1":{"url":"http://concourse-web:8080","weight":0}},"loadBalancer":{"method":"wrr"}}},"frontends":{"concourse":{"entryPoints":["http","https"],"backend":"concourse","routes":{"test_1":{"rule":"Host:concourse.my.example.com"}},"priority":0,"basicAuth":null,"headers":{}}}}"
time="2017-12-28T15:26:27Z" level=debug msg="Creating frontend concourse"
time="2017-12-28T15:26:27Z" level=debug msg="Wiring frontend concourse to entryPoint http"
time="2017-12-28T15:26:27Z" level=debug msg="Creating route test_1 Host:concourse.my.example.com"
time="2017-12-28T15:26:27Z" level=debug msg="Creating entryPoint redirect http -> https : ^(?:https?:\/\/)?([\w\._-]+)(?::\d+)?(.*)$ -> https://$1:443$2"
time="2017-12-28T15:26:27Z" level=debug msg="Creating backend concourse"
time="2017-12-28T15:26:27Z" level=debug msg="Creating load-balancer wrr"
time="2017-12-28T15:26:27Z" level=debug msg="Creating server server1 at http://concourse-web:8080 with weight 0"
time="2017-12-28T15:26:27Z" level=debug msg="Creating retries max attempts 1"
time="2017-12-28T15:26:27Z" level=debug msg="Wiring frontend concourse to entryPoint https"
time="2017-12-28T15:26:27Z" level=debug msg="Creating route test_1 Host:concourse.my.example.com"
time="2017-12-28T15:26:27Z" level=debug msg="Creating backend concourse"
time="2017-12-28T15:26:27Z" level=debug msg="Creating load-balancer wrr"
time="2017-12-28T15:26:27Z" level=debug msg="Creating server server1 at http://concourse-web:8080 with weight 0"
time="2017-12-28T15:26:27Z" level=debug msg="Creating retries max attempts 1"
time="2017-12-28T15:26:27Z" level=info msg="Server configuration reloaded on :443"
time="2017-12-28T15:26:27Z" level=info msg="Server configuration reloaded on :8080"
time="2017-12-28T15:26:27Z" level=info msg="Server configuration reloaded on :80"
time="2017-12-28T15:26:27Z" level=debug msg="LoadCertificateForDomains [concourse.my.example.com]..."
time="2017-12-28T15:26:27Z" level=debug msg="Look for provided certificate to validate [concourse.my.example.com]..."
time="2017-12-28T15:26:27Z" level=debug msg="No provided certificate found for domains [concourse.my.example.com], get ACME certificate."
time="2017-12-28T15:26:31Z" level=debug msg="Look for provided certificate to validate [concourse.my.example.com]..."
time="2017-12-28T15:26:31Z" level=debug msg="No provided certificate found for domains [concourse.my.example.com], get ACME certificate."
time="2017-12-28T15:26:31Z" level=debug msg="Challenge GetCertificate concourse.my.example.com"
time="2017-12-28T15:26:31Z" level=debug msg="ACME got domain cert concourse.my.example.com"
time="2017-12-28T15:26:31Z" level=debug msg="vulcand/oxy/roundrobin/rr: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/teams/main/pipelines/","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.5"],"Cache-Control":["max-age=0"],"Cookie":["ATC-Authorization=\"Bearer sometoken\""],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"concourse.my.example.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"${my-ip}:53372","RequestURI":"/teams/main/pipelines/","TLS":null}"
time="2017-12-28T15:26:31Z" level=debug msg="vulcand/oxy/roundrobin/rr: Forwarding this request to URL" ForwardURL=http://concourse-web:8080 Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/teams/main/pipelines/","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.5"],"Cache-Control":["max-age=0"],"Cookie":["ATC-Authorization=\"Bearer sometoken\""],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"concourse.my.example.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"${my-ip}:53372","RequestURI":"/teams/main/pipelines/","TLS":null}"
time="2017-12-28T15:26:31Z" level=debug msg="vulcand/oxy/forward: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"concourse-web:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.5"],"Cache-Control":["max-age=0"],"Cookie":["ATC-Authorization=\"Bearer sometoken\""],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"concourse.my.example.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"${my-ip}:53372","RequestURI":"/teams/main/pipelines/","TLS":null}"
time="2017-12-28T15:26:31Z" level=debug msg="vulcand/oxy/forward/http: begin ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"concourse-web:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.5"],"Cache-Control":["max-age=0"],"Cookie":["ATC-Authorization=\"Bearer sometoken\""],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"concourse.my.example.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"${my-ip}:53372","RequestURI":"/teams/main/pipelines/","TLS":null}"
time="2017-12-28T15:26:31Z" level=debug msg="vulcand/oxy/forward/http: completed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"concourse-web:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.5"],"Cache-Control":["max-age=0"],"Cookie":["ATC-Authorization=\"Bearer sometoken\""],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"concourse.my.example.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"${my-ip}:53372","RequestURI":"/teams/main/pipelines/","TLS":null}"
time="2017-12-28T15:26:31Z" level=debug msg="vulcand/oxy/forward: competed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"http","Opaque":"","User":null,"Host":"concourse-web:8080","Path":"","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.5"],"Cache-Control":["max-age=0"],"Cookie":["ATC-Authorization=\"Bearer sometoken\""],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"concourse.my.example.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"${my-ip}:53372","RequestURI":"/teams/main/pipelines/","TLS":null}"
time="2017-12-28T15:26:31Z" level=debug msg="vulcand/oxy/roundrobin/rr: competed ServeHttp on request" Request="{"Method":"GET","URL":{"Scheme":"","Opaque":"","User":null,"Host":"","Path":"/teams/main/pipelines/","RawPath":"","ForceQuery":false,"RawQuery":"","Fragment":""},"Proto":"HTTP/2.0","ProtoMajor":2,"ProtoMinor":0,"Header":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en-US,en;q=0.5"],"Cache-Control":["max-age=0"],"Cookie":["ATC-Authorization=\"Bearer sometoken\""],"Dnt":["1"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0"]},"ContentLength":0,"TransferEncoding":null,"Host":"concourse.my.example.com","Form":null,"PostForm":null,"MultipartForm":null,"Trailer":null,"RemoteAddr":"${my-ip}:53372","RequestURI":"/teams/main/pipelines/","TLS":null}"
time="2017-12-28T15:26:31Z" level=error msg="Recovered from panic in http handler: interface conversion: *negroni.responseWriter is not http.CloseNotifier: missing method CloseNotify"

```

</details>

### PR DESCRIPTION
**Pull request by Juliens**
### What does this PR do?
Fix a panic in the retry middleware if the responseWriter does not implement CloseNotify. Happen with compress=true (Gzip does not implement CloseNotify yet)

### Motivation
Fixes #2628 

### More
I think this is better that the next handler choose what to do if we don't implement CloseNotify instead of Panic or implement a wrong version of CloseNotify.

### CODE REVIEW

File: middlewares/retry.go [hunk 1]
```diff
@@ -115,9 +114,28 @@ func (l RetryListeners) Retried(req *http.Request, attempt int) {
...
+
+type retryResponseRecorder interface {
+	http.ResponseWriter
+	http.Flusher
+	GetCode() int
+	GetBody() *bytes.Buffer
+	IsStreamingResponseStarted() bool
+}
+
 // retryResponseRecorder is an implementation of http.ResponseWriter that
```
Comment (nmengin) [inline middlewares/retry.go]: Might be changed into `retryResponseRecorderWithoutCloseNotify` or moved above?

**Comment by justb81** [comment]
i still see this in 1.5.0 final
```
24.1.2018 12:18:21time="2018-01-24T11:18:21Z" level=error msg="Recovered from panic in http handler: interface conversion: *negroni.responseWriter is not http.CloseNotifier: missing method CloseNotify"
```
if i disable http compression it is fine.
