### PR TITLE
Correct Entrypoint Redirect with Stripped or Added Path

### LINKED ISSUE #1957: Wrong behaviour of HTTP -> HTTPS redirect with PathPrefixStrip annotation
### Do you want to request a *feature* or report a *bug*?

bug

### What did you do?

I'm using traefik as a kubernetes ingress controller. HTTPS is enforced by default so all the HTTP requests respond with 302 -> HTTPS. All works fine except one case: when I annotate a service with `traefik.frontend.rule.type: PathPrefixStrip`, the path gets lost during the redirect.

```yml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test
  annotations:
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /path-prefix-strip-service/
        backend:
          serviceName: my-service
          servicePort: http
```

### What did you expect to see?

| url entered                                   | 302 to                                         |
|-----------------------------------------------|------------------------------------------------|
| http://example.com/                           | https://example.com/                           |
| http://example.com/path-prefix-strip-service/ | https://example.com/path-prefix-strip-service/ |
| http://example.com/any-other-path/            | https://example.com/any-other-path/            |

### What did you see instead?

| url entered                                   | 302 to                              |
|-----------------------------------------------|-------------------------------------|
| http://example.com/                           | https://example.com/                |
| http://example.com/path-prefix-strip-service/ | https://example.com/ ⚠️ |
| http://example.com/any-other-path/            | https://example.com/any-other-path/ |

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.3.5
```
I was also able to reproduce this on one more pretty different cluster with Traefik `1.3.4`.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

[Official helm chart](https://github.com/kubernetes/charts/tree/master/stable/traefik), latest version.

### PR DESCRIPTION
**Pull request by dtomcej**
### What does this PR do?

Rebuilds entrypoint redirects when used with `PathPrefixStrip` or `AddPrefix`

### Motivation

Fixes #1957
and issues linked to #2024

### More

- [x] Added/updated documentation - No documentation needed, as this is intended behavior
- [x] Rebuild trailing slash from prefix match
- [x] Added/updated tests
- [x] Rebuild correct redirect when prefix is added
- [x] Added/updated tests

### CODE REVIEW

**Comment by kachkaev** [comment]
Can't wait to see this fix landing a release! 😍 

#1957 is in [top 10 issues by the number of 👍](https://github.com/containous/traefik/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc), so this PR is waited by many!

File: middlewares/redirect/redirect.go [hunk 1]
```diff
@@ -85,6 +86,28 @@ func (h *handler) ServeHTTP(rw http.ResponseWriter, req *http.Request, next http
 		return
 	}
 
+	if prefix, prefixOk := req.Context().Value(middlewares.StripPrefixKey).(string); prefixOk {
```
Comment (mmatur) [inline middlewares/redirect/redirect.go]: You should maybe simplify this part like that

```go
if stripPrefix, stripPrefixOk := req.Context().Value(middlewares.StripPrefixKey).(string); stripPrefixOk {
	if len(stripPrefix) > 0 {
		tempPath := parsedURL.Path
		parsedURL.Path = stripPrefix
		if len(tempPath) > 0 && tempPath != "/" {
			parsedURL.Path = stripPrefix + tempPath
		}

		if trailingSlash, trailingSlashOk := req.Context().Value(middlewares.StripPrefixSlashKey).(bool); trailingSlashOk {
			if trailingSlash {
				if !strings.HasSuffix(parsedURL.Path, "/") {
					parsedURL.Path = fmt.Sprintf("%s/", parsedURL.Path)
				}
			}
		}
	}
}

if addPrefix, addPrefixOk := req.Context().Value(middlewares.AddPrefixKey).(string); addPrefixOk {
	if len(addPrefix) > 0 {
		parsedURL.Path = strings.Replace(parsedURL.Path, addPrefix, "", 1)
	}
}
```

You update `parsedURL` instead of re parsing the URL multiple times
WDYT?

File: integration/https_test.go [hunk 2]
```diff
@@ -804,3 +804,116 @@ func modifyCertificateConfFileContent(c *check.C, certFileName, confFileName, en
 		c.Assert(err, checker.IsNil)
 	}
 }
+
+func (s *HTTPSSuite) TestEntrypointHttpsRedirectAndPathPrefixStrip(c *check.C) {
+	cmd, display := s.traefikCmd(withConfigFile("fixtures/https/https_redirect.toml"))
```
[the remark this answers is not in the document]
Comment (dtomcej) [reply integration/https_test.go]: Great suggestion

File: middlewares/stripPrefix.go [hunk 3]
```diff
@@ -17,18 +26,26 @@ type StripPrefix struct {
...
+			var trailingSlash bool
+			if r.URL.Path == prefix+"/" {
+				trailingSlash = true
+			}
 			r.URL.Path = stripPrefix(r.URL.Path, prefix)
 			if r.URL.RawPath != "" {
 				r.URL.RawPath = stripPrefix(r.URL.RawPath, prefix)
 			}
-			s.serveRequest(w, r, strings.TrimSpace(prefix))
+			s.serveRequest(w, r, strings.TrimSpace(prefix), trailingSlash)
```
[the remark this answers is not in the document]
Comment (dtomcej) [reply middlewares/stripPrefix.go]: No, because `r.URL.Path` gets modified from the original check, to the `serveRequest` call.

I have simplified the init though.

**Comment by mmatur** [comment]
Could be nice to have this fix in v1.7 WDYT ?

File: middlewares/stripPrefix.go [hunk 4]
```diff
@@ -17,18 +26,21 @@ type StripPrefix struct {
 func (s *StripPrefix) ServeHTTP(w http.ResponseWriter, r *http.Request) {
 	for _, prefix := range s.Prefixes {
 		if strings.HasPrefix(r.URL.Path, prefix) {
+			trailingSlash := (r.URL.Path == prefix+"/")
```
Comment (mmatur) [inline middlewares/stripPrefix.go]: Redundant parentheses

Comment (dtomcej) [reply middlewares/stripPrefix.go]: Good catch :)

**Comment by dtomcej** [comment]
I can rebase and squeeze this into 1.7!

**Comment by dtomcej** [comment]
Found that I didn't handle/test `PathPrefixStripRegex` properly. Didn't know that was a matcher 😝  Updated code coming.

File: integration/https_test.go [hunk 5]
```diff
@@ -804,3 +804,110 @@ func modifyCertificateConfFileContent(c *check.C, certFileName, confFileName, en
...
+			sourceURL:   "http://127.0.0.1:8888/api/bacon",
+			expectedURL: "https://foo.com:8443/api/bacon",
+		},
+		{
+			desc:        "Stripped URL Regex with path and trailing slash redirect",
+			host:        "foo.com",
+			sourceURL:   "http://127.0.0.1:8888/api/bacon/",
+			expectedURL: "https://foo.com:8443/api/bacon/",
+		},
+	}
```
Comment (emilevauge) [inline integration/https_test.go]: I would add few edge cases like double trailing redirect `http://127.0.0.1:8888/api/bacon//`, no path (with/without) redirect `http://127.0.0.1:8888`

Comment (dtomcej) [reply integration/https_test.go]: Added no path + double trailing slash tests.

There is an outstanding "issue" where an entrypoint redirect doesn't work when a frontend isn't matched (I think due to the middleware being applied to frontend chains). This would be out of the scope of this PR.

**Comment by edasque** [comment]
Is this in 1.7.0 rc3? I have a problem that seems similar where PathPrefixStrip: /container1 works when hitting /container1/ but not /container1 (where it doesn't prefix strip the subsequent queries leading to http://192.168.7.229:40080/bower_components/slimScroll/jquery.slimscroll.min.js instead of http://192.168.7.229:40080/organizr/bower_components/bootstrap/dist/css/bootstrap.min.css?v=1.80

**Comment by marianschmotzer** [comment]
I just tried 1.7.0 rc3 and PathPrefixStrip works (or doesn't work to be honest)as mentioned by edasque. I tired even to place redirection to config file - 
```
[entryPoints.https.redirect]                                                                                                                                                                      
     regex = "(http[a-z]{0,1}://[^/]+/([a-zA-Z0-9-]+)[^/])$"                                                                                                                                         
     replacement = "${1}/" 
```
But same results as in 1.6.5 - it doesn't work.

**Comment by edasque** [comment]
@Marianschmotzer , do you know if it was supposed to?

**Comment by marianschmotzer** [comment]
@edasque I've creates short blog about this problem with our "fix" you can find it here maybe will be helpful [https://medium.com/@smoco/fighting-trailing-slash-problem-c0416023d20e](https://medium.com/@smoco/fighting-trailing-slash-problem-c0416023d20e)

**Comment by edasque** [comment]
Cool trick @marianschmotzer but I’d rather not add nginx or anything to make something so simple work.

**Comment by dtomcej** [comment]
@marianschmotzer  @edasque If you are still having problems, can you please open a new issue instead of bumping a closed PR?

Thanks!

**Comment by edasque** [comment]
@dtomcej please find it here: https://github.com/containous/traefik/issues/3852

@marianschmotzer can you confirm this illustrates the issue correctly.

**Comment by marianschmotzer** [comment]
Hi
seems quite clear to me

ut 4. 9. 2018 o 23:04 Erik Dasque <notifications@github.com> napísal(a):
