### PR TITLE
Handle respondingtimeout and better shutdown tests.

### LINKED ISSUE #5763: Transport responding timeouts in V2 not working
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Configure transport responding timeouts  in static config file or from command line:

```yaml
entrypoints:
  web:
    address: ":80"
    transport:
      respondingTimeouts: 
        readTimeout: "10s"
        idleTimeout: 10
```
or with CLI options
```
--entryPoints.web.address=":80" \
--entryPoints.web.transport.respondingTimeouts.readTimeout="10s" \
--entryPoints.web.transport.respondingTimeouts.idleTimeout=10 \
```

### What did you expect to see?

After keeping an open connection it should be closed after the configured timeout, e.g.
``` 
$ time nc localhost 80
```

### What did you see instead?

Traefik does not close the connection after waiting for configured time

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.0.4
Codename:     montdor
Go version:   go1.13.3
Built:        2019-10-28T20:23:57Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```yaml
log:
  level: DEBUG
providers:
  file:
    filename: /etc/traefik/dynamic-conf.yml
entrypoints:
  web:
    address: ":80"
    transport:
      respondingTimeouts:
        readTimeout: "10s"
        writeTimeout: "10s"
        idleTimeout: 10

```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik_1    | time="2019-11-01T13:36:38Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yml"
traefik_1    | time="2019-11-01T13:36:38Z" level=info msg="Traefik version 2.0.4 built on 2019-10-28T20:23:57Z"
traefik_1    | time="2019-11-01T13:36:38Z" level=debug msg="Static configuration loaded {\"global\":{\"checkNewVersion\":true},\"serversTransport\":{\"maxIdleConnsPerHost\":200},\"entryPoints\":{\"web\":{\"address\":\":80\",\"transport\":{\"lifeCycle\":{\"graceTimeOut\":10000000000},\"respondingTimeouts\":{\"readTimeout\":10000000000,\"writeTimeout\":10000000000,\"idleTimeout\":10000000000}},\"forwardedHeaders\":{}}},\"providers\":{\"providersThrottleDuration\":2000000000,\"file\":{\"watch\":true,\"filename\":\"/etc/traefik/dynamic-conf.yml\"}},\"log\":{\"level\":\"DEBUG\",\"format\":\"common\"}}"

```

### PR DESCRIPTION
**Pull request by juliens**
### What does this PR do?
This PR handles the `RespondingTimeout` options and improve `Shutdown`.

### Motivation

Fixes #5763 

### More

- [x] Added/updated tests
~- [ ] Added/updated documentation~

Co-authored-by: Mathieu Lonjaret <mathieu.lonjaret@gmail.com>

### CODE REVIEW

File: pkg/server/server_entrypoint_tcp.go [hunk 1]
```diff
@@ -171,6 +171,21 @@ func (e *TCPEntryPoint) StartTCP(ctx context.Context) {
...
+				err := writeCloser.SetReadDeadline(time.Now().Add(time.Duration(e.transportConfiguration.RespondingTimeouts.ReadTimeout)))
+				if err != nil {
+					logger.Errorf("Error while setting read deadline: %v", err)
+				}
+			}
+
+			if e.transportConfiguration.RespondingTimeouts.WriteTimeout > 0 {
+				err = writeCloser.SetWriteDeadline(time.Now().Add(time.Duration(e.transportConfiguration.RespondingTimeouts.WriteTimeout)))
+				if err != nil {
+					log.WithoutContext().Errorf("Error while setting write deadline: %v", err)
```
Comment (mpl) [inline pkg/server/server_entrypoint_tcp.go]: why not just logger.Errorf like above L178? or maybe we should change the one L178?

File: pkg/server/server_entrypoint_tcp.go [hunk 2]
```diff
@@ -171,6 +171,21 @@ func (e *TCPEntryPoint) StartTCP(ctx context.Context) {
 		}
 
 		safe.Go(func() {
+			// Set read/write for respect timeout even without first byte.
```
Comment (mpl) [inline pkg/server/server_entrypoint_tcp.go]:
```suggestion
			// Enforce read/write timeouts at the connection level so that they get
			// triggered even without a first byte being seen, as opposed to with
			// timeouts at the server level.
```

File: pkg/server/server_entrypoint_tcp.go [hunk 3]
```diff
@@ -195,44 +210,60 @@ func (e *TCPEntryPoint) Shutdown(ctx context.Context) {
...
-					err = e.httpsServer.Server.Close()
-					if err != nil {
-						logger.Error(err)
-					}
+			err := e.httpsServer.Server.Shutdown(ctx)
+			if err == nil {
+				return
+			}
+			if ctx.Err() == context.DeadlineExceeded {
+				logger.Debugf("Wait server shutdown is overdue to: %s", err)
```
Comment (mpl) [inline pkg/server/server_entrypoint_tcp.go]:
```suggestion
				logger.Debugf("Server failed to shutdown before deadline because: %s", err)
```

File: pkg/server/server_entrypoint_tcp.go [hunk 4]
```diff
@@ -195,44 +210,60 @@ func (e *TCPEntryPoint) Shutdown(ctx context.Context) {
...
-				if ctx.Err() == context.DeadlineExceeded {
-					logger.Debugf("Wait hijack connection is overdue to: %s", err)
-					e.tracker.Close()
-				}
+			err := e.tracker.Shutdown(ctx)
+			if err == nil {
+				return
+			}
+			if ctx.Err() == context.DeadlineExceeded {
+				logger.Debugf("Wait hijack connection is overdue to: %s", err)
```
Comment (mpl) [inline pkg/server/server_entrypoint_tcp.go]:
```suggestion
				logger.Debugf("Server failed to shutdown before deadline because: %s", err)
```

File: pkg/server/server_entrypoint_tcp.go [hunk 5]
```diff
@@ -195,44 +210,60 @@ func (e *TCPEntryPoint) Shutdown(ctx context.Context) {
...
-					err = e.httpServer.Server.Close()
-					if err != nil {
-						logger.Error(err)
-					}
+			err := e.httpServer.Server.Shutdown(ctx)
+			if err == nil {
+				return
+			}
+			if ctx.Err() == context.DeadlineExceeded {
+				logger.Debugf("Server failed to shutdown within deadline because: %s", err)
```
Comment (mpl) [inline pkg/server/server_entrypoint_tcp.go]:
```suggestion
				logger.Debugf("Server failed to shutdown before deadline because: %s", err)
```

File: pkg/server/server_entrypoint_tcp.go [hunk 6]
```diff
@@ -195,44 +210,60 @@ func (e *TCPEntryPoint) Shutdown(ctx context.Context) {
...
+				if err = e.httpServer.Server.Close(); err != nil {
+					logger.Error(err)
 				}
+				return
 			}
+			logger.Error(err)
+			// We expect Close to fail again because Shutdown most likely failed when trying
+			// to close a listener. We still call it however, to make sure that all connections
+			// get closed as well.
+			e.httpServer.Server.Close()
```
Comment (mpl) [inline pkg/server/server_entrypoint_tcp.go]: maybe we can refactor all that in a func/closure that works for both httpServer and httpsServer?
