### PR TITLE
fix missing trailers with retry

### LINKED ISSUE #4433: GRPC client error "unexpected EOS on DATA frame" with retry enabled in traefik
### Do you want to request a *feature* or report a *bug*?

*Bug*

### What did you do?

We started to get `WARNING: RPC failed: Status{code=INTERNAL, description=Received unexpected EOS on DATA frame from server., cause=null}`
in our GRPC client when using `[retry]` in our traefik config.

* We were able to recreate using GRPC HelloWorld Example: https://github.com/grpc/grpc-java/tree/master/examples

### What did you expect to see?

```
$ ./build/install/examples/bin/hello-world-client
Jan 26, 2019 11:24:55 PM io.grpc.examples.helloworld.HelloWorldClient greet
INFO: Will try to greet world ...
Jan 26, 2019 11:24:55 PM io.grpc.examples.helloworld.HelloWorldClient greet
INFO: Greeting: Hello world
```

### What did you see instead?

```
./build/install/examples/bin/hello-world-client
Jan 26, 2019 11:19:11 PM io.grpc.examples.helloworld.HelloWorldClient greet
INFO: Will try to greet world ...
Jan 26, 2019 11:19:11 PM io.grpc.examples.helloworld.HelloWorldClient greet
WARNING: RPC failed: Status{code=INTERNAL, description=Received unexpected EOS on DATA frame from server., cause=null}
```

* Server Logs show normal/successful operation.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Traefik version v1.7.7 built on 2019-01-08_10:21:03AM -> Not Working
Traefik version v1.7.6 built on 2018-12-14_06:43:37AM -> Working
Traefik version v1.7.5 built on 2018-12-03_11:01:00AM -> Working
Traefik version v1.7.4 built on 2018-10-30_10:44:30AM -> Working
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
logLevel = "DEBUG"

defaultEntryPoints = ["http"]

[retry]
  attempts = 3

[entryPoints]
  [entryPoints.http]
  address = ":80"

[file]

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "h2c://backend:50051"

[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.routes.test_1]
    rule = "Host:localhost"
```

### If applicable, please paste the log output at DEBUG level (`--logLevel=DEBUG` switch)

```
DEBU[2019-01-26T14:37:34Z] vulcand/oxy/roundrobin/rr: begin ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/helloworld.Greeter/SayHello\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-java-netty/1.18.0\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.18.0.1:47744\",\"RequestURI\":\"/helloworld.Greeter/SayHello\",\"TLS\":null}"
DEBU[2019-01-26T14:37:34Z] vulcand/oxy/roundrobin/rr: Forwarding this request to URL  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/helloworld.Greeter/SayHello\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-java-netty/1.18.0\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.18.0.1:47744\",\"RequestURI\":\"/helloworld.Greeter/SayHello\",\"TLS\":null}" ForwardURL="h2c://172.18.0.3:50051"
DEBU[2019-01-26T14:37:34Z] vulcand/oxy/forward: begin ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"h2c\",\"Opaque\":\"\",\"User\":null,\"Host\":\"172.18.0.3:50051\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-java-netty/1.18.0\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.18.0.1:47744\",\"RequestURI\":\"/helloworld.Greeter/SayHello\",\"TLS\":null}"
DEBU[2019-01-26T14:37:34Z] vulcand/oxy/forward/http: begin ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"h2c\",\"Opaque\":\"\",\"User\":null,\"Host\":\"172.18.0.3:50051\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-java-netty/1.18.0\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.18.0.1:47744\",\"RequestURI\":\"/helloworld.Greeter/SayHello\",\"TLS\":null}"
DEBU[2019-01-26T14:37:34Z] vulcand/oxy/forward/http: Round trip: h2c://172.18.0.3:50051, code: 200, Length: 18, duration: 10.0082ms
DEBU[2019-01-26T14:37:34Z] vulcand/oxy/forward/http: completed ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"h2c\",\"Opaque\":\"\",\"User\":null,\"Host\":\"172.18.0.3:50051\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-java-netty/1.18.0\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.18.0.1:47744\",\"RequestURI\":\"/helloworld.Greeter/SayHello\",\"TLS\":null}"
DEBU[2019-01-26T14:37:34Z] vulcand/oxy/forward: completed ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"h2c\",\"Opaque\":\"\",\"User\":null,\"Host\":\"172.18.0.3:50051\",\"Path\":\"\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-java-netty/1.18.0\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.18.0.1:47744\",\"RequestURI\":\"/helloworld.Greeter/SayHello\",\"TLS\":null}"
DEBU[2019-01-26T14:37:34Z] vulcand/oxy/roundrobin/rr: completed ServeHttp on request  Request="{\"Method\":\"POST\",\"URL\":{\"Scheme\":\"\",\"Opaque\":\"\",\"User\":null,\"Host\":\"\",\"Path\":\"/helloworld.Greeter/SayHello\",\"RawPath\":\"\",\"ForceQuery\":false,\"RawQuery\":\"\",\"Fragment\":\"\"},\"Proto\":\"HTTP/2.0\",\"ProtoMajor\":2,\"ProtoMinor\":0,\"Header\":{\"Content-Type\":[\"application/grpc\"],\"Grpc-Accept-Encoding\":[\"gzip\"],\"Te\":[\"trailers\"],\"User-Agent\":[\"grpc-java-netty/1.18.0\"]},\"ContentLength\":-1,\"TransferEncoding\":null,\"Host\":\"localhost:80\",\"Form\":null,\"PostForm\":null,\"MultipartForm\":null,\"Trailer\":null,\"RemoteAddr\":\"172.18.0.1:47744\",\"RequestURI\":\"/helloworld.Greeter/SayHello\",\"TLS\":null}"
```

### PR DESCRIPTION
**Pull request by juliens**
### What does this PR do?
When the retry middleware has already sent the headers, use the original headers map to be able to send trailers.

### Motivation
Fix trailers and Grpc issues.
Fixes #4433 

### More

- [x] Added/updated tests

### CODE REVIEW

File: middlewares/retry.go [hunk 1]
```diff
@@ -110,6 +110,7 @@ type retryResponseWriterWithoutCloseNotify struct {
 	responseWriter http.ResponseWriter
 	headers        http.Header
 	shouldRetry    bool
+	writed         bool
```
Comment (dtomcej) [inline middlewares/retry.go]:
```suggestion
	written         bool
```

File: middlewares/retry.go [hunk 2]
```diff
@@ -121,6 +122,9 @@ func (rr *retryResponseWriterWithoutCloseNotify) DisableRetries() {
 }
 
 func (rr *retryResponseWriterWithoutCloseNotify) Header() http.Header {
+	if rr.writed {
```
Comment (dtomcej) [inline middlewares/retry.go]:
```suggestion
	if rr.written {
```

File: middlewares/retry.go [hunk 3]
```diff
@@ -155,6 +159,7 @@ func (rr *retryResponseWriterWithoutCloseNotify) WriteHeader(code int) {
 	}
 
 	rr.responseWriter.WriteHeader(code)
+	rr.writed = true
```
Comment (dtomcej) [inline middlewares/retry.go]:
```suggestion
	rr.written = true
```
