### PR TITLE
Fix empty tls flag

### LINKED ISSUE #488: Enable to define empty TLS option by flag for Let's Encrypt
I wanted to configure traefik for my project only by flags, in order to limit my configuration file to a simple docker-compose.
This is an extract of my docker-compose file.

service-front:
  labels:
     - "traefik.backend=front"
     - "traefik.port=80"
     - "traefik.frontend.rule=Host:domain.com"
     - "traefik.frontend.entryPoints=http,https"
  image: kebuu/zenquizz-front:dev
traefik:
  image: traefik
  command: --web --docker --acme --acme.domains=domain.com --acme.email=test@traefik.io --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS' --acme.storagefile=acme.json --docker.domain=localhost --logLevel=DEBUG
  ports:
    - "80:80"
    - "443:443"
    - "8080:8080"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /dev/null:/traefik.toml
    - /opt/acme/acme.json:/acme.json
  labels:
    - "traefik.enable=false"

In my logs I could see that TLS option was not set:

\"https\":{\"Network\":\"\",\"Address\":\":443\",\"TLS\":null,\"Redirect\":null}}

### PR DESCRIPTION
**Pull request by emilevauge**
Fixes #488 

Signed-off-by: Emile Vauge <emile@vauge.com>

### CODE REVIEW

File: configuration.go [hunk 1]
```diff
@@ -93,7 +93,7 @@ func (ep *EntryPoints) String() string {
 // Set's argument is a string to be parsed to set the flag.
 // It's a comma-separated list, so we split it.
 func (ep *EntryPoints) Set(value string) error {
-	regex := regexp.MustCompile("(?:Name:(?P<Name>\\S*))\\s*(?:Address:(?P<Address>\\S*))?\\s*(?:TLS:(?P<TLS>\\S*))?\\s*(?:Redirect.EntryPoint:(?P<RedirectEntryPoint>\\S*))?\\s*(?:Redirect.Regex:(?P<RedirectRegex>\\S*))?\\s*(?:Redirect.Replacement:(?P<RedirectReplacement>\\S*))?")
+	regex := regexp.MustCompile("(?:Name:(?P<Name>\\S*))\\s*(?:Address:(?P<Address>\\S*))?\\s*(?:TLS:(?P<TLS>\\S*))?\\s*((?P<TLSACME>TLS))?\\s*(?:Redirect.EntryPoint:(?P<RedirectEntryPoint>\\S*))?\\s*(?:Redirect.Regex:(?P<RedirectRegex>\\S*))?\\s*(?:Redirect.Replacement:(?P<RedirectReplacement>\\S*))?")
```
Comment (vdemeester) [inline configuration.go]: :scream_cat:

**Comment by vdemeester** [comment]
LGTM 🐯
