### PR TITLE
Fix default configuration

### LINKED ISSUE #427: Bad default values in configuration
Default values for `EntryPoints` and `DefaultEntryPoints` are not set correctly:
https://github.com/containous/traefik/blob/master/traefik.go#L117
This ends up with error:
```
No entrypoint defined for frontend ..., defaultEntryPoints:[]. Skipping it
```

### LINKED ISSUE #429: Panic on help
`traefik --help` panics:

```
./traefik --help
panic: interface conversion: interface is main.Constraints, not []types.Constraint

goroutine 1 [running]:
panic(0xe11a80, 0xc820295340)
	/home/emile/.gvm/gos/go1.6/src/runtime/panic.go:464 +0x3e6
main.(*Constraints).SetValue(0xc8202d81a0, 0xc2f280, 0xc820317ea0)
	/home/emile/dev/go/src/github.com/containous/traefik/configuration.go:176 +0x56
github.com/containous/traefik/vendor/github.com/containous/flaeg.PrintHelpWithCommand(0xc82017d348, 0xc82017d318, 0xc8202cdd10, 0xc8201e6d70, 0xc82025b6b0, 0x2, 0x2, 0x0, 0x0)
	/home/emile/dev/go/src/github.com/containous/traefik/vendor/github.com/containous/flaeg/flaeg.go:593 +0x764
github.com/containous/traefik/vendor/github.com/containous/flaeg.PrintErrorWithCommand(0x7f6f246c4028, 0xc82025b630, 0xc82017d348, 0xc82017d318, 0xc8202cdd10, 0xc8201e6d70, 0xc82025b6b0, 0x2, 0x2, 0x0, ...)
	/home/emile/dev/go/src/github.com/containous/traefik/vendor/github.com/containous/flaeg/flaeg.go:648 +0xef
github.com/containous/traefik/vendor/github.com/containous/flaeg.LoadWithCommand(0xc8201e6d70, 0xc82000a3f0, 0x1, 0x1, 0xc8202cdc80, 0xc82025b6b0, 0x2, 0x2, 0x0, 0x0)
	/home/emile/dev/go/src/github.com/containous/traefik/vendor/github.com/containous/flaeg/flaeg.go:540 +0x449
github.com/containous/traefik/vendor/github.com/containous/flaeg.(*Flaeg).Parse(0xc8201ccba0, 0xc8201e6d70, 0x1, 0x0, 0x0)
	/home/emile/dev/go/src/github.com/containous/traefik/vendor/github.com/containous/flaeg/flaeg.go:701 +0xb8
main.main()
	/home/emile/dev/go/src/github.com/containous/traefik/traefik.go:93 +0x15ec
```

### PR DESCRIPTION
**Pull request by emilevauge**
Fixes #427 
Fixes #429

Signed-off-by: Emile Vauge <emile@vauge.com>

### CODE REVIEW

File: version.go [hunk 1]
```diff
@@ -2,7 +2,7 @@ package main
 
 var (
 	// Version holds the current version of traefik.
-	Version = ""
+	Version = "dev"
 	// BuildDate holds the build date of traefik.
-	BuildDate = ""
+	BuildDate = "I don't remember exactly"
```
Comment (vdemeester) [inline version.go]: :joy:

**Comment by vdemeester** [comment]
LGTM :wink:
