### PR TITLE
fix: Double compression.

### LINKED ISSUE #1060: Malformed/garbled HTML response when compress is enabled
### What version of Traefik are you using (`traefik version`)?

1.1.2-a

### What is your environment & configuration (arguments, toml...)?

```toml
# traefik.toml
logLevel = "INFO"
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
[kubernetes]
[web]
address = ":8081"
```

<details>
<summary>traefik service.yaml</summary>

```yml
# Source: traefik/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: rtraefik-traefik
  labels:
    app: rtraefik-traefik
    chart: "traefik-1.1.2-a"
    release: "rtraefik"
    heritage: "Tiller"
spec:
  type: LoadBalancer
  selector:
    app: rtraefik-traefik
  ports:
  - port: 80
    name: http
  - port: 443
    name: https
```
</details>

<details>
<summary>traefik deployment.yaml</summary>

```
# Source: traefik/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: rtraefik-traefik
  labels:
    app: rtraefik-traefik
    chart: "traefik-1.1.2-a"
    release: "rtraefik"
    heritage: "Tiller"
spec:
  template:
    metadata:
      labels:
        app: rtraefik-traefik
        chart: "traefik-1.1.2-a"
        release: "rtraefik"
        heritage: "Tiller"
    spec:
      terminationGracePeriodSeconds: 60
      hostNetwork: true
      containers:
      - image: traefik:v1.1.2
        name: rtraefik-traefik
        resources:
          requests:
            cpu: "100m"
            memory: "20Mi"
          limits:
            cpu: "100m"
            memory: "30Mi"
        readinessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        volumeMounts:
        - mountPath: /config
          name: config
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 8081
        args:
        - --configfile=/config/traefik.toml
      volumes:
      - name: config
        configMap:
          name: rtraefik-traefik
```
</details>

<details>
<summary>kubectl get ingress rjenkins-jenkins -o yaml</summary>

```
$ kubectl get ingress rjenkins-jenkins -o yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"kind":"Ingress","apiVersion":"extensions/v1beta1","metadata":{"name":"rjenkins-jenkins","namespace":"default","selfLink":"/apis/extensions/v1beta1/namespaces/default/ingresses/rjenkins-jenkins","uid":"fd3bb42f-df57-11e6-bb42-0050568a2a2f","resourceVersion":"1052907","generation":2,"creationTimestamp":"2017-01-20T21:32:48Z","labels":{"app":"rjenkins-jenkins","chart":"traefik-1.1.2-a","heritage":"Tiller","release":"rtraefik"}},"spec":{"rules":[{"host":"jenkins.example.com","http":{"paths":[{"backend":{"serviceName":"rjenkins-jenkins","servicePort":8080}}]}}]},"status":{"loadBalancer":{}}}'
  creationTimestamp: 2017-01-20T21:32:48Z
  generation: 2
  labels:
    app: rjenkins-jenkins
    chart: traefik-1.1.2-a
    heritage: Tiller
    release: rtraefik
  name: rjenkins-jenkins
  namespace: default
  resourceVersion: "1053907"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/rjenkins-jenkins
  uid: fd3bb42f-df57-11e6-bb42-0050568a2a2f
spec:
  rules:
  - host: jenkins.example.com
    http:
      paths:
      - backend:
          serviceName: rjenkins-jenkins
          servicePort: 8080
status:
  loadBalancer: {}
```
</details>
<br>

### What did you do?

I'm using traefik in kubernetes, installed by helm.  I have a jenkins instance that I'm trying to proxy to.  I'm also using traefik to proxy traefik's dashboard and prometheus server + alertmanager.

### What did you expect to see?

I expected Jenkins page to load successfully.  Other ingress resources like traefik's dashboard and prometheus are successfully loading.

### What did you see instead?

Jenkins gives malformed HTTP response.  The headers look OK and in-tact but the HTML payload is malformed.  This happens on all browsers tested including OSX Chrome and Firefox.  My best guess is that browsers are trying to gzip decode the response when the response isn't being compressed.  See screenshots:

image

Jenkins will load OK if I hit the service IP and port directly:
image

The headers from the malformed response:
image

The raw response from the malformed response:
image

<details>
<summary>curl http://jenkins.example.com/login -v</summary>

```
$ curl http://jenkins.example.com/login -v
*   Trying 10.163.148.196...
* TCP_NODELAY set
* Connected to jenkins.example.com (10.163.148.196) port 80 (#0)
> GET /login HTTP/1.1
> Host: jenkins.example.com
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Cache-Control: no-cache,no-store,must-revalidate
< Content-Type: text/html;charset=UTF-8
< Date: Mon, 23 Jan 2017 21:23:39 GMT
< Expires: 0
< Server: Jetty(9.2.z-SNAPSHOT)
< Set-Cookie: JSESSIONID.ab758541=tzum86vvk6es1iw413gtdcsql;Path=/;HttpOnly
< Vary: Accept-Encoding
< X-Content-Type-Options: nosniff
< X-Frame-Options: sameorigin
< X-Hudson: 1.395
< X-Hudson-Cli-Port: 50000
< X-Hudson-Theme: default
< X-Instance-Identity: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv0hMZsLNMdkrNHMnwFvR8Ks+xjLupJnNzofDhIJaswpRfcFN1LvrzahQatRmbka7AhDt3G90Syo+3gaCMUxAFI0Px61nhTJ8hE8hhgNf6yYUnfxg0HRJ4j3ddumCvnQoPeq8x/rd+wxkZW7u/IpJHoS6ShFUzrfTuZSWI8v4k3A9SwXm+4x9r7c0VduEl56wefaBnSRi8cJXbXxyjtZ4/v4rurh6rnSoorlsTAmx1R9M+jZ9JFedFRc1e54Mnob1FOAAyvQryAr+HAGRAANv/EGIJ4FZBxjGMhliBzo6oifvaY6C/St/7r2FHFcp1VD4mt7naKgbaTbKExcZfsn1vwIDAQAB
< X-Jenkins: 2.19.4
< X-Jenkins-Cli-Port: 50000
< X-Jenkins-Cli2-Port: 50000
< X-Jenkins-Session: d200f825
< X-Ssh-Endpoint: jenkins.example.com:35985
< Transfer-Encoding: chunked
<





  <!DOCTYPE html><html><head resURL="/static/d200f825" data-rooturl="" data-resurl="/static/d200f825">


    <title>Jenkins</title><link rel="stylesheet" href="/static/d200f825/css/layout-common.css" type="text/css" /><link rel="stylesheet" href="/static/d200f825/css/style.css" type="text/css" /><link rel="stylesheet" href="/static/d200f825/css/color.css" type="text/css" /><link rel="stylesheet" href="/static/d200f825/css/responsive-grid.css" type="text/css" /><link rel="shortcut icon" href="/static/d200f825/favicon.ico" type="image/vnd.microsoft.icon" /><link color="black" rel="mask-icon" href="/images/mask-icon.svg" /><script>var isRunAsTest=false; var rootURL=""; var resURL="/static/d200f825";</script><script src="/static/d200f825/scripts/prototype.js" type="text/javascript"></script><script src="/static/d200f825/scripts/behavior.js" type="text/javascript"></script><script src='/adjuncts/d200f825/org/kohsuke/stapler/bind.js' type='text/javascript'></script><script src="/static/d200f825/scripts/yui/yahoo/yahoo-min.js"></script><script src="/static/d200f825/scripts/yui/dom/dom-min.js"></script><script src="/static/d200f825/scripts/yui/event/event-min.js"></script><script src="/static/d200f825/scripts/yui/animation/animation-min.js"></script><script src="/static/d200f825/scripts/yui/dragdrop/dragdrop-min.js"></script><script src="/static/d200f825/scripts/yui/container/container-min.js"></script><script src="/static/d200f825/scripts/yui/connection/connection-min.js"></script><script src="/static/d200f825/scripts/yui/datasource/datasource-min.js"></script><script src="/static/d200f825/scripts/yui/autocomplete/autocomplete-min.js"></script><script src="/static/d200f825/scripts/yui/menu/menu-min.js"></script><script src="/static/d200f825/scripts/yui/element/element-min.js"></script><script src="/static/d200f825/scripts/yui/button/button-min.js"></script><script src="/static/d200f825/scripts/yui/storage/storage-min.js"></script><script src="/static/d200f825/scripts/hudson-behavior.js" type="text/javascript"></script><script src="/static/d200f825/scripts/sortable.js" type="text/javascript"></script><script>crumb.init("", "");</script><link rel="stylesheet" href="/static/d200f825/scripts/yui/container/assets/container.css" type="text/css" /><link rel="stylesheet" href="/static/d200f825/scripts/yui/assets/skins/sam/skin.css" type="text/css" /><link rel="stylesheet" href="/static/d200f825/scripts/yui/container/assets/skins/sam/container.css" type="text/css" /><link rel="stylesheet" href="/static/d200f825/scripts/yui/button/assets/skins/sam/button.css" type="text/css" /><link rel="stylesheet" href="/static/d200f825/scripts/yui/menu/assets/skins/sam/menu.css" type="text/css" /><meta name="ROBOTS" content="INDEX,NOFOLLOW" /><script src="/static/d200f825/jsbundles/page-init.js" type="text/javascript"></script></head><body data-model-type="hudson.model.Hudson" id="jenkins" class="yui-skin-sam jenkins-2.19.4 two-column" data-version="2.19.4"><a href="#skip2content" class="skiplink">Skip to content</a><div id="page-head"><div id="header"><div class="logo"><a id="jenkins-home-link" href="/"><img src="/static/d200f825/images/headshot.png" alt="title" id="jenkins-head-icon" /><img src="/static/d200f825/images/title.png" alt="title" width="139" id="jenkins-name-icon" height="34" /></a></div><div class="login"> <a href="/loginEntry?from=%2F"><b>log in</b></a></div><div class="searchbox hidden-xs"><form method="get" name="search" action="/search/" style="position:relative;" class="no-json"><div id="search-box-minWidth"></div><div id="search-box-sizer"></div><div id="searchform"><input name="q" placeholder="search" id="search-box" class="has-default-text" /> <a href="http://wiki.jenkins-ci.org/display/JENKINS/Search+Box"><img src="/static/d200f825/images/16x16/help.png" style="width: 16px; height: 16px; " class="icon-help icon-sm" /></a><div id="search-box-completion"></div><script>createSearchBox("/search/");</script></div></form></div></div><div id="breadcrumbBar"><tr id="top-nav"><td id="left-top-nav" colspan="2"><link rel='stylesheet' href='/adjuncts/d200f825/lib/layout/breadcrumbs.css' type='text/css' /><script src='/adjuncts/d200f825/lib/layout/breadcrumbs.js' type='text/javascript'></script><div class="top-sticker noedge"><div class="top-sticker-inner"><div id="right-top-nav"></div><ul id="breadcrumbs"><li class="item"><a href="/" class="model-link inside">Jenkins</a></li><li href="/" class="children"></li></ul><div id="breadcrumb-menu-target"></div></div></div></td></tr></div></div><div id="page-body" class="clear"><div id="side-panel"></div><div id="main-panel"><a name="skip2content"></a><div style="margin: 2em;"><form method="post" name="login" action="j_security_check" style="text-size:smaller"><table><tr><td>User:</td><td><input type="text" name="j_username" id="j_username" autocorrect="off" autocapitalize="off" /></td></tr><tr><td>Password:</td><td><input type="password" name="j_password" /></td></tr></table><input name="from" type="hidden" /><input name="Submit" type="submit" value="log in" class="submit-button primary" /><script>
            $('j_username').focus();
* Curl_http_done: called premature == 0
* Connection #0 to host jenkins.example.com left intact
          </script></form></div></div></div><footer><div class="container-fluid"><div class="row"><div class="col-md-6" id="footer"></div><div class="col-md-18"><span class="page_generated">Page generated: Jan 23, 2017 9:23:39 PM UTC</span><span class="rest_api"><a href="api/">REST API</a></span><span class="jenkins_ver"><a href="http://jenkins-ci.org/">Jenkins ver. 2.19.4</a></span></div></div></div></footer></body></html>
```
</details>

### PR DESCRIPTION
**Pull request by ldez**
### Description

Don't compress when `Content-Encoding` header is already present.

Fixes #1060

### CODE REVIEW

File: middlewares/compress.go [hunk 1]
```diff
@@ -6,12 +6,25 @@ import (
...
+		next.ServeHTTP(rw, r)
+	} else {
+		newGzipHandler := gziphandler.GzipHandler(next)
+		newGzipHandler.ServeHTTP(rw, r)
+	}
+}
+
+func isEncoded(headers http.Header) bool {
+	header := headers.Get(contentEncodingHeader)
+	// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding
```
Comment (timoreimann) [inline middlewares/compress.go]: Why do we add this link here? I suppose it's to reference what constitutes an encoding?

If so, could we add an explaining comment? Something like "According to http://..., content is encoded if ...".

File: middlewares/compress_test.go [hunk 2]
```diff
@@ -0,0 +1,70 @@
...
+	}
+	rw := httptest.NewRecorder()
+
+	handler.ServeHTTP(rw, req, next)
+
+	assert.Equal(t, gzip, rw.Header().Get(contentEncodingHeader))
+	assert.Equal(t, acceptEncodingHeader, rw.Header().Get(varyHeader))
+
+	if bytes.Compare(rw.Body.Bytes(), baseBody) == 0 {
+		t.Errorf("got %v,\n expected a compressed body.", rw.Body.Bytes())
```
Comment (timoreimann) [inline middlewares/compress_test.go]: Mixture of testing and testify doesn't seem ideal. How about

`assert.True(t, bytes.Compare(rw.Body.Bytes(), baseBody) == 0)`

File: middlewares/compress_test.go [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+	}
+
+	rw := httptest.NewRecorder()
+	handler.ServeHTTP(rw, req, next)
+
+	assert.Equal(t, "", rw.Header().Get(contentEncodingHeader))
+	assert.Equal(t, "", rw.Header().Get(varyHeader))
+
+	assert.EqualValues(t, rw.Body.Bytes(), baseBody)
+}
```
Comment (timoreimann) [inline middlewares/compress_test.go]: The test seems structurally identical to `TestShouldCompressWhenNoContentEncodingHeader`. How about combining both in a table-driven test?

File: middlewares/compress_test.go (hunk 2 above)
Comment (ldez) [inline middlewares/compress_test.go]: If want to see the diff and if I do that I just see: `false` is different of `true`.
Testify doesn't provide `assert.NotEqualValues`, this is why I do that.

File: middlewares/compress_test.go (hunk 3 above)
Comment (ldez) [inline middlewares/compress_test.go]: I don't really want to do that.

File: middlewares/compress_test.go (hunk 2 above)
Comment (timoreimann) [inline middlewares/compress_test.go]: That's what the `msgAndArgs` final arguments to every testify assertion method are supposed to be used for. From [the docs](http://godoc.org/github.com/stretchr/testify/assert):

>Every assertion function also takes an optional string message as the final argument, allowing custom error messages to be appended to the message the assertion method outputs.

File: middlewares/compress_test.go (hunk 3 above)
Comment (timoreimann) [inline middlewares/compress_test.go]: Why not?

Comment (ldez) [inline middlewares/compress_test.go]: because it's not may way to test:
- I follow a Kent Beck rule about triangulation: I begin to thinking about a possible factorization if I repeat 3 times the same thing (the number 3, it's my limit, not a KB limit, but it's a very classic number for that with TDD)
- the tests are more flexible and more resistant to changes of the implementation.
- each test is independent and can be "recycle" (it's a testing strategy)
- the code in the test provide some limitation to be clearly factorize. (readability)
- table-driven test are not the only way to write good tests: each test case are different and we can use a lot of technique or approach.

File: middlewares/compress_test.go (hunk 2 above)
Comment (ldez) [inline middlewares/compress_test.go]: yes but I will see this:
```
Expected: True
Actual: False
Message: got XXX...
expected a compressed body YYY...
```
And I don't think it's a good test output.

I prefer mix stdlib and Testify, it's a better compromise for me.

File: middlewares/compress_test.go (hunk 3 above)
Comment (timoreimann) [inline middlewares/compress_test.go]: Hmm sorry, I find most of these arguments too general and abstract.

The flexibility point sounds like a bet into the future that only some parts of the tests will need to be adjusted. It could just as well be that a part common to both tests will need to be changed, so separate tests could be more costly. We don't know what part might change; we do know though that we can save lines and improve readability by taking a table-driven approach _now_, possibly changing again in the future.

So I don't agree but I neither bother too much as it's just about two tests. :-)

**Comment by tkisme** [comment]
still not work as expected
content-encoding:gzip

**Comment by kevinjqiu** [comment]
I'm expericing this issue too with 1.3.3. Bug report here https://github.com/containous/traefik/issues/1851
