### PR TITLE
Set a NopCloser request body with retry middleware

### LINKED ISSUE #1008: Traefik failing on POST request
### What version of Traefik are you using (`traefik version`)?
v1.1.2

### What is your environment & configuration (arguments, toml...)?
linux, simple file backend

[retry]

[backends]
[backends.testing]
[backends.testing.servers.server1]
url = "http://primary:80"
weight = 1
[backends.testing.servers.server2]
url = "http://backup:80"
weight = 1

### What did you do?
if the request is a POST request  and if the primary backend has failed, then traefik will retry the request to backup ( or vice-versa first backup then primary). 

### What did you expect to see?
Request being forwarded to another server and a response

### What did you see instead?
traefik fails to retry request and post data is destroyed. traefik  debug logs below

```
time="2016-12-31T10:50:50+01:00" level=warning msg="Error forwarding to http://primary:80, err: dial tcp primary:80: getsockopt: connection refused"
time="2016-12-31T10:50:50+01:00" level=debug msg="New attempt 2 for request: /api/adduser"
time="2016-12-31T10:50:50+01:00" level=warning msg="Error forwarding to http://backup:80, err: http: invalid Read on closed Body"
```

i have found out a similar case  here, please  have a look
https://github.com/flynn/flynn/issues/872

### PR DESCRIPTION
**Pull request by bamarni**
fixes #1008

### CODE REVIEW

**Comment by SantoDE** [comment]
Hey @bamarni ,

first of all, thanks for your contribution 👍 

I think it's fine for the moment. If we encounter an issue, where we encounter them send by upstream, we can still iterate over it. 

Could you please rebase your branch with the current master?

LGTM 👼 

/cc @containous/traefik

**Comment by bamarni** [comment]
Hi @SantoDE , you're welcome 😸 

> I think it's fine for the moment. If we encounter an issue, where we encounter them send by upstream, we can still iterate over it.

At the moment this would be supported, as the body is buffered and seeked to the beginning, in case of an upstream error where the body could have been read already it would be reset correctly, however I'm not sure this is the best approach.

Maybe a cleaner solution would be to pass an explicit error handler to the oxy forwarder, which instead of passing the dial error in the http response would use the request context for example, then we would only retry for this specific error, what do you think?

**Comment by SantoDE** [comment]
Hi @bamarni ,

that would probably be even better! The oxy forwarder already supports passing it an error handler so why not? :-)

**Comment by bamarni** [comment]
Agreed, I'll check this out soon.

**Comment by bamarni** [comment]
@SantoDE : I've updated the PR and splitted it in 2 commits, please check their message description. The first one is about fixing #1008, the second is changing the retry logic to only catch network errors.

**Comment by SantoDE** [comment]
Hey @bamarni ,

sadly, you have to rebase again :( 

For your commits, I'm okay with splitting it in 2 commits, if the fixing commit has a reference to what it fixes in the message :-)

ping @containous/traefik

**Comment by bamarni** [comment]
sure, just rebased

**Comment by SantoDE** [comment]
Thanks. Now it looks really LGTM 👼 

/ping @containous/traefik

**Comment by trecloux** [comment]
LGTM 👍

File: middlewares/retry.go [hunk 1]
```diff
@@ -32,12 +33,19 @@ func NewRetry(attempts int, next http.Handler) *Retry {
...
+		defer body.Close()
+		r.Body = ioutil.NopCloser(body)
+	}
 	attempts := 1
 	for {
 		recorder := NewRecorder()
 		recorder.responseWriter = rw
 		retry.next.ServeHTTP(recorder, r)
-		if !isNetworkError(recorder.Code) || attempts >= retry.attempts {
+		if recorder.Error == nil || attempts >= retry.attempts {
```
Comment (emilevauge) [inline middlewares/retry.go]: @bamarni are you sure you only have network errors in there? Maybe I'm wrong but I don't see the filter anymore.

Comment (bamarni) [inline middlewares/retry.go]: Thanks for double checking. The previous filter was looking at response status as it's how the default oxy error handler sets it, but my error handler would pass the error as a new field in the recorder struct. If this field is not nil then it comes from the transport RoundTrip call, meaning it is a network error.

However what I'm not sure about is whether the next attempt would be properly forwarded to the next backend and not the same one, I guess this depends on the load balancer configuration? If it's a sticky session for instance retrying wouldn't really make sense.

Comment (emilevauge) [inline middlewares/retry.go]: >If this field is not nil then it comes from the transport RoundTrip call, meaning it is a network error.

I'm really not sure about that. In oxy, `err` is not null at multiple places:
- https://github.com/containous/oxy/blob/master/forward/fwd.go#L164
- https://github.com/containous/oxy/blob/master/forward/fwd.go#L198
- https://github.com/containous/oxy/blob/master/forward/fwd.go#L265
- https://github.com/containous/oxy/blob/master/forward/fwd.go#L278
- https://github.com/containous/oxy/blob/master/forward/fwd.go#L288

Comment (bamarni) [inline middlewares/retry.go]: Would you consider these as network errors too? At least from my pov, if the forwarder doesn't manage to send a request or get a proper response from upstream for whatever reason I'd see it as a network error, as opposed to a valid http response from upstream with a 5XX status code, which would currently be retried.

Shall I stick to the first commit and open an other issue to discuss about the exact behaviour we want for the retry feature?

Comment (emilevauge) [inline middlewares/retry.go]: >Would you consider these as network errors too?

Not all these errors are network errors. For example https://github.com/containous/oxy/blob/master/forward/fwd.go#L278.

Therefore, I think it would be better to revert to the old test `if !isNetworkError(recorder.Code) || attempts >= retry.attempts {` :)

Comment (bamarni) [inline middlewares/retry.go]: I've reverted it, however please note that it wouldn't change the behaviour for errors you're mentioning, they'd still lead to retries.

The errors I was tackling with this change are instead explicit http errors from upstream, to compare this according to [proxy_next_upstream](http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_next_upstream) semantics, currently the behaviour is : 

    error timeout http_502 http_504 non_idempotent

And with my changes it would be : 

    error timeout non_idempotent

The motivation behind this is that imo `http_5XX + non_idempotent` is a bit aggressive for a default. If upstream sends http 504 for a POST request it still might have altered a resource but didn't manage to serve the response in a timely manner, and retrying might not be the best option, at least hard to assume. Maybe even `non_idempotent` shouldn't be by default? Or the retry behaviour should be configurable?

**Comment by bamarni** [comment]
It seems like there are random failures in the build 😿  For example mine failed on `TestAccessLog`, which contains this code : https://github.com/containous/traefik/blob/009057cb87db4a0991909c9c813c0819a3d63e18/integration/access_log_test.go#L37

There are multiple places with this kind of random wait period in the test suite, which are subject to failures. How about introducing generic helpers, for example `utils.WaitTcp(addr, timeout)` instead of hardcoding a time period?

**Comment by emilevauge** [comment]
@bamarni 
Yeah we know... We will refactor tests in the next release.

**Comment by bamarni** [comment]
@emilevauge : cool, let me know if you need extra help. As per this PR I've rebased it.
