### PR TITLE
Fix Kubernetes watch SSL & empty schema

### LINKED ISSUE #332: Kubernetes Watch bug
The watch request dont include the ca.crt ? 

```
Error watching kubernetes events: failed to create watch failed to make request: GET \"https://10.3.0.1:443/apis/extensions/v1beta1/ingresses?watch&resourceVersion=2445422\": Get https://10.3.0.1:443/apis/extensions/v1beta1/ingresses?resourceVersion=2445422&watch=: x509: certificate signed by unknown authority
```

can you reproduce that ? ( Kube 1.2.2 )

Logs -> http://pasted.co/18838070

### LINKED ISSUE #333: Kubernetes scheme bug
Some of my service as shown as ://x.x.x.x:80  and traefik fail 

you can check the logs http://pasted.co/18838070

### PR DESCRIPTION
**Pull request by emilevauge**
This PR fixes Kubernetes watch SSL, and Kubernetes empty schema.
The new schema rule is:

- if `port.Name` is not empty, use it as protocol
- else if `port` = 443, schema is `https` 
- else schema is `http`

Fixes #332 
Fixes #333 

Signed-off-by: Emile Vauge <emile@vauge.com>

### CODE REVIEW

File: provider/k8s/client.go [hunk 1]
```diff
@@ -225,34 +223,35 @@ func (c *clientImpl) watch(url string, stopCh <-chan bool) (chan interface{}, ch
...
-		conn, err := net.Dial(network, addr)
-		if err != nil {
-			return nil, err
-		}
-		// No timeout for long-polling request
-		conn.SetDeadline(time.Now())
-		return conn, nil
-	}
-	req, err := request.TLSClientConfig(c.tls).MakeRequest()
+	// request.Transport.Dial = func(network, addr string) (net.Conn, error) {
```
Comment (vdemeester) [inline provider/k8s/client.go]: @emilevauge why not removing it all together instead of leaving it commented out ? :angel:

Comment (emilevauge) [inline provider/k8s/client.go]: Removed ;)

File: provider/kubernetes.go [hunk 2]
```diff
@@ -170,10 +170,16 @@ func (provider *Kubernetes) loadIngresses(k8sClient k8s.Client) (*types.Configur
...
+					protocol := "http"
 					for _, port := range service.Spec.Ports {
 						if port.Port == pa.Backend.ServicePort.IntValue() {
-							protocol = port.Name
+							if len(port.Name) == 0 {
+								if port.Port == 443 {
+									protocol = "https"
+								}
+							} else {
+								protocol = port.Name
```
Comment (mgoodness) [inline provider/kubernetes.go]: [ServicePort names must be unique](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_serviceport), so this will fail if there multiple ports that use the same scheme.

```
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wip
    branch: andy
    environment: stage
  name: wip-stage-test
spec:
  ports:
    - name: http
      port: 80
    - name: http-alt
      port: 8080
    - name: https
      port: 443
    - name: https-alt
      port: 6443
  selector:
    app: wip
    branch: andy
    environment: stage
```

Comment (emilevauge) [inline provider/kubernetes.go]: Yeah, I know, but I don't know how to do it otherwise...
By default it's http, https with 443. And you can override it with name.
Do I keep it like that?

Comment (mgoodness) [inline provider/kubernetes.go]: Would it make sense to use the Ingress object instead of the Service to determine the protocol? ServicePorts can be named arbitrarily, while the IngressSpec states that SSL is only supported on port 443. All others are http.

Comment (emilevauge) [inline provider/kubernetes.go]: Finally, 443=>https, else http ;)

**Comment by mgoodness** [comment]
LGTM

**Comment by vdemeester** [comment]
LGTM :sun_with_face:
