### PR TITLE
Fix ACME certificate for wildcard and root domains

### LINKED ISSUE #3468: LetsEncrypt DNS-01 fails when mixing domains with wildcard subdomains.
This may be a bug with ACME, but I'm not technical enough to know, and I'm using Traefik, so reporting it here.

### Do you want to request a *feature* or report a *bug*?
Bug

### What did you do?
I'm using the traefik docker image. I configured and run it, and immediately the certificates are rejected _only when mixing wildcard domains_.

### What did you expect to see?
Wildcard subdomains to be allowed.

### What did you see instead?
```
time="2018-06-10T21:15:43Z" level=error msg="Unable to obtain ACME certificate for domains \"*.EVERYDOMAIN.com,EVERYDOMAIN.com\" : cannot obtain certificates: acme: Error -> One or more domains had a problem:\n[EVERYDOMAIN.com] acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Incorrect TXT record \"HASH HERE\" found at _acme-challenge.EVERYDOMAIN.com\n"
```
Points of interest:
This only happens if the wildcard domains is listed with the main domain.
Setting a delay of 5s did not fix this.
It is apparently able to set the TXT record; I'm not getting a permission error.
I believe the provider (Cloudflare) has to verify that TXT record is set before ACME even checks?

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.6.3
Codename:     tetedemoine
Go version:   go1.10.2
Built:        2018-06-05_03:29:01PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
```toml
defaultEntryPoints = ["http", "https"]

[acme]
  email = "..."
  entryPoint = "https"
  onHostRule = true
  storage = "acme.json"
  [acme.dnsChallenge]
    delayBeforeCheck = 0
    provider = "cloudflare"

[[acme.domains]]
  main = "*.MYDOMAIN.com"
  sans = ["MYDOMAIN.com"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
    [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]

[web]
  address = ":8080"
  [web.auth.basic]
    users = ["..."]
```

The environment has cloudflare email and cloudflare api key in it.

When I set the wildcard subdomains to be their own `main` entry and the domain to be its own `main` entry, it works without error.

### PR DESCRIPTION
**Pull request by nmengin**
### What does this PR do?

This Pull Request introduces a mechanims which allow retrying to generate a ACME certificate when a `DNSChallenge` failed to obtain a certificate for both wildcard and root domain.

### Motivation

Since the feature which allows Træfik users to generate ACME certificates for both wildcard domain (as CN) and root domain (as SAN), a flaky behavior is noted.

Sometimes everything works well, sometines challenges cannot be solved with different errors (TXT record missing or incorrect).
These errors exist for almost all the DNS providers.

Fixes #3468, #3445.

### More

- [x] Added/updated tests

### Additional Notes

A first analysis showed that **the problem is due to the name of the TXT records** needed by Let's Encrypt: a wildcard domain and its root domain are challenged thanks to a TXT record with the same name. In function of the TTL given to the TXT records, it was unable to Let's Encrypt the get all the values asked in the allowed time.

After analyzed deeply the problem (and made some tests), it appears that **the problem is due to the time to propagate a TXT record creation/deletion/update** in the DNS provider infrastructure.

Indeed, LEGO makes a pre-check on all the TXT records before to ask Let's Ecrypt to do the challenge. But, sometimes, the result caught by LEGO and the other one caught by Let's Encrypt are differents (it's maybe due to the time to propagate the modifications into all the DNS provider infrastructure).

The modification introduced by this PR allows Træfik to retry to obtain a ACME certificate for a wildcard and its root domain when errors happens.

**The retry works because Let's Encrypt does not ask to challenge twice the same domain**.
Thus, if during the first iteration the wildcard is successfully checked, during the second iteration only the root domain will be checked.

### CODE REVIEW

File: provider/acme/provider.go [hunk 1]
```diff
@@ -368,6 +389,53 @@ func (p *Provider) resolveCertificate(domain types.Domain, domainFromConfigurati
...
 
+func (p *Provider) useBackOffToObtainCertificate(domains []string) bool {
+	// Check if we can use a backoff only if we use the DNS Challenge and if is there are at least 2 domains to check
+	if p.DNSChallenge != nil && len(domains) > 1 {
+		rootDomain := ""
+		for i := 0; i < len(domains); i++ {
+			// Search a wildcard domain if not already found
+			if len(rootDomain) == 0 && strings.HasPrefix(domains[i], "*.") {
+				rootDomain = strings.TrimPrefix(domains[i], "*.")
+				// Restart to the first indfex to check id the root domain of the wildcard domain exists
```
Comment (Juliens) [inline provider/acme/provider.go]: indfex/index

File: provider/acme/provider.go [hunk 2]
```diff
@@ -368,6 +389,53 @@ func (p *Provider) resolveCertificate(domain types.Domain, domainFromConfigurati
 	return certificate, nil
 }
 
+func (p *Provider) useBackOffToObtainCertificate(domains []string) bool {
+	// Check if we can use a backoff only if we use the DNS Challenge and if is there are at least 2 domains to check
+	if p.DNSChallenge != nil && len(domains) > 1 {
+		rootDomain := ""
+		for i := 0; i < len(domains); i++ {
```
Comment (emilevauge) [inline provider/acme/provider.go]: `for i := range domains` instead?

download

File: provider/acme/provider.go [hunk 3]
```diff
@@ -368,6 +389,53 @@ func (p *Provider) resolveCertificate(domain types.Domain, domainFromConfigurati
...
+		return err
+	}
+
+	notify := func(err error, time time.Duration) {
+		log.Errorf("Error obtaining certificate retrying in %s", time)
+	}
+
+	ebo := backoff.NewExponentialBackOff()
+	// Give the time to LEGO to try to solve the challenge twice
+	ebo.MaxElapsedTime = 2 * timeout
```
Comment (emilevauge) [inline provider/acme/provider.go]: Not sure about this, maybe use `WithMaxRetries` instead ?

File: provider/acme/provider.go (hunk 2 above)
Comment (nmengin) [reply provider/acme/provider.go]: @emilevauge I used the old way to iterate on a slice in the way to use only one `loop` statement for the two operations I have to to on the slice.

I was not aware about the possible issues you mentionned, I am going to change the code.

File: provider/acme/provider.go [hunk 4]
```diff
@@ -246,6 +249,17 @@ func (p *Provider) getClient() (*acme.Client, error) {
 		if err != nil {
 			return nil, err
 		}
+
+		// Set the precheck timeout into the DNSChallenge provider
+		switch provider := provider.(type) {
```
[the remark this answers is not in the document]
Comment (emilevauge) [reply provider/acme/provider.go]: Isn't this working `if cpt, ok := provider.(acme.ChallengeProviderTimeout); ok {` instead ?

**Comment by A-Shleifman** [comment]
Hi @nmengin,

I'm afraid the problem is not fixed yet. I'm running traefik in a docker container based on `traefik:1.7-alpine`. The actual version is `v1.7.0-rc3`. Tried to generate wildcard certificates for two domains and got the same `incorrect TXT record` error:

[traefik.log](https://github.com/containous/traefik/files/2288598/traefik.log)

I'm using `cloudflare`.

_.txt as github doesn't allow .toml files_
[traefik.toml.txt](https://github.com/containous/traefik/files/2288607/traefik.toml.txt)

Any ideas what could be causing this?

**Comment by A-Shleifman** [comment]
Update: Certificates are generated for domains using `route53` provider, but the error appears when using `cloudflare`

**Comment by BirkhoffLee** [comment]
You should raise a new issue

**Comment by nmengin** [comment]
Hello @A-Shleifman ,

Many thanks fro your feedback.

I guess the problem comes from the paramtrization of the cloudflare provider into LEGO :+1: 
The TTL and the check timeout are equals (120s) that's why even if we try twice the problem persists.

I'll try to find another solution when I'll be back at the office (monday).

Can you open a new issue as @BirkhoffLee suggested please?

**Comment by A-Shleifman** [comment]
Done => #3761 :)

**Comment by pwaldon** [comment]
Hello,

with the latest build (codename: maroilles) and NS1 provider I started to get new errors. Is this somehow related?

config:
```toml
[[acme.domains]]
  main = "*.abc.com"
  sans = ["abc.com"]
```

```bash
traefik          | time="2018-08-19T05:43:50Z" level=info msg="legolog: [INFO] acme: Registering account for test@abc.com"
traefik          | time="2018-08-19T05:43:51Z" level=info msg="legolog: [INFO] [*.abc.com] acme: Obtaining bundled SAN certificate"
traefik          | time="2018-08-19T05:43:51Z" level=info msg="legolog: [INFO] [*.abc.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/..."
traefik          | time="2018-08-19T05:43:51Z" level=info msg="legolog: [INFO] [abc.com] acme: Trying to solve DNS-01"
traefik          | time="2018-08-19T05:43:51Z" level=error msg="Unable to obtain ACME certificate for domains \"*.abc.com\" : unable to generate a certificate for the domains [*.abc.com]: acme: Error -> One or more domains had a problem:\n[abc.com] error presenting token: dns: domain must be fully qualified\n"
```

**Comment by nmengin** [comment]
Hello @pwaldon ,

Many thanks for your interest in the project.

Your problem does not seem to be related to this issue.

If you need more help, please join our [Slack workspace](https://traefik.herokuapp.com/) for more [community #support](https://traefik.slack.com/messages/C0CDT22PJ/).

**Comment by chris-aeviator** [comment]
without setting timeout to >90 sec, I'm getting this behavior with Gandi V5 trying to issue a wildcard cert with traefik

traefik:
```
Gandi DNS: DNS Record Created
Gandi DNS: Zone record deleted
Gandi DNS: DNS Record Created
Gandi DNS: Zone record deleted
time="2018-09-18T21:47:29Z" level=error msg="Unable to obtain ACME certificate for domains \"**.domain.com, domain.com\" : cannot obtain certificates: acme: Error -> One or more domains had a problem:\n[domaincom] acme: Error 403 - urn:ietf:params:acme:error:unauthorized - Incorrect TXT record \"QEpHmVXXXXXXXcz0Au3ZrFphtXFMKZrkdCM\" found at _acme-challenge.domain.com\n"
Gandi DNS: DNS Record Created

```
traefik.toml
```
defaultEntryPoints = ["http", "https"]

[web]
# Port for the status page
address = ":8080"

# Entrypoints, http and https
[entryPoints]
  # http should be redirected to https
  [entryPoints.http]
  address = ":80"
    #[entryPoints.http.redirect]
    #entryPoint = "https"
  # https is the default
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[retry]

# Enable ACME (Let's Encrypt): automatic SSL
[acme]
# Email address used for registration
email = "chris@domain.io"
storageFile = "acme.json"
entryPoint = "https"
onDemand = false
onHostRule = false
# Use a HTTP-01 acme challenge rather than TLS-SNI-01 challenge
#[acme.httpChallenge]
#entryPoint = "http"

caServer = "https://acme-v02.api.letsencrypt.org/directory"

# optional but recommend
#[acme.tlsChallenge]

  [acme.dnsChallenge]
    provider = "gandiv5"
    delayBeforeCheck = 91

  [[acme.domains]]
    main = "*.domain.com"
    sans = ["domain.com"]
# Enable Docker configuration backend
[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.com"
watch = true
exposedbydefault = false
[api]
  entryPoint = "traefik"
  dashboard = true
  [api.statistics]
    recentErrors = 10

```
