### PR TITLE
acme: prevent some malformed errors.

### LINKED ISSUE #4011: Malformed ACME identifiers with trailing period
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

N/A - I'm an employee of Let's Encrypt and noticed in our server-side logs that Traefik (versions 1.6.4 ... 1.7.2.) are responsible for a large portion of the `"urn:ietf:params:acme:error:malformed"` type error responses to newOrder requests. The majority of these have the detail message `"Error creating new order :: DNS name ends in a period"` indicating there is probably a common mis-configuration at work Traefik might be able to address.

### What did you expect to see?

The Traefik user-agent not being a dominant source of malformed errors in our logs :-)

### What did you see instead?

Many malformed errors being returned to Traefik users indicating that a newOrder request was received containing identifiers with a trailing period character, not a valid domain name.

I expect this is a result of browsers/HTTPS user-agents sending a request to a domain with a trailing period backed by a Traefik instance that doesn't strip the trailing period before creating an order with Lego/Let's Encrypt. It probably makes sense for Traefik to be responsible for stripping that trailing period instead of handling that corner-case in Lego.

### Output of `traefik version`: (_What version of Traefik are you using?_)

N/A, in the last 3 days of logs I see versions 1.6.4 through 1.7.2 represented.

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

N/A

### If applicable, please paste the log output in DEBUG level (`--logLevel=DEBUG` switch)

N/A

### PR DESCRIPTION
**Pull request by ldez**
### What does this PR do?

Prevent some malformed errors.

### Motivation

Not being a dominant source of malformed errors in Let's Encrypt logs.

Fixes #4011

### More

- [-] Added/updated tests
- [-] Added/updated documentation

### CODE REVIEW

File: provider/acme/provider.go [hunk 1]
```diff
@@ -762,8 +761,16 @@ func (p *Provider) getValidDomains(domain types.Domain, wildcardAllowed bool) ([
...
+	var cleanDomains []string
+	for _, domain := range domains {
+		canonicalDomain := types.CanonicalDomain(domain)
+		cleanDomain := acme.UnFqdn(canonicalDomain)
+		if canonicalDomain != cleanDomain {
+			log.Warnf("FQDN detected, please remove the trailing dot: %s", canonicalDomain)
+		}
+		cleanDomains = append(cleanDomains, cleanDomain)
+	}
+	return cleanDomains, nil
```
Comment (mmatur) [inline provider/acme/provider.go]: Could you please add a new line before
