### PR TITLE
Fix rancher host IP address

### LINKED ISSUE #1498: [Rancher] No IP in backend in host networking mode
### Do you want to request a *feature* or report a *bug*?
Bug. Appears to be the same as #487 except for Rancher (I even ran into it setting up Home Assistant as well).

### What did you do?
Set up Traefik with Rancher backend for a container with net=host.

### What did you expect to see?
IP address in backend

### What did you see instead?
IP address is missing

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.2.3
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in debug mode (`--debug` switch)

```
(paste your output here)
```

### PR DESCRIPTION
**Pull request by matq007**
### Description

Until now traefik was setting up `PrimaryIpAddress` which is only set for managed network. When host network is chosen, traefik has to setup the IP address of the host machine where the container is running. As shown on the picture below `ghot-1` is on **host** network and `ghot` is on **managed** network.

github

Fixes  #1498

### CODE REVIEW

**Comment by ldez** [comment]
Thanks for your contribution 👍 

Could you change the  base branch of this PR from `master` to `v1.4` ?

Is there an already open issue about this problem?

**Comment by matq007** [comment]
Sure thing @ldez. No. Should I make an issue for it?

**Comment by ldez** [comment]
No need to open a new issue.

It's not related to #1498 ?

**Comment by matq007** [comment]
Oh right. I forgot about that. That's the one! :)

**Comment by ldez** [comment]
Could you rebase your PR on the `v1.4` branch?

```shell
git rebase upstream/v1.4
```

with:
```shell
git remote -v

origin	git@github.com:matq007/traefik.git (fetch)
origin	git@github.com:matq007/traefik.git (push)
upstream	git@github.com:containous/traefik.git (fetch)
upstream	git@github.com:containous/traefik.git (push)
```

File: provider/rancher/api.go [hunk 1]
```diff
@@ -10,10 +10,12 @@ import (
 	"github.com/containous/traefik/log"
 	"github.com/containous/traefik/safe"
 	"github.com/containous/traefik/types"
+	"github.com/mitchellh/mapstructure"
 	rancher "github.com/rancher/go-rancher/client"
 )
 
 const labelRancheStackServiceName = "io.rancher.stack_service.name"
+const hostNetwork = "host"
```
Comment (nmengin) [inline provider/rancher/api.go]: Can you use a `const` block?

Comment (matq007) [reply provider/rancher/api.go]: Sure thing, on it right now :)

Comment (matq007) [reply provider/rancher/api.go]: Could you please rebase it again to 1.4 branch?

**Comment by ldez** [comment]
@matq007 please do:
```shell
git checkout master
git branch -D fix-rancher-host
git checkout origin fix-rancher-host
```
