### PR TITLE
Maintain sticky flag on LB method validation failure.

### LINKED ISSUE #1568: Enabled sticky sessions flag not effective when load-balancing method is missing or invalid.
Hello!

The documentation on stickiness on https://docs.traefik.io/basics/ says:
```
Sticky sessions are supported with both load balancers. When sticky sessions are enabled, a cookie called _TRAEFIK_BACKEND is set on the initial request. On subsequent requests, the client will be directed to the backend stored in the cookie if it is still healthy. If not, a new backend will be assigned.
```
and I guess this is not correct anymore. If I leave the default (wrr) I don't receive a loadbalancing cookie in the browser when setting sticky = true. It is only working when method = "drr".

Also, but maybe I'am wrong, I thought that there was an indicator on the web ui which was indicating that stickiness is enabled?

traefik-web-sticky

### Output of `traefik version`: (_What version of Traefik are you using?_)
Version:      v1.2.3
Codename:     morbier
Go version:   go1.7.5
Built:        2017-04-13_07:32:59PM
OS/Arch:      linux/amd64

### PR DESCRIPTION
**Pull request by timoreimann**
We previously did not copy the sticky flag if the load-balancer method validation failed, causing enabled stickiness to be dropped in case of a validation error (which, technically, for us is the same as a load-balancer configuration without an explicitly set method). This change fixes that.

A few refactorings and improvements along the way:

- Move the frontend and backend configuration steps into separate   methods/functions for better testability.
- Include the invalid method name in the error value and avoid log   duplication.
- Add tests for the backend configuration part.

Fixes #1568.

### CODE REVIEW

**Comment by timoreimann** [comment]
@containous/traefik FYI.

/cc @ kleinsasserm.

File: server/server.go [hunk 1]
```diff
@@ -887,3 +876,25 @@ func sortedFrontendNamesForConfig(configuration *types.Configuration) []string {
...
+}
+
+func configureBackends(backends map[string]*types.Backend) {
+	for backendName, backend := range backends {
+		_, err := types.NewLoadBalancerMethod(backend.LoadBalancer)
+		if err != nil {
+			log.Debugf("Validation of load balancer method for backend %s failed: %s. Using default method wrr.", backendName, err)
+			backend.LoadBalancer = &types.LoadBalancer{
+				Method: "wrr",
+				Sticky: backend.LoadBalancer.Sticky,
```
Comment (timoreimann) [inline server/server.go]: Effectively, this should be the only addition to the production code.

**Comment by timoreimann** [comment]
Integration tests keep failing. Not exactly sure why, will have to investigate.

File: server/server.go [hunk 2]
```diff
@@ -887,3 +876,25 @@ func sortedFrontendNamesForConfig(configuration *types.Configuration) []string {
...
+func (server *Server) configureFrontends(frontends map[string]*types.Frontend) {
+	for _, frontend := range frontends {
+		// default endpoints if not defined in frontends
+		if len(frontend.EntryPoints) == 0 {
+			frontend.EntryPoints = server.globalConfiguration.DefaultEntryPoints
+		}
+	}
+}
+
+func configureBackends(backends map[string]*types.Backend) {
```
Comment (ldez) [inline server/server.go]: why not `func (server *Server) configureBackends`?

Comment (timoreimann) [inline server/server.go]: Because the backend configuration requires nothing from `server` for now.

Comment (emilevauge) [inline server/server.go]: I also find this a bit odd to be honest ^^

Comment (timoreimann) [inline server/server.go]: I can turn it into a receiver method if you really want to, but it would carry the wrong message to the reader (and my IDE's "find usage" function) that `server` is somehow needed for this method to work properly, which it isn't. It also makes things like testing more complicated.

Effectively, it'd be similar to passing an unused variable to a function call.

Comment (emilevauge) [inline server/server.go]: @timoreimann I think there is at least 2 reasons to add `func (server *Server)` to both functions:

1. it's homogeneous (to the reader, it would be easier to understand if `configureFrontends` and `configureBackends` add the same signature)
2. we could only call `configureBackends` if we had a reference to a `Server` which is makes more sense

Comment (timoreimann) [inline server/server.go]: Okay, converted `configureBackends` into a method.

PTAL again.

File: server/server.go [hunk 3]
```diff
@@ -887,3 +876,29 @@ func sortedFrontendNamesForConfig(configuration *types.Configuration) []string {
...
+func (server *Server) configureFrontends(frontends map[string]*types.Frontend) {
+	for _, frontend := range frontends {
+		// default endpoints if not defined in frontends
+		if len(frontend.EntryPoints) == 0 {
+			frontend.EntryPoints = server.globalConfiguration.DefaultEntryPoints
+		}
+	}
+}
+
+func (*Server) configureBackends(backends map[string]*types.Backend) {
```
Comment (emilevauge) [inline server/server.go]: :heart:
