### PR TITLE
Uses both binded HostIP and HostPort when useBindPortIP=true

### LINKED ISSUE #3622: docker.UseBindPortIP ignored
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Created traefik.toml file containing;
```toml
[docker]
   endpoint = "unix:///var/run/docker.sock"
   domain = "xxxxxxxxxxxxxxxxxxxx"
   exposedbydefault = true
   watch = true
   usebindportip = true
```

Configured docker container as
```yml
service:
    test:
        image: xxxxxx
         ports:
             -  192.168.0.10:8080:8080
```

### What did you expect to see?

In traefik dashboard - backend for `test` should be `192.168.0.10:8080`

### What did you see instead?

in traefik dashboard - backend for `test` was `172.18.0.2:8080`

### Output of `traefik version`: (_What version of Traefik are you using?_)
```
Version:      v1.6.5
Codename:     tetedemoine
Go version:   go1.10.3
Built:        2018-07-10_03:54:03PM
OS/Arch:      linux/amd64
```

Assuming I was using the option usebindportip incorrectly, I jumped into the source and added some diagnostics, what I found was that the bound ports returned by docker were `8080/tcp` and the `docker/config.go`  was performing a case sensitive comparison against `port+"/TCP"`.   This resulted in no bound ports ever matching.

Once I fixed this, and the ports matched, all containers which did not explicitly include port IP bindings inherited the ip address `0.0.0.0` which would not work.

The following fixes both problems; starting at https://github.com/containous/traefik/blob/dbe720f0f10369d60fd8a81f2d62bfd33db4fa99/provider/docker/config.go#L240-L244

```diff
       if strings.EqualFold(string(netPort), port+"/TCP") || strings.EqualFold(string(netPort), port+"/UDP") {
                  for _, p := range portBindings {
~                     if p.HostIP != "0.0.0.0" {
+                         return p.HostIP
+                     }
        
```

This ensures the comparison is not case sensitive, and ports without an explicit HostIP get the correct IP.

Note that fixes my current issue, however once the 'useportbindip' works, you have a new issue;

The following docker compose fragment;
```yml
service:
    test:
        image: xxxxxx
         ports:
             -  192.168.0.10:8080:8080
```
results in a backend pointing to `192.168.0.10:8080` (assuming the aforementioned patch) which is correct.

The following docker compose fragment;
```yml
service:
    test:
        image: xxxxxx
         ports:
             -  192.168.0.10:80:8080
```
also results in a backend pointing to `192.168.0.10:8080` which is no longer correct.

When `UsePortBindIP` is active, and an alternative `BindIP` is found, it must use the associated bound port, not the internal port.

Note that adding the label
```yml
       labels:
          - traefik.port=80
```
resulted in a backend pointing to `172.18.0.2:80` which I assume is because it could not find an existing port 80 in the set of bound ports since it only looks at the internal port value, not the mapped port value.

Tracking this down was beyond what I could do in the time I had.

Kind Regards
David

### PR DESCRIPTION
**Pull request by geraldcroes**
### What does this PR do?

Context: docker provider with usebindportip

Currently:
- Traefik doesn't find the port bindings when the API responds in lowercase.
- When the API responds in uppercase, Traefik uses the external IP only, and not the port
- When no IP is specified, Traefik creates a route using the IP 0.0.0.0
- When the label `traefik.port`is specified, it is used both for selecting the binding _and_ in the route

This PR: 
- ignores the case when looking for port bindings
- takes the external IP _and_ port into account to create the routes
- excludes servers with no binding
- excludes servers with no IP specified in the binding (0.0.0.0)
- the label `traefik.port` is used to select the binding (which enables the use of segments)

To sum it up:

| label                  | Binding      | Routes to |
|----------------|------------|-----------|
| `traefik.port` not set | `IP_E1:P_E1:P_I1` | `IP_E1:P_E1` |
| `traefik.port` not set | `P_E1:P_I1` | Warning & Ignored (cannot route to `0.0.0.0`) |
| `traefik.port` not set | None | Warning & Ignored (Binding is missing) |
| `traefik.port=P_I1` | `IP_E1:P_E1:P_I1` | `IP_E1:P_E1` |
| `traefik.port=P_I2` | `IP_E1:P_E1:P_I1` | Warning  & Ignored (cannot find binding for `XX:XX:P_I2`) |
| `traefik.port=P_I2`  | `IP_E1:P_E1:P_I1` & `IP_E2:P_E2:P_I2` | `IP_E2:P_E2` |
| `traefik.port=P_I1`  | None | Warning & Ignored (Binding is missing) |

### Motivation

Fixes #3622 

(kudos to @systemmonkey42 for the awesome description in the issue) 

### More

- [x] Added/updated tests
- [ ] Added/updated documentation

### Examples 

<details>
<summary>docker-compose.yml</summary>

```yml
version: '3'

services:
  whoami-1:
    image: emilevauge/whoami
    ports:
      -  xx.xx.xx.xx:8082:80 # Routes to XX.XX.XX.XX:8082
    labels: 
      - traefik.enable=true
      - traefik.backend=whoami
      - "traefik.frontend.rule=PathPrefix:/whoami-1"

  whoami-2:
    image: emilevauge/whoami
    ports:
      -  8083:80 # Warning Cannot determine the IP address (got 0.0.0.0) for the container "/issue_3622_whoami-2_1": ignoring server 
    labels: 
      - traefik.enable=true
      - traefik.backend=whoami-2
      - "traefik.frontend.rule=PathPrefix:/whoami-2"

  whoami-3:
    image: emilevauge/whoami
    # Warning Unable to find a binding for the container "/issue_3622_whoami-3_1": ignoring server
    labels: 
      - traefik.enable=true
      - traefik.backend=whoami-3
      - "traefik.frontend.rule=PathPrefix:/whoami-3"
  
  whoami-4:
    image: emilevauge/whoami
    ports:
      -  xx.xx.xx.xx:8085:80 # routes to XX:XX:XX:XX:8085
    labels:
      - traefik.port=80
      - traefik.enable=true
      - traefik.backend=whoami-4
      - "traefik.frontend.rule=PathPrefix:/whoami-4"

  whoami-5:
    image: emilevauge/whoami
    ports:
      -  xx.xx.xx.xx:8086:80 # Warning Unable to find a binding for the container "/issue_3622_whoami-5_1": ignoring server
    labels:
      - traefik.port=81
      - traefik.enable=true
      - traefik.backend=whoami-5
      - "traefik.frontend.rule=PathPrefix:/whoami-5"

  whoami-6:
    image: emilevauge/whoami
    ports:
      -  xx.xx.xx.xx:8087:80
      -  xx.xx.xx.xx:8088:81 # routes to xx.xx.xx.xx:8088
    labels:
      - traefik.port=81
      - traefik.enable=true
      - traefik.backend=whoami-6
      - "traefik.frontend.rule=PathPrefix:/whoami-6"

  whoami-7:
    image: emilevauge/whoami
    # Warning Unable to find a binding for the container "/issue_3622_whoami-7_1": ignoring server
    labels:
      - traefik.port=81
      - traefik.enable=true
      - traefik.backend=whoami-7
      - "traefik.frontend.rule=PathPrefix:/whoami-7"
```

</details>

<details>
<summary>traefik/api</summary>

```json
{
  "docker": {
    "backends": {
      "backend-whoami": {
        "servers": {
          "server-issue-3622-whoami-1-1-7c60b6958b968de9998659c11d7406a0": {
            "url": "http://xx.xx.xx.xx:8082",
            "weight": 1
          }
        },
      },
      "backend-whoami-4": {
        "servers": {
          "server-issue-3622-whoami-4-1-5dcf432359cd6ad04e1779a85d45314a": {
            "url": "http://xx.xx.xx.xx:8085",
            "weight": 1
          }
        },
      },
      "backend-whoami-6": {
        "servers": {
          "server-issue-3622-whoami-6-1-554f0078ab3c259e14fc03848f9f8ce4": {
            "url": "http://xx.xx.xx.xx:8088",
            "weight": 1
          }
        },
      }
    },
  }
}
```
</details>

### CODE REVIEW

File: provider/docker/config.go [hunk 1]
```diff
@@ -322,22 +311,49 @@ func getPort(container dockerData) string {
 	return ""
 }
 
+func (p *Provider) getPortBinding(container dockerData) (nat.PortBinding, error) {
```
Comment (ldez) [inline provider/docker/config.go]: could you return a pointer (`*nat.PortBinding`) instead of a struct?

File: provider/docker/config.go [hunk 2]
```diff
@@ -322,22 +311,49 @@ func getPort(container dockerData) string {
...
+	port := getPort(container)
+	for netPort, portBindings := range container.NetworkSettings.Ports {
+		if strings.EqualFold(string(netPort), port+"/TCP") || strings.EqualFold(string(netPort), port+"/UDP") {
+			for _, p := range portBindings {
+				return p, nil
+			}
+		}
+	}
+
+	return nat.PortBinding{HostIP: "", HostPort: ""}, fmt.Errorf("Unable to find the external IP:Port for the container %q", container.Name)
```
Comment (ldez) [inline provider/docker/config.go]: return nil.

https://github.com/golang/go/wiki/CodeReviewComments#error-strings
```go
fmt.Errorf("unable to find the external IP:Port for the container %q", container.Name)
```

File: provider/docker/config.go [hunk 3]
```diff
@@ -322,22 +311,49 @@ func getPort(container dockerData) string {
...
-		if len(ip) == 0 {
-			log.Warnf("Unable to find the IP address for the container %q: the server is ignored.", container.Name)
-			continue
+		var ip, port string
+
+		if p.UseBindPortIP {
+			portBinding, err := p.getPortBinding(container)
+			if err != nil {
+				log.Warnf("Unable to find a binding for the container %q: ignoring server", container.Name)
+				continue
```
Comment (ldez) [inline provider/docker/config.go]: could you create a function that returns an error to replace the `continue`

File: provider/docker/config.go [hunk 4]
```diff
@@ -322,22 +311,49 @@ func getPort(container dockerData) string {
...
+			}
+			if portBinding.HostIP != "0.0.0.0" {
```
Comment (ldez) [inline provider/docker/config.go]: fail fast: could you invert the condition:
```go
if portBinding.HostIP == "0.0.0.0" {
// ...
}
// ...
```
The `else` is not needed.

File: provider/docker/config.go [hunk 5]
```diff
@@ -347,6 +363,9 @@ func (p *Provider) getServers(containers []dockerData) map[string]types.Server {
 			continue
 		}
 
+		if servers == nil {
+			servers = make(map[string]types.Server)
```
Comment (ldez) [inline provider/docker/config.go]: the map initialization must be done before.

File: provider/docker/deprecated_config.go [hunk 6]
```diff
@@ -19,10 +19,10 @@ func (p *Provider) buildConfigurationV1(containersInspected []dockerData) *types
 		"isBackendLBSwarm": isBackendLBSwarm,
 
 		// Backend functions
-		"getIPAddress": p.getIPAddress,
-		"getPort":      getPortV1,
-		"getWeight":    getFuncIntLabelV1(label.TraefikWeight, label.DefaultWeight),
-		"getProtocol":  getFuncStringLabelV1(label.TraefikProtocol, label.DefaultProtocol),
+		"getDeprecatedIPAddress": p.getDeprecatedIPAddress,
```
Comment (mmatur) [inline provider/docker/deprecated_config.go]: Should be `"getIPAddress"` instead of `"getDeprecatedIPAddress"`

File: provider/docker/config.go [hunk 7]
```diff
@@ -33,13 +33,13 @@ func (p *Provider) buildConfigurationV2(containersInspected []dockerData) *types
...
 
 		// Backend functions
-		"getIPAddress":      p.getIPAddress,
-		"getServers":        p.getServers,
-		"getMaxConn":        label.GetMaxConn,
-		"getHealthCheck":    label.GetHealthCheck,
-		"getBuffering":      label.GetBuffering,
-		"getCircuitBreaker": label.GetCircuitBreaker,
-		"getLoadBalancer":   label.GetLoadBalancer,
+		"getDeprecatedIPAddress": p.getDeprecatedIPAddress, // TODO: Should we expose getIPPort instead?
```
Comment (mmatur) [inline provider/docker/config.go]: Should be `"getIPAddress"` instead of `"getDeprecatedIPAddress"`
