### PR TITLE
Check ping configuration.

### LINKED ISSUE #2851: Traefik 1.5.2 & systemd watchdog issue
Traefik version : 1.5.2

OS : Ubuntu 16.04 LTS

Systemd service file : https://github.com/containous/traefik/blob/master/contrib/systemd/traefik.service

Traefik toml file :

``` toml
defaultEntryPoints = ["http", "https"]

logLevel = "ERROR"

[traefikLog]
filePath = "/var/log/traefik.log"

[accessLog]
filePath = "/var/log/traefik_access.log"

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]


[api]
entryPoint = "traefik"
dashboard = true
debug = false

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "traefik"
watch = true
exposedbydefault = true
swarmmode = true
```

```
Feb 13 10:32:53  traefik[6089]: goroutine 52 [running]:
Feb 13 10:32:53  traefik[6089]: runtime/debug.Stack(0x74f40f, 0xc420082320, 0x2128009)
Feb 13 10:32:53  traefik[6089]:         /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
Feb 13 10:32:53  traefik[6089]: runtime/debug.PrintStack()
Feb 13 10:32:53  traefik[6089]:         /usr/local/go/src/runtime/debug/stack.go:16 +0x22
Feb 13 10:32:53  traefik[6089]: github.com/containous/traefik/safe.defaultRecoverGoroutine(0x1dd7b00, 0x32e5af0)
Feb 13 10:32:53  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:148 +0x7d
Feb 13 10:32:53  traefik[6089]: github.com/containous/traefik/safe.GoWithRecover.func1.1(0x21aa728)
Feb 13 10:32:53  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:139 +0x57
Feb 13 10:32:53  traefik[6089]: panic(0x1dd7b00, 0x32e5af0)
Feb 13 10:32:53  traefik[6089]:         /usr/local/go/src/runtime/panic.go:491 +0x283
Feb 13 10:32:53  traefik[6089]: main.healthCheck(0xc42068b140, 0x0, 0x100, 0x0, 0x0, 0xc420631520, 0xc4205e0c80, 0x14, 0x0, 0xc420555800, ...)
Feb 13 10:32:53  traefik[6089]:         /go/src/github.com/containous/traefik/cmd/traefik/healthcheck.go:53 +0x37
Feb 13 10:32:53  traefik[6089]: main.run.func1()
Feb 13 10:32:53  traefik[6089]:         /go/src/github.com/containous/traefik/cmd/traefik/traefik.go:180 +0xfd
Feb 13 10:32:53  traefik[6089]: github.com/containous/traefik/safe.GoWithRecover.func1(0x21aa728, 0xc420244780)
Feb 13 10:32:53  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Feb 13 10:32:53  traefik[6089]: created by github.com/containous/traefik/safe.GoWithRecover
Feb 13 10:32:53  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
Feb 13 10:32:54  systemd[1]: traefik.service: Watchdog timeout (limit 1s)!
Feb 13 10:32:54  traefik[6089]: SIGABRT: abort
Feb 13 10:32:54  traefik[6089]: PC=0x45eb23 m=1 sigcode=0
Feb 13 10:32:54  traefik[6089]: goroutine 0 [idle]:
Feb 13 10:32:54  traefik[6089]: runtime.futex(0x32fee98, 0x0, 0xc42003beb8, 0x0, 0x0, 0xc42003bed0, 0x3c, 0x0, 0xc42003bed0, 0x4100b0, ...)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/sys_linux_amd64.s:480 +0x23
Feb 13 10:32:54  traefik[6089]: runtime.futexsleep(0x32fee98, 0x7ffe00000000, 0xdf8475800)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/os_linux.go:62 +0xd7
Feb 13 10:32:54  traefik[6089]: runtime.notetsleep_internal(0x32fee98, 0xdf8475800, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/lock_futex.go:193 +0x130
Feb 13 10:32:54  traefik[6089]: runtime.notetsleep(0x32fee98, 0xdf8475800, 0x1)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/lock_futex.go:216 +0x56
Feb 13 10:32:54  traefik[6089]: runtime.sysmon()
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/proc.go:3876 +0x14d
Feb 13 10:32:54  traefik[6089]: runtime.mstart1()
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/proc.go:1182 +0x11e
Feb 13 10:32:54  traefik[6089]: runtime.mstart()
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/proc.go:1152 +0x64
Feb 13 10:32:54  traefik[6089]: goroutine 1 [chan receive]:
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/server.(*Server).Wait(...)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:213
Feb 13 10:32:54  traefik[6089]: main.run(0xc420192380, 0xc4202eaedd, 0x1e)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/cmd/traefik/traefik.go:192 +0x444
Feb 13 10:32:54  traefik[6089]: main.main.func1(0xc42063ff80, 0xc42068f980)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/cmd/traefik/traefik.go:46 +0x42
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/vendor/github.com/containous/staert.(*Staert).Run(0xc42063ff60, 0xc420192380, 0xc4203c1700)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/vendor/github.com/containous/staert/staert.go:84 +0x2e
Feb 13 10:32:54  traefik[6089]: main.main()
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/cmd/traefik/traefik.go:131 +0x19b1
Feb 13 10:32:54  traefik[6089]: goroutine 14 [chan receive]:
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/vendor/github.com/golang/glog.(*loggingT).flushDaemon(0x32feb00)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/vendor/github.com/golang/glog/glog.go:879 +0x9f
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/vendor/github.com/golang/glog.init.0
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/vendor/github.com/golang/glog/glog.go:410 +0x203
Feb 13 10:32:54  traefik[6089]: goroutine 20 [syscall]:
Feb 13 10:32:54  traefik[6089]: os/signal.signal_recv(0xc420178540)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/sigqueue.go:131 +0xa6
Feb 13 10:32:54  traefik[6089]: os/signal.loop()
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
Feb 13 10:32:54  traefik[6089]: created by os/signal.init.0
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
Feb 13 10:32:54  traefik[6089]: goroutine 21 [semacquire]:
Feb 13 10:32:54  traefik[6089]: sync.runtime_notifyListWait(0xc4201e6a00, 0xc400000000)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/sema.go:507 +0x110
Feb 13 10:32:54  traefik[6089]: sync.(*Cond).Wait(0xc4201e69f0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/sync/cond.go:56 +0x80
Feb 13 10:32:54  traefik[6089]: io.(*pipe).read(0xc4201e69c0, 0xc420306000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/io/pipe.go:47 +0xc6
Feb 13 10:32:54  traefik[6089]: io.(*PipeReader).Read(0xc4205b6060, 0xc420306000, 0x1000, 0x1000, 0x1000, 0x1000, 0xc420189dc0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/io/pipe.go:130 +0x4c
Feb 13 10:32:54  traefik[6089]: bufio.(*Scanner).Scan(0xc4206e0f38, 0xc42018c9a0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/bufio/scan.go:207 +0xaf
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/vendor/github.com/Sirupsen/logrus.(*Entry).writerScanner(0xc420082320, 0xc4205b6060, 0xc4202f61b0)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/vendor/github.com/Sirupsen/logrus/writer.go:51 +0xab
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/vendor/github.com/Sirupsen/logrus.(*Entry).WriterLevel
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/vendor/github.com/Sirupsen/logrus/writer.go:43 +0x175
Feb 13 10:32:54  traefik[6089]: goroutine 22 [sleep]:
Feb 13 10:32:54  traefik[6089]: time.Sleep(0x8bb2c97000)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/time.go:65 +0x130
Feb 13 10:32:54  traefik[6089]: main.checkNewVersion.func1()
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/cmd/traefik/traefik.go:257 +0x39
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/safe.GoWithRecover.func1(0x21aa728, 0xc4203aaf90)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/safe.GoWithRecover
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
Feb 13 10:32:54  traefik[6089]: goroutine 23 [select, locked to thread]:
Feb 13 10:32:54  traefik[6089]: runtime.gopark(0x21b18c0, 0x0, 0x210d913, 0x6, 0x18, 0x1)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/proc.go:287 +0x12c
Feb 13 10:32:54  traefik[6089]: runtime.selectgo(0xc4206dcf50, 0xc420194240)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/select.go:395 +0x1149
Feb 13 10:32:54  traefik[6089]: runtime.ensureSigM.func1()
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/signal_unix.go:511 +0x220
Feb 13 10:32:54  traefik[6089]: runtime.goexit()
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/asm_amd64.s:2337 +0x1
Feb 13 10:32:54  traefik[6089]: goroutine 24 [sleep]:
Feb 13 10:32:54  traefik[6089]: time.Sleep(0x3b9aca00)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/time.go:65 +0x130
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/vendor/github.com/thoas/stats.New.func1(0xc4206cd9e0)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/vendor/github.com/thoas/stats/stats.go:35 +0x38
Feb 13 10:32:54  systemd[1]: traefik.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/vendor/github.com/thoas/stats.New
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/vendor/github.com/thoas/stats/stats.go:31 +0x150
Feb 13 10:32:54  traefik[6089]: goroutine 25 [IO wait]:
Feb 13 10:32:54  traefik[6089]: internal/poll.runtime_pollWait(0x7fc2ade18f70, 0x72, 0xffffffffffffffff)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/netpoll.go:173 +0x57
Feb 13 10:32:54  traefik[6089]: internal/poll.(*pollDesc).wait(0xc4202e5e98, 0x72, 0xc4207feb00, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
Feb 13 10:32:54  traefik[6089]: internal/poll.(*pollDesc).waitRead(0xc4202e5e98, 0xffffffffffffff00, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
Feb 13 10:32:54  traefik[6089]: internal/poll.(*FD).Accept(0xc4202e5e80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/internal/poll/fd_unix.go:335 +0x1e2
Feb 13 10:32:54  traefik[6089]: net.(*netFD).accept(0xc4202e5e80, 0xc4204df1c8, 0xc4205f80d0, 0x1f87d40)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/fd_unix.go:238 +0x42
Feb 13 10:32:54  traefik[6089]: net.(*TCPListener).accept(0xc4205b70d8, 0x4f7ce5, 0xc4204df1c8, 0xc4205f80d0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
Feb 13 10:32:54  traefik[6089]: net.(*TCPListener).Accept(0xc4205b70d8, 0xc42008a020, 0x1d89000, 0x32e59f0, 0x20ab6e0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/tcpsock.go:247 +0x49
Feb 13 10:32:54  traefik[6089]: net/http.(*Server).Serve(0xc4205f80d0, 0x30b7d80, 0xc4205b70d8, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/http/server.go:2695 +0x1b2
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/server.(*Server).startServer(0xc42062afc0, 0xc4202caeb0, 0xc42068b140, 0x0, 0x100, 0x0, 0x0, 0xc420631520, 0xc4205e0c80, 0
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:734 +0x1f9
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/server.(*Server).startHTTPServers
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:284 +0x167
Feb 13 10:32:54  traefik[6089]: goroutine 26 [IO wait]:
Feb 13 10:32:54  traefik[6089]: internal/poll.runtime_pollWait(0x7fc2ade18eb0, 0x72, 0xffffffffffffffff)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/netpoll.go:173 +0x57
Feb 13 10:32:54  traefik[6089]: internal/poll.(*pollDesc).wait(0xc4202e5f98, 0x72, 0xc4207fab00, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
Feb 13 10:32:54  traefik[6089]: internal/poll.(*pollDesc).waitRead(0xc4202e5f98, 0xffffffffffffff00, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
Feb 13 10:32:54  systemd[1]: traefik.service: Unit entered failed state.
Feb 13 10:32:54  traefik[6089]: internal/poll.(*FD).Accept(0xc4202e5f80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/internal/poll/fd_unix.go:335 +0x1e2
Feb 13 10:32:54  traefik[6089]: net.(*netFD).accept(0xc4202e5f80, 0xc4204df258, 0xc4205f81a0, 0x1f87d40)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/fd_unix.go:238 +0x42
Feb 13 10:32:54  traefik[6089]: net.(*TCPListener).accept(0xc4205b70f8, 0x4f7ce5, 0xc4204df258, 0xc4205f81a0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
Feb 13 10:32:54  traefik[6089]: net.(*TCPListener).Accept(0xc4205b70f8, 0xc42008a020, 0x1d89000, 0x32e59f0, 0x20ab6e0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/tcpsock.go:247 +0x49
Feb 13 10:32:54  traefik[6089]: net/http.(*Server).Serve(0xc4205f81a0, 0x30b7d80, 0xc4205b70f8, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/http/server.go:2695 +0x1b2
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/server.(*Server).startServer(0xc42062afc0, 0xc4202caf00, 0xc42068b140, 0x0, 0x100, 0x0, 0x0, 0xc420631520, 0xc4205e0c80, 0
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:734 +0x1f9
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/server.(*Server).startHTTPServers
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:284 +0x167
Feb 13 10:32:54  traefik[6089]: goroutine 15 [IO wait]:
Feb 13 10:32:54  traefik[6089]: internal/poll.runtime_pollWait(0x7fc2ade18df0, 0x72, 0xffffffffffffffff)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/netpoll.go:173 +0x57
Feb 13 10:32:54  traefik[6089]: internal/poll.(*pollDesc).wait(0xc4202e4018, 0x72, 0xc4206e3900, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
Feb 13 10:32:54  traefik[6089]: internal/poll.(*pollDesc).waitRead(0xc4202e4018, 0xffffffffffffff00, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
Feb 13 10:32:54  traefik[6089]: internal/poll.(*FD).Accept(0xc4202e4000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/internal/poll/fd_unix.go:335 +0x1e2
Feb 13 10:32:54  traefik[6089]: net.(*netFD).accept(0xc4202e4000, 0x7fc2adbd6178, 0x0, 0x21b19f8)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/fd_unix.go:238 +0x42
Feb 13 10:32:54  traefik[6089]: net.(*TCPListener).accept(0xc42000c018, 0x21b19f8, 0xc420019300, 0xc42048a628)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/tcpsock_posix.go:136 +0x2e
Feb 13 10:32:54  traefik[6089]: net.(*TCPListener).Accept(0xc42000c018, 0xc4205da0c0, 0xc4206e3ba0, 0x4f7c4a, 0x1f87d40)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/tcpsock.go:247 +0x49
Feb 13 10:32:54  traefik[6089]: crypto/tls.(*listener).Accept(0xc42030e020, 0xc42008a020, 0x1d89000, 0x32e59f0, 0x20ab6e0)
Feb 13 10:32:54  systemd[1]: traefik.service: Failed with result 'exit-code'.
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/crypto/tls/tls.go:52 +0x37
Feb 13 10:32:54  traefik[6089]: net/http.(*Server).Serve(0xc420592270, 0x30aef40, 0xc42030e020, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/http/server.go:2695 +0x1b2
Feb 13 10:32:54  traefik[6089]: net/http.(*Server).ServeTLS(0xc420592270, 0x30b7d80, 0xc42000c018, 0x0, 0x0, 0x0, 0x0, 0xc420157a40, 0xc420157b90)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/http/server.go:2764 +0x293
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/server.(*Server).startServer(0xc42062afc0, 0xc4202caf50, 0xc42068b140, 0x0, 0x100, 0x0, 0x0, 0xc420631520, 0xc4205e0c80, 0
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:732 +0x103
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/server.(*Server).startHTTPServers
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:284 +0x167
Feb 13 10:32:54  traefik[6089]: goroutine 16 [select]:
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/server.(*Server).listenProviders(0xc42062afc0, 0xc4201822a0)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:342 +0x11e
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/server.(*Server).Start.func1(0xc4201822a0)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:201 +0x34
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/safe.(*Pool).Go.func1()
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:78 +0x3a
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/safe.GoWithRecover.func1(0x21aa728, 0xc4205564e0)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/safe.GoWithRecover
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
Feb 13 10:32:54  traefik[6089]: goroutine 49 [select]:
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/server.(*Server).listenConfigurations(0xc42062afc0, 0xc420182310)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:417 +0x11e
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/server.(*Server).Start.func2(0xc420182310)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:204 +0x34
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/safe.(*Pool).Go.func1()
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:78 +0x3a
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/safe.GoWithRecover.func1(0x21aa728, 0xc420556510)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/safe.GoWithRecover
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
Feb 13 10:32:54  traefik[6089]: goroutine 51 [chan receive]:
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/server.(*Server).listenSignals(0xc42062afc0)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server_signals.go:19 +0x63
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/server.(*Server).Start
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:208 +0x119
Feb 13 10:32:54  traefik[6089]: goroutine 53 [chan receive]:
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/provider/docker.(*Provider).Provide.func1.1(0x8, 0x21aa720)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/provider/docker/docker.go:201 +0xe1f
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/safe.OperationWithRecover.func1(0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:160 +0x6c
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/vendor/github.com/cenk/backoff.RetryNotify(0xc420702ac0, 0x30a9440, 0xc420702ad0, 0x21aa5f0, 0x1aba3b0, 0x1)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/vendor/github.com/cenk/backoff/retry.go:37 +0x88
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/provider/docker.(*Provider).Provide.func1()
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/provider/docker/docker.go:264 +0x12d
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/safe.GoWithRecover.func1(0x21aa728, 0xc4202447e0)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/safe.GoWithRecover
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
Feb 13 10:32:54  traefik[6089]: goroutine 55 [IO wait]:
Feb 13 10:32:54  traefik[6089]: internal/poll.runtime_pollWait(0x7fc2ade18d30, 0x72, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/netpoll.go:173 +0x57
Feb 13 10:32:54  traefik[6089]: internal/poll.(*pollDesc).wait(0xc4202e5518, 0x72, 0xffffffffffffff00, 0x30a8280, 0x309a560)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0xae
Feb 13 10:32:54  traefik[6089]: internal/poll.(*pollDesc).waitRead(0xc4202e5518, 0xc420307000, 0x1000, 0x1000)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
Feb 13 10:32:54  traefik[6089]: internal/poll.(*FD).Read(0xc4202e5500, 0xc420307000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/internal/poll/fd_unix.go:126 +0x18a
Feb 13 10:32:54  traefik[6089]: net.(*netFD).Read(0xc4202e5500, 0xc420307000, 0x1000, 0x1000, 0x42df5b, 0xc4206dda40, 0x459750)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/fd_unix.go:202 +0x52
Feb 13 10:32:54  traefik[6089]: net.(*conn).Read(0xc42000c048, 0xc420307000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/net.go:176 +0x6d
Feb 13 10:32:54  traefik[6089]: net/http.(*persistConn).Read(0xc4206a8480, 0xc420307000, 0x1000, 0x1000, 0xc42058abe0, 0xc420074178, 0x4577b0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/http/transport.go:1391 +0x140
Feb 13 10:32:54  traefik[6089]: bufio.(*Reader).fill(0xc4206cc7e0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/bufio/bufio.go:97 +0x11a
Feb 13 10:32:54  traefik[6089]: bufio.(*Reader).Peek(0xc4206cc7e0, 0x1, 0x0, 0x0, 0x0, 0xc420074360, 0x0)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/bufio/bufio.go:129 +0x3a
Feb 13 10:32:54  traefik[6089]: net/http.(*persistConn).readLoop(0xc4206a8480)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/http/transport.go:1539 +0x185
Feb 13 10:32:54  traefik[6089]: created by net/http.(*Transport).dialConn
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/http/transport.go:1186 +0xa2e
Feb 13 10:32:54  traefik[6089]: goroutine 56 [select]:
Feb 13 10:32:54  traefik[6089]: net/http.(*persistConn).writeLoop(0xc4206a8480)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/http/transport.go:1759 +0x165
Feb 13 10:32:54  traefik[6089]: created by net/http.(*Transport).dialConn
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/net/http/transport.go:1187 +0xa53
Feb 13 10:32:54  traefik[6089]: goroutine 58 [select]:
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/provider/docker.(*Provider).Provide.func1.1.1(0xc420182690)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/provider/docker/docker.go:178 +0x175
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/safe.(*Pool).Go.func1()
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:78 +0x3a
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/safe.GoWithRecover.func1(0x21aa728, 0xc4203c5d40)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/safe.GoWithRecover
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
Feb 13 10:32:54  traefik[6089]: goroutine 59 [select]:
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/server.throttleProviderConfigReload(0x77359400, 0xc4206cd740, 0xc420194b40, 0xc420182700)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:398 +0x222
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/server.(*Server).preLoadConfiguration.func1(0xc420182700)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:370 +0x4a
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/safe.(*Pool).Go.func1()
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:78 +0x3a
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/safe.GoWithRecover.func1(0x21aa728, 0xc42032b230)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/safe.GoWithRecover
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
Feb 13 10:32:54  traefik[6089]: goroutine 60 [select]:
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/vendor/github.com/eapache/channels.(*RingChannel).ringBuffer(0xc42032b290)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/vendor/github.com/eapache/channels/ring_channel.go:87 +0x22d
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/vendor/github.com/eapache/channels.NewRingChannel
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/vendor/github.com/eapache/channels/ring_channel.go:32 +0x1f1
Feb 13 10:32:54  traefik[6089]: goroutine 61 [sleep]:
Feb 13 10:32:54  traefik[6089]: time.Sleep(0x77359400)
Feb 13 10:32:54  traefik[6089]:         /usr/local/go/src/runtime/time.go:65 +0x130
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/server.throttleProviderConfigReload.func1()
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/server/server.go:392 +0x95
Feb 13 10:32:54  traefik[6089]: github.com/containous/traefik/safe.GoWithRecover.func1(0x21aa728, 0xc42032b2c0)
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Feb 13 10:32:54  traefik[6089]: created by github.com/containous/traefik/safe.GoWithRecover
Feb 13 10:32:54  traefik[6089]:         /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
Feb 13 10:32:54  traefik[6089]: rax    0xfffffffffffffffc
Feb 13 10:32:54  traefik[6089]: rbx    0x0
Feb 13 10:32:54  traefik[6089]: rcx    0x45eb23
Feb 13 10:32:54  traefik[6089]: rdx    0x0
Feb 13 10:32:54  traefik[6089]: rdi    0x32fee98
Feb 13 10:32:54  traefik[6089]: rsi    0x0
Feb 13 10:32:54  traefik[6089]: rbp    0xc42003bec8
Feb 13 10:32:54  traefik[6089]: rsp    0xc42003be80
Feb 13 10:32:54  traefik[6089]: r8     0x0
Feb 13 10:32:54  traefik[6089]: r9     0x0
Feb 13 10:32:54  traefik[6089]: r10    0xc42003beb8
Feb 13 10:32:54  traefik[6089]: r11    0x246
Feb 13 10:32:54  traefik[6089]: r12    0x430a60
Feb 13 10:32:54  traefik[6089]: r13    0xf1
Feb 13 10:32:54  traefik[6089]: r14    0x11
Feb 13 10:32:54  traefik[6089]: r15    0x0
Feb 13 10:32:54  traefik[6089]: rip    0x45eb23
Feb 13 10:32:54  traefik[6089]: rflags 0x246
Feb 13 10:32:54  traefik[6089]: cs     0x33
Feb 13 10:32:54  traefik[6089]: fs     0x0
Feb 13 10:32:54  traefik[6089]: gs     0x0
```

or 

```
Feb 13 10:44:34  systemd[1]: traefik.service: Service hold-off time over, scheduling restart.
Feb 13 10:44:34  systemd[1]: Stopped Traefik.
Feb 13 10:44:34  systemd[1]: Starting Traefik...
Feb 13 10:44:35  systemd[1]: Started Traefik.
Feb 13 10:44:38  traefik[10341]: goroutine 71 [running]:
Feb 13 10:44:38  traefik[10341]: runtime/debug.Stack(0x74f40f, 0xc42000e370, 0x2128009)
Feb 13 10:44:38  traefik[10341]:         /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
Feb 13 10:44:38  traefik[10341]: runtime/debug.PrintStack()
Feb 13 10:44:38  traefik[10341]:         /usr/local/go/src/runtime/debug/stack.go:16 +0x22
Feb 13 10:44:38  traefik[10341]: github.com/containous/traefik/safe.defaultRecoverGoroutine(0x1dd7b00, 0x32e5af0)
Feb 13 10:44:38  traefik[10341]:         /go/src/github.com/containous/traefik/safe/routine.go:148 +0x7d
Feb 13 10:44:38  traefik[10341]: github.com/containous/traefik/safe.GoWithRecover.func1.1(0x21aa728)
Feb 13 10:44:38  traefik[10341]:         /go/src/github.com/containous/traefik/safe/routine.go:139 +0x57
Feb 13 10:44:38  traefik[10341]: panic(0x1dd7b00, 0x32e5af0)
Feb 13 10:44:38  traefik[10341]:         /usr/local/go/src/runtime/panic.go:491 +0x283
Feb 13 10:44:38  traefik[10341]: main.healthCheck(0xc4205316a0, 0x0, 0x100, 0x0, 0x0, 0xc4202ee5c0, 0x0, 0x0, 0xc4202ee600, 0xc42035ad28, ...)
Feb 13 10:44:38  traefik[10341]:         /go/src/github.com/containous/traefik/cmd/traefik/healthcheck.go:53 +0x37
Feb 13 10:44:38  traefik[10341]: main.run.func1()
Feb 13 10:44:38  traefik[10341]:         /go/src/github.com/containous/traefik/cmd/traefik/traefik.go:180 +0xfd
Feb 13 10:44:38  traefik[10341]: github.com/containous/traefik/safe.GoWithRecover.func1(0x21aa728, 0xc4205a3360)
Feb 13 10:44:38  traefik[10341]:         /go/src/github.com/containous/traefik/safe/routine.go:142 +0x4d
Feb 13 10:44:38  traefik[10341]: created by github.com/containous/traefik/safe.GoWithRecover
Feb 13 10:44:38  traefik[10341]:         /go/src/github.com/containous/traefik/safe/routine.go:136 +0x49
...skipping...
Feb 13 10:44:34  traefik[10325]:         /usr/local/go/src/bufio/bufio.go:129 +0x3a
Feb 13 10:44:34  traefik[10325]: net/http.(*conn).serve(0xc420260d20, 0x30b9f40, 0xc42065e300)
Feb 13 10:44:34  traefik[10325]:         /usr/local/go/src/net/http/server.go:1826 +0x88f
Feb 13 10:44:34  traefik[10325]: created by net/http.(*Server).Serve
Feb 13 10:44:34  traefik[10325]:         /usr/local/go/src/net/http/server.go:2720 +0x288
Feb 13 10:44:34  traefik[10325]: rax    0xca
Feb 13 10:44:34  traefik[10325]: rbx    0x32ff8c0
Feb 13 10:44:34  traefik[10325]: rcx    0x45eb23
Feb 13 10:44:34  traefik[10325]: rdx    0x0
Feb 13 10:44:34  traefik[10325]: rdi    0x32ff9f8
Feb 13 10:44:34  traefik[10325]: rsi    0x0
Feb 13 10:44:34  traefik[10325]: rbp    0x7ffe5bb89010
Feb 13 10:44:34  traefik[10325]: rsp    0x7ffe5bb88fc8
Feb 13 10:44:34  traefik[10325]: r8     0x0
Feb 13 10:44:34  traefik[10325]: r9     0x0
Feb 13 10:44:34  traefik[10325]: r10    0x0
Feb 13 10:44:34  traefik[10325]: r11    0x286
Feb 13 10:44:34  traefik[10325]: r12    0x0
Feb 13 10:44:34  traefik[10325]: r13    0x0
Feb 13 10:44:34  traefik[10325]: r14    0x45c360
Feb 13 10:44:34  traefik[10325]: r15    0x0
Feb 13 10:44:34  traefik[10325]: rip    0x45eb21
Feb 13 10:44:34  traefik[10325]: rflags 0x286
Feb 13 10:44:34  traefik[10325]: cs     0x33
Feb 13 10:44:34  traefik[10325]: fs     0x0
Feb 13 10:44:34  traefik[10325]: gs     0x0
```

I had to remove the Watchdog section in the systemd service unit file to have traefik work as expected.

### PR DESCRIPTION
**Pull request by ldez**
### What does this PR do?

Check if Ping pointer is not nil.

### Motivation

Fixes  #2851

### More

- [ ] Added/updated tests

### CODE REVIEW

File: cmd/traefik/healthcheck.go [hunk 1]
```diff
@@ -50,6 +45,10 @@ func runHealthCheck(traefikConfiguration *TraefikConfiguration) func() error {
 }
 
 func healthCheck(globalConfiguration configuration.GlobalConfiguration) (*http.Response, error) {
+	if globalConfiguration.Ping == nil {
+		return nil, errors.New("please enable `ping` to use healtcheck")
```
Comment (timoreimann) [inline cmd/traefik/healthcheck.go]: Typo: healtcheck -> health check (pre-existing :) )
