### PR TITLE
Auto-negotiate Docker API Version

### LINKED ISSUE #12253: Error response from daemon: client version 1.24 is too old
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Upgraded docker to 29.0.0 (https://docs.docker.com/engine/release-notes/29/)

There are breaking changes: https://docs.docker.com/engine/deprecated/#deprecate-legacy-api-versions

### What did you see instead?

```
2025-11-10T23:03:43Z ERR Failed to retrieve information of the docker client and server host error="Error response from daemon: client version 1.24 is too old. Minimum supported API version is 1.44, please upgrade your client to a newer version" providerName=docker
2025-11-10T23:03:43Z ERR Provider error, retrying in 2.356192979s error="Error response from daemon: client version 1.24 is too old. Minimum supported API version is 1.44, please upgrade your client to a newer version" providerName=docker
```

### What version of Traefik are you using?

```
$ sudo docker exec -it traefik traefik version
Version:      3.6.0
Codename:     ramequin
Go version:   go1.24.10
Built:        2025-11-07T15:22:11Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

### If applicable, please paste the log output in DEBUG level

_No response_

### PR DESCRIPTION
**Pull request by felixbuenemann**
### What does this PR do?

This PR fixes #12253 by removing the hardcoded docker api version and relying on auto-negotiation between the docker client (sdk) and server using [WithAPIVersionNegotiation()](https://github.com/moby/moby/blob/v28.5.2/client/options.go#L221).

### Motivation

Traefik currently fails to work with Docker v29 with the following errors:

```
2025-11-10T23:03:43Z ERR Failed to retrieve information of the docker client and server host error="Error response from daemon: client version 1.24 is too old. Minimum supported API version is 1.44, please upgrade your client to a newer version" providerName=docker
2025-11-10T23:03:43Z ERR Provider error, retrying in 2.356192979s error="Error response from daemon: client version 1.24 is too old. Minimum supported API version is 1.44, please upgrade your client to a newer version" providerName=docker
```

Fixes #12253

### Additional Notes

- Tested on production servers with Docker 29.0.0.
- Test docker image available with tag `felixbuenemann/traefik:v3.6` on docker hub (created with `make build-image`)

### CODE REVIEW

File: pkg/provider/docker/shared.go
Comment (thaJeztah) [inline pkg/provider/docker/shared.go:118]: Orthogonal to this PR, but this could use the `client.WithUserAgent()` option; https://github.com/moby/moby/blob/bea959c7b793b32a893820b97c4eadc7c87fabb0/client/options.go#L110-L118

File: pkg/provider/docker/shared.go [hunk 1]
```diff
@@ -124,7 +122,7 @@ func createClient(ctx context.Context, cfg ClientConfig) (*client.Client, error)
 
 	opts = append(opts,
 		client.WithHTTPHeaders(httpHeaders),
-		client.WithVersion(cfg.apiVersion))
+		client.WithAPIVersionNegotiation())
```
Comment (thaJeztah) [inline pkg/provider/docker/shared.go:125]: Not sure if practical for how traefik is used, but it's possible to _also_ add the [`client.FromEnv`](https://github.com/moby/moby/blob/v28.3.3/client/options.go#L22-L47) (in addition to `client.WithAPIVersionNegotiation`) option, which would allow setting a fixed API version (and some other options) through the `DOCKER_API_VERSION` env-var.


If it's desirable to make this configurable through the config-file; [`WithVersion`](https://github.com/moby/moby/blob/v28.3.3/client/options.go#L194-L205) and `WithAPIVersionNegotiation` can be used _both_ as long as `cfg.apiVersion` is empty by default (otherwise it pins the API version to that version, similar to `FromEnv` with `DOCKER_API_VERSION` set), but IIUC, the `cfg.apiVersion` (non-exported) was not configurable currently, correct? So that would be a new feature.

File: pkg/provider/docker/shared.go
Comment (felixbuenemann) [reply pkg/provider/docker/shared.go:118]: Since we need to use `WithHTTPHeaders()` anyways for the `Authorization` header, I see no benefit in using `WithUserAgent()`.

File: pkg/provider/docker/shared.go (hunk 1 above)
Comment (felixbuenemann) [reply pkg/provider/docker/shared.go:125]: If I understand the other comments correctly then version negotiation is supported since Docker API version 1.24, which was the minimum version previously supported. So why would we want to override the API version?

**Comment by MarkenJaden** [comment]
Tested the build on our system and can confirm it works.

File: pkg/provider/docker/shared.go (hunk 1 above)
Comment (thaJeztah) [reply pkg/provider/docker/shared.go:125]: Ah, yes, it's been supported for a long time; so using it as a default makes perfect sense! I'm not deeply familiar with expectations people may have from Traefik, and am aware that in some settings, people prefer to either fixate the API version (which may be to skip the extra "ping" round-trip).

File: pkg/provider/docker/shared.go
Comment (thaJeztah) [reply pkg/provider/docker/shared.go:118]: Yes, it should be mostly equivalent; I recall older versions of the client did not allow overriding User-Agent through custom headers; there's also still some extra handling in the code to make sure that what's set through `WithUserAgent` is always applied "last"; I think this was to account for situations where it was not desirable for the end-user to override the user-agent in some situations.

**Review by thaJeztah — COMMENTED** [review]
FWIW, changes in this LGTM (assuming CI is happy)

**Comment by thaJeztah** [comment]
w.r.t. updating to the new (moby.moby/client, moby/moby/api) modules; https://github.com/traefik/traefik/pull/12255#issuecomment-3515188162

> It would probably be better to update this PR so the project no longer uses the deprecated API, and replace it with the recommended current one, since the old one is probably no longer supported.

I don't think there's an immediate urgency, and the changes in this PR look good to fix the problem at hand, unless traefik must support features only available in API v1.52 or up.

While the project _should_ transition at some point, the client module is still a v0.x release, and there will be breaking changes in future in the client signatures (we plan to migrate it to functional options, and improve usability of streaming endpoints).

If would be good to update the dependency to the lastest v28.x version (currently at v28.3.3, which is an older minor release), and it won't hurt to explore what changes are needed to transition, but it's fine to keep that for a future exercise.

**Comment by thaJeztah** [comment]
@rtribotte looks like CI needs a kick / approval to run 😅

**Comment by goppinath** [comment]
Does anyone have an estimate for when this update will be available? I have several instances down because of this issue, and I prefer not to use workarounds.

**Comment by sbusch** [comment]
Until this lands on Docker Hub, you can use the image the PR author @felixbuenemann kindly published instead:

`docker.io/felixbuenemann/traefik:v3.6.1`

Works for us.

**Comment by thaJeztah** [comment]
Interesting; was `letsencrypt/pebble` and existing image? 

```
2025/11/12 10:55:28 🔔 Container is ready: 902ec3d34995
    integration_test.go:261: 
        	Error Trace:	/home/runner/work/traefik/traefik/integration/integration_test.go:261
        	            				/home/runner/work/traefik/traefik/integration/acme_test.go:100
        	            				/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.11.1/suite/suite.go:211
        	            				/home/runner/work/traefik/traefik/integration/acme_test.go:34
        	Error:      	Received unexpected error:
        	            	Error response from daemon: pull access denied for letsencrypt/pebble, repository does not exist or may require 'docker login': denied: requested access to the resource is denied: failed to create container
        	Test:       	TestAcmeSuite
```

Looks like it's gone from Docker Hub; https://hub.docker.com/r/letsencrypt/pebble

I do see a reference to `ghcr.io/letsencrypt/pebble:2.8.0` elsewhere;
https://github.com/traefik/traefik/blob/2ad42cd0ec2ebcc159f20544e45768d2e017b33b/integration/resources/compose/pebble.yml#L3

**Comment by marcopaggioro** [comment]
> Interesting; was `letsencrypt/pebble` and existing image?
> 
> ```
> 2025/11/12 10:55:28 🔔 Container is ready: 902ec3d34995
>     integration_test.go:261: 
>         	Error Trace:	/home/runner/work/traefik/traefik/integration/integration_test.go:261
>         	            				/home/runner/work/traefik/traefik/integration/acme_test.go:100
>         	            				/home/runner/go/pkg/mod/github.com/stretchr/testify@v1.11.1/suite/suite.go:211
>         	            				/home/runner/work/traefik/traefik/integration/acme_test.go:34
>         	Error:      	Received unexpected error:
>         	            	Error response from daemon: pull access denied for letsencrypt/pebble, repository does not exist or may require 'docker login': denied: requested access to the resource is denied: failed to create container
>         	Test:       	TestAcmeSuite
> ```
> 
> Looks like it's gone from Docker Hub; https://hub.docker.com/r/letsencrypt/pebble
> 
> I do see a reference to `ghcr.io/letsencrypt/pebble:2.8.0` elsewhere;
> 
> https://github.com/traefik/traefik/blob/2ad42cd0ec2ebcc159f20544e45768d2e017b33b/integration/resources/compose/pebble.yml#L3

https://github.com/letsencrypt/pebble/issues/451

**Review by kevinpollet — APPROVED** [review]
Thanks for fixing this @felixbuenemann and for the review @thaJeztah 👍

**Review by rtribotte — APPROVED** [review]
Thanks!

**Comment by foux** [comment]
In which version is this PR merged? Thanks

**Comment by waja** [comment]
> In which version is this PR merged? Thanks

> [traefiker](https://github.com/traefiker) merged commit [baba5da](https://github.com/traefik/traefik/commit/baba5da88bcb26b31bffc317374babafcab28836) into traefik:v3.6 [1 hour ago](https://github.com/traefik/traefik/pull/12256#event-20892875846)

**Comment by xXSalamanderXx** [comment]
> > In which version is this PR merged? Thanks
> 
> > [traefiker](https://github.com/traefiker) merged commit [baba5da](https://github.com/traefik/traefik/commit/baba5da88bcb26b31bffc317374babafcab28836) into traefik:v3.6 [1 hour ago](https://github.com/traefik/traefik/pull/12256#event-20892875846)

Pulling 3.6 but still getting `error="Error response from daemon: client version 1.24 is too old. Minimum supported API version is 1.44`

Edit: For anyone that was confused like me:

    v3.6 was released 5 days ago (image exists)

    Fix was just merged into v3.6 branch 1 hour ago

    But the v3.6 Docker image from 5 days ago doesn't have the fix

**Comment by waja** [comment]
> Pulling 3.6 but still getting `error="Error response from daemon: client version 1.24 is too old. Minimum supported API version is 1.44`

I would guess, it's just merged into the VCS, but there is no new release yet?!?

**Comment by xXSalamanderXx** [comment]
> > Pulling 3.6 but still getting `error="Error response from daemon: client version 1.24 is too old. Minimum supported API version is 1.44`
> 
> I would guess, it's just merged into the VCS, but there is no new release yet?!?

So have to wait for a new release, or can they rebuild 3.6?

**Comment by saltydk** [comment]
> > > Pulling 3.6 but still getting `error="Error response from daemon: client version 1.24 is too old. Minimum supported API version is 1.44`
> > 
> > 
> > I would guess, it's just merged into the VCS, but there is no new release yet?!?
> 
> So have to wait for a new release, or can they rebuild 3.6?

https://github.com/traefik/traefik/tags until 3.6.1 appears there nothing will happen.

**Comment by MrTengil** [comment]
> > > > Pulling 3.6 but still getting `error="Error response from daemon: client version 1.24 is too old. Minimum supported API version is 1.44`
> > > 
> > > 
> > > I would guess, it's just merged into the VCS, but there is no new release yet?!?
> > 
> > 
> > So have to wait for a new release, or can they rebuild 3.6?
> 
> https://github.com/traefik/traefik/tags until 3.6.1 appears there nothing will happen.

Great fix! Do we know when it will be released? @felixbuenemann

**Comment by iBros** [comment]
Stuck with this as well - pulled v3.6 image, same issue. I'd argue that the severity and impact of this issue should be enough to create a new release

**Comment by ChaosExAnima** [comment]
as a workaround i switched to `felixbuenemann/traefik:v3.6.1` as per the description and it works great.

**Comment by iBros** [comment]
> Until this lands on Docker Hub, you can use the image the PR author @felixbuenemann kindly published instead:
> 
> `docker.io/felixbuenemann/traefik:v3.6.1`
> 
> Works for us.



> as a workaround i switched to `felixbuenemann/traefik:v3.6.1` as per the description and it works great.

I missed it in the thread. great and thx to @felixbuenemann !
