### PR TITLE
fix: redirect to HTTPS first before basic auth if header redirect (secure) is set

### LINKED ISSUE #3134: Do SSLRedirect before auth.basic
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Deploy a docker service with the following labels:

```yaml
        - traefik.frontend.rule=Host:private.example.com
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.auth.basic=username:password
        - traefik.frontend.headers.SSLRedirect=true
```

### What did you expect to see?

Opening `http://private.example.com` redirects to `https://private.example.com` before prompting for authorisation.

### What did you see instead?

`http://private.example.com` requires authorisation before redirecting. This means user has to enter authorisation data twice, and the first authorisation data is sent over an insecure connection.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
1.5.4
```

### PR DESCRIPTION
**Pull request by SantoDE**
### What does this PR do?

Fixes #3134 by moving the order of middleware invoking

### Motivation

Don't transfer basic auth credentials over an insecure connection if security headers are set.

### CODE REVIEW

File: server/server.go [hunk 1]
```diff
@@ -1192,26 +1202,6 @@ func (s *Server) loadConfig(configurations types.Configurations, globalConfigura
...
-						log.Debugf("Adding header middleware for frontend %s", frontendName)
-						n.Use(s.tracingMiddleware.NewNegroniHandlerWrapper("Header", headerMiddleware, false))
-					}
-
-					if secureMiddleware != nil {
-						log.Debugf("Adding secure middleware for frontend %s", frontendName)
-						n.UseFunc(secureMiddleware.HandlerFuncWithNextForRequestOnly)
-					}
-
-					if config.Backends[frontend.Backend].Buffering != nil {
```
Comment (mmatur) [inline server/server.go]: Bye bye Buffering :wave:

Comment (dtomcej) [reply server/server.go]: Buffering is for the weak.

Comment (SantoDE) [reply server/server.go]: Nothing happened @dtomcej @mmatur :D 😇
