### PR TITLE
Fix host Docker network

### LINKED ISSUE #447: domain label doesn't work on docker
Hi !

I've tried to use the traefik.domain label on one of my container in order to change the default domain applied to the frontend but unfortunately it doesn't work :(

I've created the label with docker run --label traefik.domain=mydomain.com

Can you confirm the bug ?

Regards

### LINKED ISSUE #487: [Docker] No IP in backend in host networking mode
I have a Docker machine set up to use the `host` network mode. Here's the `docker-compose` entry:
```
hass:
  image: 'homeassistant/home-assistant'
  restart: always
  net: 'host'
  volumes:
    - '/etc/localtime:/etc/localtime:ro'
    - '/srv/hass/config:/config'
  labels:
    - "traefik.backend=hass"
    - "traefik.frontend.rule=Host:home.redacted.net"
    - "traefik.port=8123"
```

When traefik picks it, the backend's URL is set to `http://:8123`, the IP is missing. Is there any other solution than skipping this docker machine (`traefik.enable=false`) and adding it from somewhere else? A missing label I could hint traefik with?

### PR DESCRIPTION
**Pull request by emilevauge**
Fixes #487
Fixes #447

Signed-off-by: Emile Vauge <emile@vauge.com>

### CODE REVIEW

File: provider/docker.go [hunk 1]
```diff
@@ -270,7 +270,12 @@ func (provider *Docker) getIPAddress(container dockertypes.ContainerJSON) string
 			}
 		}
 	}
-	for _, network := range container.NetworkSettings.Networks {
+	for networkName, network := range container.NetworkSettings.Networks {
```
Comment (vdemeester) [inline provider/docker.go]: I'm pretty sure it's more reliable to look at `container.HostConfig.NetworkMode` to detect the `host` network mode :angel:

Comment (emilevauge) [inline provider/docker.go]: OK :) How to go from `pretty sure` to `sure`? ^^
What could be unreliable using `container.NetworkSettings.Networks`?

Comment (vdemeester) [inline provider/docker.go]: Well, `host` is a reserved named for network (to *map* the networkMode host) but well…
The other thing is on versions, `networkMode` is guaranteed to be there since… well a while…, but `NetworkSettings.Networks` has been updated quite a while.

Anyway that's just a nit, backward compatibility should make it that it works ok like that for more than a while :angel:

**Comment by vdemeester** [comment]
LGTM 🐹
