### PR TITLE
Abort Kubernetes Ingress update if Kubernetes API call fails

### LINKED ISSUE #1240: When Kubernetes API Fails, Traefik starts returning 404s
### What version of Traefik are you using (`traefik version`)?

1.1.3

### What is your environment & configuration (arguments, toml...)?

Kubernetes ingress controllers

### What did you do?

When kube api returns error during sync, traefik starts returning 404s.

### What did you expect to see?

Traefik continues to run with last known configuration.

### What did you see instead?

Traefik wipes config and starts returning 404s until API calls start succeeding.

Traefik maintains a cached state of the last good configuration. It should continue to use the last good configuration when it encounters an API error during sync process. Right now it just logs the error and throws it away, and then behaves as if the sync succeeded and swaps out the last known config with a corrupt config.

I believe if it were to return errors here (and other places where it is currently throwing away the errors):

https://github.com/containous/traefik/blob/master/provider/kubernetes.go#L194

Then it wouldn't override the config here, and the last good state would be maintained instead of being cleared out:

https://github.com/containous/traefik/blob/master/provider/kubernetes.go#L88

### PR DESCRIPTION
**Pull request by Regner**
Currently if a Kubernetes API call fails we potentially remove a working service from Traefik. This changes it so if a Kubernetes API call fails we abort out of the ingress update and use the current working config. Github issue: #1240 

Tests are currently failing but wanted to get the PR up for a few reasons:
1. Confirm this is how we want to solve this issue (abort the whole ingress update if a single API call fails)
2. That there isn't a better way to do the tests
3. I would like the tests to catch a specific error, but don't know what error to expect being raised from the API call

Fixes #1240

### CODE REVIEW

File: provider/kubernetes_test.go [hunk 1]
```diff
@@ -1524,11 +1524,80 @@ func TestServiceAnnotations(t *testing.T) {
...
+
+	client = clientMock{
+		ingresses:         ingresses,
+		services:          services,
+		endpoints:         endpoints,
+		watchChan:         watchChan,
+		apiEndpointsError: true,
+	}
+	provider = Kubernetes{}
+	_, err = provider.loadIngresses(client)
```
Comment (timoreimann) [inline provider/kubernetes_test.go]: I suggest we convert the test into a [table-driven one](https://github.com/golang/go/wiki/TableDrivenTests) using [sub-tests](https://blog.golang.org/subtests). Among several benefits, this should improve readability and reduce the amount of test code needed.

File: provider/kubernetes_test.go [hunk 2]
```diff
@@ -1524,11 +1524,80 @@ func TestServiceAnnotations(t *testing.T) {
...
+		services:        services,
+		endpoints:       endpoints,
+		watchChan:       watchChan,
+		apiServiceError: true,
+	}
+	provider := Kubernetes{}
+	_, err := provider.loadIngresses(client)
+
+	if err == nil {
+		t.Fatal("Should have raised error when loading services but did not.")
```
Comment (timoreimann) [inline provider/kubernetes_test.go]: This can be `t.Error` in my view.

File: provider/kubernetes_test.go [hunk 3]
```diff
@@ -1543,6 +1612,10 @@ func (c clientMock) GetIngresses(namespaces k8s.Namespaces) []*v1beta1.Ingress {
 }
 
 func (c clientMock) GetService(namespace, name string) (*v1.Service, bool, error) {
+	if c.apiServiceError {
+		return &v1.Service{}, true, c.err
```
Comment (timoreimann) [inline provider/kubernetes_test.go]: Conventionally, if an error occurs in a function returning multiple values, the non-`error` parameters are set to their default values. Thus, I'd use `false` for the boolean return value.

Slightly related/unrelated: I don't know why we return `true` in line 1624 when we seemingly can't find the service.

File: provider/kubernetes_test.go [hunk 4]
```diff
@@ -1552,6 +1625,10 @@ func (c clientMock) GetService(namespace, name string) (*v1.Service, bool, error
 }
 
 func (c clientMock) GetEndpoints(namespace, name string) (*v1.Endpoints, bool, error) {
+	if c.apiEndpointsError {
+		return &v1.Endpoints{}, true, c.err
```
Comment (timoreimann) [inline provider/kubernetes_test.go]: Also `false` here.

File: provider/kubernetes_test.go [hunk 5]
```diff
@@ -1524,11 +1524,80 @@ func TestServiceAnnotations(t *testing.T) {
 	}
 }
 
+func TestGetServiceErrors(t *testing.T) {
+	ingresses := []*v1beta1.Ingress{
+		{
+			ObjectMeta: v1.ObjectMeta{
+				Namespace: "testing",
+				Annotations: map[string]string{
+					"traefik.frontend.passHostHeader": "true",
```
Comment (timoreimann) [inline provider/kubernetes_test.go]: Do we need this annotation for the tests at hand?

I'm always in favor of keeping test fixtures as minimized as possible.

File: provider/kubernetes_test.go [hunk 6]
```diff
@@ -1524,11 +1524,80 @@ func TestServiceAnnotations(t *testing.T) {
...
+				},
+			},
+			Spec: v1beta1.IngressSpec{
+				Rules: []v1beta1.IngressRule{
+					{
+						Host: "foo",
```
Comment (timoreimann) [inline provider/kubernetes_test.go]: Needed?

File: provider/kubernetes.go [hunk 7]
```diff
@@ -169,10 +169,13 @@ func (provider *Kubernetes) loadIngresses(k8sClient k8s.Client) (*types.Configur
...
-				if err != nil || !exists {
-					log.Warnf("Error retrieving service %s/%s: %v", i.ObjectMeta.Namespace, pa.Backend.ServiceName, err)
-					delete(templateObjects.Frontends, r.Host+pa.Path)
-					continue
+				if err != nil {
+					log.Errorf("Error while retrieving service information from k8s API %s/%s: %v", service.ObjectMeta.Namespace, pa.Backend.ServiceName, err)
+					return nil, err
+				}
+
+				if !exists {
```
Comment (timoreimann) [inline provider/kubernetes.go]: I don't see a test for this case. I suppose it's already covered by a pre-existing test?

File: provider/kubernetes.go [hunk 8]
```diff
@@ -196,10 +199,10 @@ func (provider *Kubernetes) loadIngresses(k8sClient k8s.Client) (*types.Configur
 						endpoints, exists, err := k8sClient.GetEndpoints(service.ObjectMeta.Namespace, service.ObjectMeta.Name)
 						if err != nil || !exists {
```
Comment (timoreimann) [inline provider/kubernetes.go]: Any particular reason we not splitting up the two cases here as well?

File: provider/kubernetes_test.go [hunk 9]
```diff
@@ -1524,11 +1524,80 @@ func TestServiceAnnotations(t *testing.T) {
...
+	}
+}
+
 type clientMock struct {
 	ingresses []*v1beta1.Ingress
 	services  []*v1.Service
 	endpoints []*v1.Endpoints
 	watchChan chan interface{}
+
+	err               error
```
Comment (timoreimann) [inline provider/kubernetes_test.go]: You can get rid of this variable by changing the type of `api{Service,Endpoints}Error` to `error` and returning the error if it's non-nil in the stubbed getter methods.

File: provider/kubernetes_test.go (hunk 2 above)
Comment (timoreimann) [inline provider/kubernetes_test.go]: Instead of just checking for the error being `nil`, what I think we can do here is pass a custom error variable to the mock (e.g., `errors.New("failed")`) and check against this very error. It shouldn't matter what error value we inject since our code doesn't depend on any specific error -- we just want to verify that we return the error to the caller that the (mocked) API gives us.
Similar for the endpoint case.

I hope this addresses your third question.

File: provider/kubernetes.go (hunk 7 above)
Comment (Regner) [inline provider/kubernetes.go]: You mean the does not exist part? No that was on my todo list, it is actually why the ingress part of the new test has sample data. Was thinking of moving it to a separate test though.

File: provider/kubernetes.go (hunk 8 above)
Comment (Regner) [inline provider/kubernetes.go]: A bad rebase is why actually. Specifically wrote some test code for it. Will fix,

File: provider/kubernetes_test.go (hunk 5 above)
Comment (Regner) [inline provider/kubernetes_test.go]: Going to move it to a separate test specifically for checking the !exists cases.

File: provider/kubernetes_test.go (hunk 6 above)
Comment (Regner) [inline provider/kubernetes_test.go]: See above.

File: provider/kubernetes_test.go (hunk 2 above)
Comment (Regner) [inline provider/kubernetes_test.go]: That should work great. Will make the change.

**Comment by Regner** [comment]
Tests SHOULD be passing now. Still need to move the tests over to using the table driven test method, need to add tests for the !exists code paths, and am not sure how we want to handle when things don't exist. For example when a service doesn't exist do we still add the frontend? The two cases of this right now are when services or endpoints don't exist. Both cases can easily be someone putting a typo in the service name or port name.

File: provider/kubernetes.go (hunk 7 above)
Comment (timoreimann) [inline provider/kubernetes.go]: Separate test sounds good. :+1:

**Comment by timoreimann** [comment]
AFAICS, the only alternative we have to skipping frontends with missing services/endpoints is to revert the entire configuration (i.e., apply the error case resolution). IMHO, we shouldn't do that since such misses are usually due to a user mistake (as you said) and would consequently "punish" all other frontends that did everything correct.
There's also the case where a service or endpoint isn't available because the k8s reconciliation loops haven't completed yet. That's another situation where skipping and hoping for the next watch API event to trigger a benevolent update seems like the better option to me.

I believe the focus of this PR should be to fix #1240, which is to protect against the Kube API temporarily being unavailable. By handling that case gracefully (through reverting to the previous configuration) and maintaining the "missing" behavior as-is, I think we have satisfied the goal at hand. Potential improvements to the missing case, especially if the direction isn't super clear, can be handled by follow-up issues/PRs.

Just my 2 cents. :)

**Comment by Regner** [comment]
Was reviewing this PR this morning and noticed that the condition in my new test to check for failure was actually wrong and would be passing even if it shouldn't.

Fixed that and added test data back in. Without the test data the loadIngress logic doesn't get far enough along to trigger the errors we want to test for. So added the test data back in.

Very sorry about that! The logic in loadIngress was fine and I didn't have to make any changes there. It was just the tests not actually doing anything useful.

File: provider/kubernetes_test.go [hunk 10]
```diff
@@ -1524,11 +1525,89 @@ func TestServiceAnnotations(t *testing.T) {
...
+		ingresses:       ingresses,
+		services:        services,
+		endpoints:       endpoints,
+		watchChan:       watchChan,
+		apiServiceError: errors.New("failed service call"),
+	}
+	provider := Kubernetes{}
+	_, err := provider.loadIngresses(client)
+
+	if err == nil || err.Error() != "failed service call" {
```
Comment (timoreimann) [inline provider/kubernetes_test.go]: We can simplify the assertion by comparing error values:

```go
if err != client.apiServiceError {
  ...
}
```

Once you turn the test into a table-driven one, define and inject an error variable `var apiErr = errors.New("error")` and compare against that in each test case.

File: provider/kubernetes_test.go [hunk 11]
```diff
@@ -1524,11 +1525,89 @@ func TestServiceAnnotations(t *testing.T) {
...
+		ingresses:         ingresses,
+		services:          services,
+		endpoints:         endpoints,
+		watchChan:         watchChan,
+		apiEndpointsError: errors.New("failed endpoints call"),
+	}
+	provider = Kubernetes{}
+	_, err = provider.loadIngresses(client)
+
+	if err == nil || err.Error() != "failed endpoints call" {
```
Comment (timoreimann) [inline provider/kubernetes_test.go]: Same pattern as above.

File: provider/kubernetes_test.go [hunk 12]
```diff
@@ -1524,11 +1525,97 @@ func TestServiceAnnotations(t *testing.T) {
...
+				{
+					Port: 80,
+				},
+			},
+		},
+	}}
+
+	endpoints := []*v1.Endpoints{}
+	watchChan := make(chan interface{})
+	apiErr := errors.New("failed")
```
Comment (emilevauge) [inline provider/kubernetes_test.go]: Minor comment, but I would use something more random than _failed_ here.

File: provider/kubernetes.go (hunk 7 above)
Comment (Regner) [inline provider/kubernetes.go]: Added tests for this and the !exists endpoints

**Comment by Regner** [comment]
Commits all squashed and that final test case added.

@timoreimann be aware, as this isn't obvious with the squash, that I renamed the test from `TestServiceErrors` to `TestKubeAPIErrors` as it isn't just related to services but endpoints as well.

I also changed `apiErr := errors.New("failed")` to `apiErr := errors.New("failed kube api call")` as per the comment from @emilevauge.

Other then that I only added the `TestMissingResources` test case and nothing else should have changed.

File: provider/kubernetes_test.go [hunk 13]
```diff
@@ -1524,11 +1525,283 @@ func TestServiceAnnotations(t *testing.T) {
...
+										ServiceName: "service1",
+										ServicePort: intstr.FromInt(80),
+									},
+								},
+							},
+						},
+					},
+				},
+				{
+					Host: "bar",
```
Comment (timoreimann) [inline provider/kubernetes_test.go]: Suggestion: Could we change the host name to something like "host_with_missing_service" or place an according comment to indicate that the purpose of this Ingress resource test-wise is to not be found because of that reason?

It takes a bit of back of forth scrolling to understand the purpose of the individual objects this test is setting up. I think purposeful names / comments could alleviate that.

File: provider/kubernetes_test.go [hunk 14]
```diff
@@ -1524,11 +1525,283 @@ func TestServiceAnnotations(t *testing.T) {
...
+										ServiceName: "service2",
+										ServicePort: intstr.FromInt(80),
+									},
+								},
+							},
+						},
+					},
+				},
+				{
+					Host: "tar",
```
Comment (timoreimann) [inline provider/kubernetes_test.go]: Similarly, something that indicates this Ingress' Service's Endpoints are missing?

**Comment by timoreimann** [comment]
The new `TestMissingResources` test is still failing according to CI.

**Comment by Regner** [comment]
My most recent commit where I add a blank Servers attribute the "missing_service" expected output is required to pass the diff. @timoreimann helped me figure this out, but essentially without it we end up comparing a nil to a blank Servers definition.

```
-          (string) (len=15) "missing_service": (*types.Backend)(0xc4201b0450)({
-           Servers: (map[string]types.Server) <nil>,
+          (string) (len=15) "missing_service": (*types.Backend)(0xc4201b0270)({
+           Servers: (map[string]types.Server) {
+           },
```

One of the unfortunate parts of that is the normal logging we do for the failed comparison doesn't show this difference. The above output was retrieved when @timoreimann made the following change:

```
if !reflect.DeepEqual(actual, expected) {
    t.Fatalf("expected %+v, got %+v", string(expectedJSON), string(actualJSON))
    t.Fatalf("expected\n%v\ngot\n\n%v", spew.Sdump(expected), spew.Sdump(actual))
}
```

Something to keep in mind in the future.

**Comment by timoreimann** [comment]
@Regner I pushed a small commit that includes a link to #1307.

The tests went green before, so I think as soon as we have @emilevauge's approval, we can squash and merge. 🎉

**Comment by Regner** [comment]
Good call on adding the link
