### PR TITLE
Fix default weight in server.LoadConfig

### LINKED ISSUE #480: loadConfig modifies configuration causing same config check to fail
Moving my comment from #478 to make it easier to track.

In same config check the "old" config also have `loadBalancer` blocks in the backend config where the new from the provider does not. This from line 444 in server.go

I think the fix to this is to never modify the config in loadConfig but I'm not really sure where should go instead.

```
        "backend-eremetic": {
            "servers": {
                "eremetic--10-4-72-161--8182--monitor--api--monitor--6": {
                    "url": "http://10.4.72.161:8182",
                    "weight": 0
                }
            },
            "loadBalancer": {
                "method": "wrr"
            }
        },
```

```
        "backend-eremetic": {
            "servers": {
                "eremetic--10-4-72-161--8182--monitor--api--monitor--6": {
                    "url": "http://10.4.72.161:8182",
                    "weight": 0
                }
            }
        },
```

### PR DESCRIPTION
**Pull request by emilevauge**
Fixes #480

Signed-off-by: Emile Vauge <emile@vauge.com>

### CODE REVIEW

File: server.go [hunk 1]
```diff
@@ -181,6 +181,12 @@ func (server *Server) defaultConfigurationValues(configuration *types.Configurat
 			frontend.EntryPoints = server.globalConfiguration.DefaultEntryPoints
 		}
 	}
+	for _, backend := range configuration.Backends {
+		_, err := types.NewLoadBalancerMethod(backend.LoadBalancer)
+		if err != nil {
+			backend.LoadBalancer = &types.LoadBalancer{Method: "wrr"}
```
Comment (vdemeester) [inline server.go]: Should this be logged ? :angel: (like "wrong backend.LoadBlancer, using default..")

**Comment by vdemeester** [comment]
@emilevauge quick question. Otherwise, LGTM 🐹

File: server.go (hunk 1 above)
Comment (emilevauge) [inline server.go]: You're right !
