### PR TITLE
fix: Empty Rancher Service Labels.

### LINKED ISSUE #1615: Traefik crashes when calling Rancher's APIs.
### What version of Traefik are you using?
```
Version:      v1.2.3
Codename:     morbier
Go version:   go1.7.5
Built:        2017-04-13_07:21:10PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml...)?
```json
{
 "GraceTimeOut": 10,
 "Debug": false,
 "CheckNewVersion": true,
 "AccessLogsFile": "",
 "TraefikLogsFile": "",
 "LogLevel": "ERROR",
 "EntryPoints": {
  "http": {
   "Network": "",
   "Address": ":80",
   "TLS": null,
   "Redirect": null,
   "Auth": null,
   "Compress": false
  }
 },
 "Cluster": null,
 "Constraints": [],
 "ACME": null,
 "DefaultEntryPoints": [
  "http"
 ],
 "ProvidersThrottleDuration": 2000000000,
 "MaxIdleConnsPerHost": 200,
 "InsecureSkipVerify": false,
 "Retry": null,
 "Docker": null,
 "File": null,
 "Web": {
  "Address": ":8080",
  "CertFile": "",
  "KeyFile": "",
  "ReadOnly": false,
  "Statistics": null,
  "Metrics": null,
  "Auth": null
 },
 "Marathon": null,
 "Consul": null,
 "ConsulCatalog": null,
 "Etcd": null,
 "Zookeeper": null,
 "Boltdb": null,
 "Kubernetes": null,
 "Mesos": null,
 "Eureka": null,
 "ECS": null,
 "Rancher": {
  "Watch": true,
  "Filename": "",
  "Constraints": null,
  "Endpoint": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "AccessKey": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
  "SecretKey": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
  "ExposedByDefault": true,
  "Domain": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
 },
 "ConfigFile": "/etc/traefik/traefik.toml"
}
```

### What did you do?

I am trying to integrate Traefik with Rancher using the configuration file to proxy containers. As you can see I kept my configuration as simple as possibile, basing on the one provided in the documentation.
This issue is related to #1218 
but for everyone of them seems to have solved; of course this is not my case :D

The Rancher version i'm currently using is 1.5.9 (stable).
```toml
defaultEntryPoints = ["http"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
[web]
address = ":8080"
[rancher]
domain = "XXX"
ExposedByDefault = true
Endpoint = "http://XXX/v1"
AccessKey = "XXX"
SecretKey = "XXX"
```
### What did you expect to see?
I expect to see traefik working

### What did you see instead?
```shell
ERRO[2017-05-16T16:54:16Z] Error in Go routine: runtime error: invalid memory address or nil pointer dereference
goroutine 57 [running]:
runtime/debug.Stack(0x4e837f, 0xc42000c2c0, 0x1db66d3)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x79
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/containous/traefik/safe.defaultRecoverGoroutine(0x1af0560, 0xc42000a040)
        /go/src/github.com/containous/traefik/safe/routine.go:147 +0x7d
github.com/containous/traefik/safe.GoWithRecover.func1.1(0x1eb3a50)
        /go/src/github.com/containous/traefik/safe/routine.go:138 +0x57
panic(0x1af0560, 0xc42000a040)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/containous/traefik/provider.parseRancherData(0xc42034e300, 0x14, 0x20, 0xc42046ea00, 0x2f, 0x40, 0xc42034ee00, 0x14, 0x20, 0x2bc8032d, ...)
        /go/src/github.com/containous/traefik/provider/rancher.go:373 +0x298
github.com/containous/traefik/provider.(*Rancher).Provide.func1.1(0xc4203546c0, 0x42b488)
        /go/src/github.com/containous/traefik/provider/rancher.go:236 +0x217
github.com/containous/traefik/vendor/github.com/cenk/backoff.RetryNotify(0xc4203e2e60, 0x2a9cb00, 0xc4201895e0, 0x1eb39f0, 0xc420490f48, 0x65f19f)
        /go/src/github.com/containous/traefik/vendor/github.com/cenk/backoff/retry.go:32 +0x3f
github.com/containous/traefik/provider.(*Rancher).Provide.func1()
        /go/src/github.com/containous/traefik/provider/rancher.go:280 +0x132
github.com/containous/traefik/safe.GoWithRecover.func1(0x1eb3a50, 0xc4203e2e40)
        /go/src/github.com/containous/traefik/safe/routine.go:141 +0x4d
created by github.com/containous/traefik/safe.GoWithRecover
        /go/src/github.com/containous/traefik/safe/routine.go:142 +0x49
```

Thank you

### PR DESCRIPTION
**Pull request by ldez**
### Description

Fixes #1615

### CODE REVIEW

File: provider/rancher/rancher.go [hunk 1]
```diff
@@ -388,8 +388,12 @@ func parseRancherData(environments []*rancher.Environment, services []*rancher.S
 				Containers: []string{},
 			}
 
-			for key, value := range service.LaunchConfig.Labels {
-				rancherData.Labels[key] = value.(string)
+			if service.LaunchConfig == nil || service.LaunchConfig.Labels == nil {
+				log.Warnf("Rancher Service Labels are missing.")
```
Comment (emilevauge) [inline provider/rancher/rancher.go]: We may add `service.Name` in the log
