### PR TITLE
Fix error handling for docker swarm mode

### LINKED ISSUE #1100: Docker watch is terminated after first error
### What version of Traefik are you using (`traefik version`)?
1.1.2

### What is your environment & configuration (arguments, toml...)?
```
[docker]
endpoint = "tcp://...."
domain = "..."
watch = true
swarmmode = true
exposedbydefault = true
```

### What did you do?
Docker swarm is not available for short time

### What did you expect to see?
Watch will continue working after error

### What did you see instead?
Watch is terminated after first error
example error:
```
level=error msg="Failed to list services for docker, error Error response from daemon: rpc error: code = 2 desc = raft: no elected cluster leader"
```

### PR DESCRIPTION
**Pull request by tanyadegurechaff**
### Description

Fixes #1100

### CODE REVIEW

**Comment by tanyadegurechaff** [comment]
This makes backoff operation return error when an error occurs, and the operation will be retried.

**Comment by tanyadegurechaff** [comment]
Could you explain in detail how a memory leak comes about?

**Comment by emilevauge** [comment]
@tanyadegurechaff @beldpro-ci After reading more in details, indeed, it does not introduce any memory leak in this case. But it is still better to defer close the channel, especially because it's [inside a go routine](https://github.com/containous/traefik/pull/1533/files#diff-fa150917b5a9de47451ce96099822a9dR120). We had many leaks in the past do to not closed channels. Other than that, seems great :)

**Comment by tanyadegurechaff** [comment]
Thank you for your feedbacks. @beldpro-ci @emilevauge

File: provider/docker/docker.go [hunk 1]
```diff
@@ -153,15 +153,18 @@ func (p *Provider) Provide(configurationChan chan<- types.ConfigMessage, pool *s
 			if p.Watch {
 				ctx, cancel := context.WithCancel(ctx)
 				if p.SwarmMode {
+					errChan := make(chan error)
 					// TODO: This need to be change. Linked to Swarm events docker/docker#23827
 					ticker := time.NewTicker(SwarmDefaultWatchTime)
 					pool.Go(func(stop chan bool) {
+						defer close(errChan)
```
Comment (ldez) [inline provider/docker/docker.go]: why you put the defer here?
I think you must move this line under the line 156.

Comment (tanyadegurechaff) [inline provider/docker/docker.go]: The receiver at line 185 blocks the execution until the channel is closed or received an error.

Comment (emilevauge) [inline provider/docker/docker.go]: I agree with @tanyadegurechaff on this. But it would be better to use this syntax instead:
```go
if err, ok := <-errChan; ok {
  return err
} else {
  // channel closed
  ...
}
```

Comment (tanyadegurechaff) [inline provider/docker/docker.go]: I agree, but I got an error from golint:
```
provider/docker/docker.go:187:13: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary)
```

Comment (ldez) [inline provider/docker/docker.go]: just do:
```golang
if err, ok := <-errChan; ok {
  return err
}
 // channel closed
 // ...
```

**Comment by ldez** [comment]
Due to SemaphoreCI, I close and reopen the PR.
