### PR TITLE
Force http/1.1 for upgrade (Traefik v2)

### LINKED ISSUE #6527: Cannot proxy kube-apiserver
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

```
cd $(mktemp -d)
export KUBECONFIG=$PWD/conf
kind create cluster

# download values and ingress
curl -L https://gist.github.com/joejulian/ebba694a625333dc989a288a221c04cd/archive/0eecf28355c1a11d1965457a0cf44202ca972ded.tar.gz | tar xzv --strip 1

# deploy traefik and create ingress 
helm install traefik stable/traefik --values traefik_values.yaml
kubectl apply -f ingress.yaml

# create token account for testing. This represents an analog for oidc auth.
kubectl create sa test
kubectl get clusterrolebinding cluster-admin -o yaml | yq '.subjects[.subjects | length] |=.+ {kind: "ServiceAccount", name: "test", namespace: "default"}' | kubectl apply -f -

# set some variables to use when we switch configs
TOKEN="$(kubectl get secret "$(kubectl get serviceaccounts test -o jsonpath='{.secrets[0].name}')" -o jsonpath='{.data.token}' | base64 -d)"
POD="$(kubectl get pod -l app=traefik -o jsonpath='{.items[0].metadata.name}' )"

# port forward to traefik since we can't reach the node port from the host
kubectl port-forward $POD 8443:443 &

# create a kubeconfig that uses token auth
yq -y '.users[0]={name: "kind-kind", user: { token: "'$TOKEN'" }}' conf | yq -y '.clusters[0].cluster.server="https://127.0.0.1:8443/testpath"' > conf-token

kubectl --kubeconfig conf-token --insecure-skip-tls-verify -v9 port-forward $POD 8080
```
### What did you expect to see?
```
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080
```

### What did you see instead?
```
Handling connection for 8443
Handling connection for 8443
error: error upgrading connection: unable to upgrade connection: Internal Server Error
```

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      v1.7.20
Codename:     maroilles
Go version:   go1.12.14
Built:        2019-12-10_05:02:10PM
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?

```toml
# set by chart template
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

_filtered out 'event kind'_
https://gist.github.com/joejulian/dd2ae3cdb1de5d9354923fab6e1a69a1

### PR DESCRIPTION
**Pull request by juliens**
### What does this PR do?

This PR forces the use of http1.1 with the backend when the request is a `Connection:Upgrade` because `Connection: Upgrade` is not valid for http2.

Also, this PR fixes the fact that specifying root CAs and specifying insecureskipverify was mutually exclusive.

### Motivation
Some kubernetes api server refuse http2 during tls-alpn (like k3s) but some other just don't (like kind) and so, SPDY upgrade fails. This PR fixes this behavior.

Fixes #6527 

### More

~- [ ] Added/updated tests~
~- [ ] Added/updated documentation~

### CODE REVIEW

File: pkg/server/service/smart_roundtripper.go [hunk 1]
```diff
@@ -0,0 +1,36 @@
...
+		http:  transportHTTP1,
+	}, nil
+}
+
+type smartRoundTripper struct {
+	http2 *http.Transport
+	http  *http.Transport
+}
+
+func (m *smartRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
```
Comment (mpl) [inline pkg/server/service/smart_roundtripper.go]:
```suggestion
// smartRoundTripper implements RoundTrip while making sure that HTTP/2 is not used
// with protocols that start with a Connection Upgrade, such as SPDY or Websocket.
func (m *smartRoundTripper) RoundTrip(req *http.Request) (*http.Response, error) {
```

File: pkg/server/service/smart_roundtripper.go [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+	// If we have a connection upgrade, we don't use HTTP2
```
Comment (mpl) [inline pkg/server/service/smart_roundtripper.go]:
```suggestion
	// If we have a connection upgrade, we don't use HTTP/2
```
