### PR TITLE
Fix acme renew panic

### LINKED ISSUE #269: Traefik panics due to ACME
Traefik panicked due to a certificate renew request.

```
goroutine 44 [running]:
panic(0xc119c0, 0xc82000a080)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/containous/traefik/acme.(*ACME).renewCertificates(0xc820068880, 0xc820089320, 0xc8200df680, 0x0, 0x0)
	/go/src/github.com/containous/traefik/acme/acme.go:293 +0x871
github.com/containous/traefik/acme.(*ACME).CreateConfig.func2(0xc8202eb340, 0xc820068880, 0xc820089320, 0xc8200df680)
	/go/src/github.com/containous/traefik/acme/acme.go:253 +0x91
created by github.com/containous/traefik/acme.(*ACME).CreateConfig
	/go/src/github.com/containous/traefik/acme/acme.go:259 +0x7ea
```

### PR DESCRIPTION
**Pull request by emilevauge**
This PR fixes an issue with Let's Encrypt certificate renew process.
It also adds a recovering mechanism for some goroutines:

```
func GoSafe(goroutine func()) {
	go func() {
		defer recoverGoroutine()
		goroutine()
	}()
}

func recoverGoroutine() {
	if err := recover(); err != nil {
		log.Println(err)
		debug.PrintStack()
	}
}
```

```
safe.GoSafe(func() {
	// my safe go routine
})
```

Fixes #269 

Signed-off-by: Emile Vauge <emile@vauge.com>

### CODE REVIEW

**Comment by emilevauge** [comment]
@rebaseTraefik

File: safe/safe.go [hunk 1]
```diff
@@ -0,0 +1,21 @@
+package safe
+
+import (
+	"log"
+	"runtime/debug"
+)
+
+// GoSafe starts a recoverable goroutine
+func GoSafe(goroutine func()) {
```
Comment (vdemeester) [inline safe/safe.go]: I think the name could be `Go` and that's all ; that way, no repeat of the `safe` word, and it looks cool `safe.Go(…)`.

File: safe/safe.go [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+	go func() {
+		defer recoverGoroutine()
+		goroutine()
+	}()
+}
+
+func recoverGoroutine() {
```
Comment (vdemeester) [inline safe/safe.go]: For future uses, I would rename this `defaultRecoverGoroutine` and add a new `GoWithRecover` method (*meh* for the name though :stuck_out_tongue_closed_eyes:) that would allow to execute a custom function for recovering. @emilevauge WDYT ?

File: safe/safe.go (hunk 1 above)
Comment (emilevauge) [inline safe/safe.go]: your right

File: safe/safe.go (hunk 2 above)
Comment (emilevauge) [inline safe/safe.go]: nice idea :)

**Comment by vdemeester** [comment]
LGTM 🐸
