### PR TITLE
Fix marathon groups subdomain

### LINKED ISSUE #169: Marathon directory as a subdomain
Change default frontend Host value from `foobar.marathon.localhost` to `foo.bar.marathon.localhost` for Marathon apps with ID `/foo/bar`.

### PR DESCRIPTION
**Pull request by emilevauge**
Fix marathon [groups](https://mesosphere.github.io/marathon/docs/application-groups.html) subdomain management.

Added new optional `groupsAsSubDomains`:

```
# Convert Marathon groups to subdomains
# Default behavior: /foo/bar/myapp => foo-bar-myapp.{defaultDomain}
# with groupsAsSubDomains enabled: /foo/bar/myapp => myapp.bar.foo.{defaultDomain}
#
# Optional
# Default: false
#
# groupsAsSubDomains = true
```

If enabled, instead of:
`/foo/bar/myapp` => `foo-bar-myapp.{defaultDomain}`
we now have:
`/foo/bar/myapp` => `myapp.bar.foo.{defaultDomain}`

Fixes #169

Signed-off-by: Emile Vauge <emile@vauge.com>

### CODE REVIEW

**Comment by vdemeester** [comment]
LGTM 🐸

**Comment by kbroughton** [comment]
lgtm

File: provider/marathon.go [hunk 1]
```diff
@@ -21,13 +21,14 @@ import (
...
 // Marathon holds configuration of the Marathon provider.
 type Marathon struct {
-	BaseProvider     `mapstructure:",squash" description:"go through"`
-	Endpoint         string `description:"Marathon server endpoint. You can also specify multiple endpoint for Marathon"`
-	Domain           string `description:"Default domain used"`
-	ExposedByDefault bool   `description:"Expose Marathon apps by default"`
-	Basic            *MarathonBasic
-	TLS              *tls.Config
-	marathonClient   marathon.Marathon
+	BaseProvider       `mapstructure:",squash" description:"go through"`
```
Comment (cocap10) [inline provider/marathon.go]: The `StructTag` is useless ...
I think I forgot to remove this one...
@emilevauge : Can you delete it ?

Comment (emilevauge) [inline provider/marathon.go]: Indeed ;)
